### ISSUE TITLE
Use -mno-red-zone

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#10]
See [monocasa's comment] on reddit and the [OSDev forum].

[monocasa's comment]: https://www.reddit.com/r/programming/comments/3q6y2l/writing_an_os_in_rust/cwcu8g0
[OSDev forum]: http://forum.osdev.org/viewtopic.php?t=21720

**Comment by steveklabnik** [comment]
http://www.randomhacks.net/2015/11/11/bare-metal-rust-custom-target-kernel-space/ is helpful

**Comment by phil-opp** [comment]
Closing as the "Set Up Rust" post mentions it now. There will be an detailed explanation in an upcoming post about CPU exceptions/interrupts.
