### ISSUE TITLE
Add some notes regarding problems with `grub-mkrescue`

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#104]
It seems like `grub-mkrescue` causes some issues. See [this comment](http://os.phil-opp.com/multiboot-kernel.html#comment-2436330071).

**Update**: We should add some notes regarding

- [ ] the different naming of `grub-mkrescue` in some distros (`grub2-mkrescue`) 
- [ ] the need for `mtools` (to create an EFI image) or `-d /usr/lib/grub/i386-pc` (to avoid EFI) on EFI systems 
- [ ] that `xorriso` is contained in `libisoburn` for some distros

**Comment by birkenfeld** [comment]
Both are actually the same program, and it's just up to the distribution how they like their binaries to be called. Most distributions I've come across use `grub-*`, but e.g. Gentoo uses `grub2-*`.

So please don't just replace, but add a comment that the `2` might be required.

**Comment by birkenfeld** [comment]
As for the EFI issue, there two solutions to get grub-mkrescue to work:

* Install `mtools`, which is used by grub-mkrescue to create efi.img
* Use `-d /usr/lib/grub/i386-pc` (may also be distribution specific) to avoid using EFI

Once mtools was installed, I had no problems getting the EFI-enabled iso booting in qemu.

**Comment by birkenfeld** [comment]
One more thing: `xorriso` is contained (again, for some distributions) in the awkwardly-named package `libisoburn`, which might also warrant a note.

**Comment by phil-opp** [comment]
Thank you very much! I will add some notes for these things.

**Comment by spratt** [comment]
Additionally, while I see xorriso is mentioned in the text it's not mentioned in the github readme.  I have been trying to build before reading the blog post, and consequently I didn't know to install xorriso.  `make run` fails with error 127 when xorriso isn't installed.

**Comment by phil-opp** [comment]
@spratt Thanks! I have little time at the moment, so I just added `xorriso` to the Readme. But I plan to add a troubleshooting page with more details.
