### ISSUE TITLE
How can I get contact with author @phil-opp?

### ISSUE THREAD

**Issue by luojia65** [phil-opp/blog_os#1047]
Writing an OS in Rust is a wonderful book, as a reminder I translated the book two years ago into Chinese. Recently one editor contacted me to see if the translated work could get published, and of course it requires original authors to agree in e-mail.
How can I contact original authors? Are there any e-mail addresses? @bjorn3 @phil-opp 
Please e-mail me at me@luojia.cc . Thanks!

**Comment by bjorn3** [comment]
The github profile of @phil-opp lists their email. @phil-opp is the sole author and I think the sole copyright holder. At least most of the changes by others are too small to be copyrightable I think, but IANAL.

**Comment by phil-opp** [comment]
Hi @luojia65, sorry for not replying to your email yet. I'm still thinking about your proposal. To be honest, I'm not sure how I feel about the idea of turning this hobby project that I've been working on for ~6 years into a for-profit thing. But let's discuss this over email, I'll try to reply to you soon.

**Comment by rasheedmhd** [comment]
What is the progress on this? if conversations have been taken privately to mail we can close this issue?

**Comment by phil-opp** [comment]
Yeah, I think we can close this
