### ISSUE TITLE
Error while trying to build (latest async post)

### ISSUE THREAD

**Issue by LorenzoDeMarco** [phil-opp/blog_os#1048]
Greetings.
My project has been compiling and running just fine up until today. For some reason when I run cargo build it says:
```
error: Package `test v0.0.0 (/home/[REDACTED]/.rustup/toolchains/nightly-2020-09-30-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test)` does not have these features: `compiler-builtins-mem`
```
It doesn't compile anymore. I have the proper
```rust
#![feature(custom_test_frameworks)]
#![test_runner(ledom_os::test_runner)]
#![reexport_test_harness_main = "test_main"]
```
in `main.rs` and `lib.rs`. Any thoughts on that?

Here is my `rustup show` for reference:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/[REDACTED]/.rustup

installed toolchains
--------------------

nightly-2020-07-27-x86_64-unknown-linux-gnu
nightly-2020-09-30-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-2020-09-30-x86_64-unknown-linux-gnu (directory override for '/media/[REDACTED]_os')
rustc 1.48.0-nightly (381b445ff 2020-09-29)

```

**Comment by bjorn3** [comment]
The feature does exist: https://github.com/rust-lang/rust/blob/9f85cd6f2ab2769c16e89dcdddb3e11d9736b351/library/test/Cargo.toml#L26

By the way why is it compiling libtest at all? You should limit it to libcore and liballoc as you don't run inside an os and thus libstd and libtest are not supported.

Did you setup `.cargo/config.toml` like in https://os.phil-opp.com/minimal-rust-kernel/#the-build-std-option?

**Comment by LorenzoDeMarco** [comment]
> By the way why is it compiling libtest at all? You should limit it to libcore and liballoc as you don't run inside an os and thus libstd and libtest are not supported.
I know, and having the custom test framework defined it shouldn't try to use the builtin one.

> Did you setup `.cargo/config.toml` like in https://os.phil-opp.com/minimal-rust-kernel/#the-build-std-option?
I did, here it is:
```toml
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
```

**Comment by LorenzoDeMarco** [comment]
I tried to restore the `.cargo` and `.rustup` folders from my weekly backup and it's throwing a new error...
```
error[E0152]: found duplicate lang item `oom`
  --> src/lib.rs:27:1
   |
27 | fn alloc_error_handler(layout: alloc::alloc::Layout) -> ! {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: the lang item is first defined in crate `std` (which `num_traits` depends on)
   = note: first definition in `std` loaded from /media/hdd2t02/Progetti/ledom_os/target/x86_64-ledom_os/debug/deps/libstd-c4e256477614c48e.rmeta
   = note: second definition in the local crate (`ledom_os`)
```
Why is it trying to include stuff from std at all costs?

**Comment by bjorn3** [comment]
Which dependencies do you have? It seems that `num_traits` pulls in libstd when it shouldn't.

**Comment by LorenzoDeMarco** [comment]
My ATA disk module (not part of the vanilla blog_os) uses num_traits::float::FloatCore, so I added num_traits as a dependency. If I remove the dependency and the ATA module it fails again. Not to mention that it used to compile and work fine even with num_traits.
I tried doing a `cargo clean` but nothing changed. Here is the dependency:
```toml
[dependencies.num-traits]
version = "0.2.14"
default-features = false
```

**Comment by bjorn3** [comment]
Are there any other dependencies that depend on num-traits? You can look in `Cargo.lock` to find all crates that depend on it.

**Comment by LorenzoDeMarco** [comment]
There is one, `vga`:
```toml

[[package]]
name = "vga"
version = "0.2.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "67cbcb7bfff998d176ffb8f2c3dfd6cb0fe62740e36dee6c64fc3928c01001bf"
dependencies = [
 "bitflags",
 "conquer-once 0.3.2",
 "font8x8",
 "num-traits",
 "spinning_top",
 "x86_64",
]
```

But why did it work before? Haven't touched the VGA code in almost a month.

**Comment by LorenzoDeMarco** [comment]
Strange for 'num-traits' to require `std` though. On crates.io and the docs it's listed as a no_std-compatible crate.

**Comment by bjorn3** [comment]
num-traits has std as default feature. If any crate depends on it without disabling the default features, it will not be no_std compatible. Vga disables it though.

Would you be fine with sharing the full project source? That probably makes it easier to find the problem.

**Comment by LorenzoDeMarco** [comment]
Update: had a look at the Cargo.toml of `test` and the compiler is right, there's no "compiler-builtins-mem", how is that even possible....? Maybe I'm using the wrong toolchain
![image](https://user-images.githubusercontent.com/33262919/133258360-7b571847-c143-403a-9f95-40115a630521.png)

**Comment by bjorn3** [comment]
Oh, you are using a nightly from 2020 instead of 2021.

**Comment by LorenzoDeMarco** [comment]
Should I use the latest nightly?

**Comment by bjorn3** [comment]
Yes, blog os is unlikely to work with such an old nightly, unless you look at an old version of blog os around the time of the rustc version you are using.

**Comment by LorenzoDeMarco** [comment]
Tried with the latest nightly:
```
$ cargo build
   Compiling compiler_builtins v0.1.49
   Compiling core v0.0.0 (/home/lorenzo/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.29
   Compiling bitflags v1.2.1
   Compiling unicode-xid v0.2.2
   Compiling x86_64 v0.14.3
   Compiling syn v1.0.76
   Compiling version_check v0.9.3
   Compiling log v0.4.14
   Compiling futures-core v0.3.15
   Compiling maybe-uninit v2.0.0
   Compiling serde v1.0.130
   Compiling futures-task v0.3.15
   Compiling bootloader v0.9.18
   Compiling crossbeam-utils v0.7.2
   Compiling num-traits v0.2.14
   Compiling futures-util v0.3.15
   Compiling ahash v0.7.4
   Compiling quote v1.0.9
   Compiling num_enum_derive v0.5.4
   Compiling derivative v2.2.0
   Compiling rustc-std-workspace-core v1.99.0 (/home/lorenzo/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/home/lorenzo/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc)
   Compiling scopeguard v1.1.0
   Compiling bit_field v0.9.0
   Compiling volatile v0.4.4
   Compiling cfg-if v1.0.0
   Compiling bit_field v0.10.1
   Compiling conquer-util v0.3.0
   Compiling cfg-if v0.1.10
   Compiling spin v0.5.2
   Compiling pin-utils v0.1.0
   Compiling conquer-util v0.2.0
   Compiling font8x8 v0.3.1
error[E0463]: can't find crate for `std`
  --> /home/lorenzo/.cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.14/src/lib.rs:21:1
   |
21 | extern crate std;
   | ^^^^^^^^^^^^^^^^^ can't find crate
   |
   = note: the `x86_64-ledom_os-5263665188370184252` target may not support the standard library
   = help: consider building the standard library from source with `cargo build -Zbuild-std`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `num-traits` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Doesn't work. I'll try uninstalling all the toolchains and cargo and reinstalling them as the blog says step by step.

**Comment by LorenzoDeMarco** [comment]
Hurray! Nuking `rustup` and `cargo` worked!
