### ISSUE TITLE
Black screen on qemu on Windows

### ISSUE THREAD

**Issue by vandadnp** [phil-opp/blog_os#1052]
Hi and thank you for the great resources, I really appreciate it

I'm at the end of this chapter: https://os.phil-opp.com/minimal-rust-kernel/

and I run the following:

```bash
PS C:\dev\rust-projects\blog_os> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s      
     Running `bootimage runner target\x86_64-blog_os\debug\blog_os`
Building bootloader
warning: use of deprecated macro `llvm_asm`: will be removed from the compiler, use asm! instead
  --> src\main.rs:45:5
   |
45 |     llvm_asm!("call $1; ${:private}.spin.${:uid}: jmp ${:private}.spin.${:uid}" ::
   |     ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated macro `llvm_asm`: will be removed from the compiler, use asm! instead
  --> src\main.rs:91:5
   |
91 |     llvm_asm!("mov bx, 0x0
   |     ^^^^^^^^

warning: `bootloader` (bin "bootloader") generated 2 warnings
    Finished release [optimized + debuginfo] target(s) in 0.05s
Running: `qemu-system-x86_64 -drive format=raw,file=target\x86_64-blog_os\debug\bootimage-blog_os.bin`
```

and qemu is initialized looking like this:
![Untitled](https://user-images.githubusercontent.com/759524/133917117-9be66c22-0424-4282-bf79-b5218d8b90ec.jpg)

my main.rs file looks like this:

```rust
#![no_std]
#![no_main]

use core::panic::PanicInfo;

static HELLO: &[u8] = b"Hello World!";

#[no_mangle]
pub extern "C" fn _start() -> ! {
    let vga_buffer = 0xb8000 as *mut u8;

    for (i, &byte) in HELLO.iter().enumerate() {
        unsafe {
            *vga_buffer.offset(i as isize * 2) = byte;
            *vga_buffer.offset(i as isize * 2 + 1) = 0xb;
        }
    }

    loop {}
}

// this is our panic handler
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop { }
}
```

here is my rustc version

```bash
PS C:\dev\rust-projects\blog_os> rustc --version --verbose
rustc 1.57.0-nightly (aa8f2d432 2021-09-18)
binary: rustc
commit-hash: aa8f2d432b23575929a48f87b8746f41ba723318
commit-date: 2021-09-18
host: x86_64-pc-windows-msvc
release: 1.57.0-nightly
LLVM version: 13.0.0
PS C:\dev\rust-projects\blog_os>
```

thank you for any help you could provide me

have a great sunday

**Comment by vandadnp** [comment]
The series of commands I'm doing is this:

```bash
cargo bootimage
cargo run
```

and this is the complete output

```bash
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\dev\rust-projects\blog_os> cargo bootimage
WARNING: `CARGO_MANIFEST_DIR` env variable not set
Building kernel
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
Building bootloader
   Compiling bootloader v0.9.19 (C:\Users\Vandad\.cargo\registry\src\github.com-1ecc6299db9ec823\bootloader-0.9.19)
warning: use of deprecated macro `llvm_asm`: will be removed from the compiler, use asm! instead
  --> src\main.rs:45:5
   |
45 |     llvm_asm!("call $1; ${:private}.spin.${:uid}: jmp ${:private}.spin.${:uid}" ::
   |     ^^^^^^^^
   |

warning: use of deprecated macro `llvm_asm`: will be removed from the compiler, use asm! instead
  --> src\main.rs:91:5
   |
91 |     llvm_asm!("mov bx, 0x0
   |     ^^^^^^^^

warning: `bootloader` (bin "bootloader") generated 2 warnings
    Finished release [optimized + debuginfo] target(s) in 1.21s
Created bootimage for `blog_os` at `C:\dev\rust-projects\blog_os\target\x86_64-blog_os\debug\bootimage-blog_os.bin`
PS C:\dev\rust-projects\blog_os> cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `bootimage runner target\x86_64-blog_os\debug\blog_os`
Building bootloader
   Compiling bootloader v0.9.19 (C:\Users\Vandad\.cargo\registry\src\github.com-1ecc6299db9ec823\bootloader-0.9.19)
warning: use of deprecated macro `llvm_asm`: will be removed from the compiler, use asm! instead
  --> src\main.rs:45:5
   |
45 |     llvm_asm!("call $1; ${:private}.spin.${:uid}: jmp ${:private}.spin.${:uid}" ::
   |     ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated macro `llvm_asm`: will be removed from the compiler, use asm! instead
  --> src\main.rs:91:5
   |
91 |     llvm_asm!("mov bx, 0x0
   |     ^^^^^^^^

warning: `bootloader` (bin "bootloader") generated 2 warnings
    Finished release [optimized + debuginfo] target(s) in 1.20s
Running: `qemu-system-x86_64 -drive format=raw,file=target\x86_64-blog_os\debug\bootimage-blog_os.bin`
```

**Comment by vandadnp** [comment]
I'll attach the whole project folder as a zip file here for reference
I've removed the "target" folder for obvious reasons from the zipped file since it's way too big

[os.zip](https://github.com/phil-opp/blog_os/files/7191075/os.zip)

**Comment by vandadnp** [comment]
@bjorn3 I'd really appreciate your help on this please if you have the time. Thank you in advance and thank you again for the great resource that you're providing here.

**Comment by bjorn3** [comment]
> @bjorn3 I'd really appreciate your help on this please if you have the time.

I tried to run the provided code. It worked fine for me. Maybe try `cargo run -- -d cpu_reset -d guest_errors` to show if there are any exceptions?

```
$ rustc -vV
rustc 1.57.0-nightly (5ecc8ad84 2021-09-19)
binary: rustc
commit-hash: 5ecc8ad8462574354a55162a0c16b10eb95e3e70
commit-date: 2021-09-19
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

> and thank you again for the great resource that you're providing here.

Actually @phil-opp is the author of this blog series. I just try to provide support when others get stuck.

**Comment by vandadnp** [comment]
thank you for your help @bjorn3

I tried what you mentioned and this is my output

![Untitled](https://user-images.githubusercontent.com/759524/134217172-76b51263-a8e8-49c3-ac61-eb24e3e26233.png)

**Comment by vandadnp** [comment]
@phil-opp thank you for your reply. To be honest I got tired of my Windows system so I went through the first 2 posts of your blog on macOS and got it to work without a problem:
<img width="1792" alt="Screenshot 2021-09-22 at 08 48 57 (2)" src="https://user-images.githubusercontent.com/759524/134296057-56e7d0cd-5116-4a0f-b9e0-1114d1f3d694.png">

Is it OK if I keep this issue open until I've tried your solution on Windows? You're more than welcome to close this issue if you want to since it seems to be platform specific.

**Comment by vandadnp** [comment]
About the QEMU version on Windows, I am using this version:

```bash
PS C:\dev\rust-projects\blog_os> qemu-system-x86_64 --version                                                               
QEMU emulator version 6.0.93 (v6.1.0-rc3-11879-ge232c1bc00-dirty)      
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```

and I'm now going to update to the latest version to see how that changes things. here is the version that I just updated to:

```bash
QEMU emulator version 6.1.0 (v6.1.0-11882-g7deea770bf-dirty)
```
and here are the results (it works!)

![itworks](https://user-images.githubusercontent.com/759524/134379503-169a70f8-d704-43ca-b360-673c276083e8.png)

Thank you for all the help @phil-opp and @bjorn3, so it's as you said @phil-opp , it's a QEMU bug in version 6.0.0

**Comment by vandadnp** [comment]
I'm closing this issue since this seems to be a QEMU bug and nothing to do with this OS's code. Thank you again for all the help and support
