### ISSUE TITLE
Failing to create a bootimage inside container w/ ubuntu 20.04.3 LTS: instruction requires: Not 64-bit mode

### ISSUE THREAD

**Issue by kristoiv** [phil-opp/blog_os#1076]
Great series so far! Trying to build not working with my setup though, wanted to build inside docker to void having to clutter my main system (with qemu etc.).

Host system:
```
Macbook Air (M1, 2020)
macOs Big Sur
```

Docker container, build host system:
```
root@c9bdd59d07e1:/work# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

root@c9bdd59d07e1:/work# history | grep apt-get
   12  apt-get update && apt-get dist-upgrade -y
   13  apt-get install vim
   14  apt-get install qemu-system
   15  apt-get install curl
   26  apt-get install git-core
   62  apt-get install -y build-essential

root@c9bdd59d07e1:/work# history | grep rustup
   16  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  104  rustup override set nightly-2021-12-13
  106  rustup component add rust-src --toolchain nightly-2021-12-13-aarch64-unknown-linux-gnu
  109  rustup component add llvm-tools-preview

root@c9bdd59d07e1:/work# history | grep "cargo insta"
   76  cargo install bootimage

root@c9bdd59d07e1:/work# cargo bootimage --version
bootimage 0.10.3

root@c9bdd59d07e1:/work# rustc --version
rustc 1.59.0-nightly (6bda5b331 2021-12-12)
```

Bootloader version locked:
```
[[package]]
name = "bootloader"
version = "0.9.21"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a62c8f6168cd106687ee36a2b71a46c4144d73399f72814104d33094b8092fd2"
```

Failure to create bootimage output:
```
root@c9bdd59d07e1:/work# cargo bootimage
Building kernel
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Building bootloader
   Compiling bootloader v0.9.21 (/root/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.9.21)
error: instruction requires: Not 64-bit mode
    push ds
    ^
error: instruction requires: Not 64-bit mode
    push es
    ^
error: instruction requires: Not 64-bit mode
    lgdt [gdt32info]
    ^
error: instruction requires: Not 64-bit mode
    mov eax, cr0
    ^


(...)


error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:42:5
   |
42 |     push ds
   |     ^

error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:43:5
   |
43 |     push es
   |     ^

error: instruction requires: Not 64-bit mode
   |
note: instantiated into assembly here
  --> <inline asm>:45:5
   |
45 |     lgdt [gdt32info]
   |     ^


(...)


error: could not compile `bootloader` due to 48 previous errors
Error: Bootloader build failed.
Stderr: 
```

**Comment by kristoiv** [comment]
Can confirm I get the same result if I clone your source code and checkout branch post-02

**Comment by kristoiv** [comment]
Interesting enough if I set up the exact same toolchain on my macOs directly (not containerized) it compiles without problems. So something with my docker container setup.

**Comment by kristoiv** [comment]
I transitioned to the supported use of macOs directly. Closing this one.

**Comment by kennystrawnmusic** [comment]
It's doing that because the host architecture is ARM (Apple Silicon), not x86_64. I've had the same problem with my M1-2020 MBP myself which is why I use my mining rig for OS dev.

**Comment by kristoiv** [comment]
@kennystrawnmusic When I installed the same toolchain (darwin instead of linux though) on my M1 MBA as the one I installed in the container it does actually work! I just have to do it directly on osx, not inside a container. So you might not have to use your minig rig anymore!

**Comment by phil-opp** [comment]
Are you sure that you're compiling for the right target? Try running `cargo bootimage --target x86_64-blog_os.json`. You can also [set the target as default](https://os.phil-opp.com/minimal-rust-kernel/#set-a-default-target), but this only works if you're invoking the `cargo bootimage` command from the directory where the `.cargo/config.toml` lives (or a subdirectory).

**Comment by kristoiv** [comment]
I followed the blog in detail. But non the less tried specifying too (see middle of code block). Same result.

```
root@46482403cbb6:/work# cat .cargo/config.toml 
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
root@46482403cbb6:/work# cargo bootimage
WARNING: `CARGO_MANIFEST_DIR` env variable not set
Building kernel
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
Building bootloader
   Compiling bootloader v0.9.21 (/root/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.9.21)
warning: the feature `asm` has been stable since 1.59.0 and no longer requires an attribute to enable
 --> src/main.rs:3:12
  |
3 | #![feature(asm)]
  |            ^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: the feature `global_asm` has been stable since 1.59.0 and no longer requires an attribute to enable
 --> src/main.rs:2:12
  |
2 | #![feature(global_asm)]
  |            ^^^^^^^^^^

error: instruction requires: Not 64-bit mode
    push ds
    ^
error: instruction requires: Not 64-bit mode
    push es


(...)


warning: `bootloader` (bin "bootloader") generated 2 warnings
error: could not compile `bootloader` due to 48 previous errors; 2 warnings emitted
Error: Bootloader build failed.
Stderr: 


root@46482403cbb6:/work# cargo bootimage --target x86_64-blog_os.json 
WARNING: `CARGO_MANIFEST_DIR` env variable not set
Building kernel
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
Building bootloader
   Compiling bootloader v0.9.21 (/root/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.9.21)
warning: the feature `asm` has been stable since 1.59.0 and no longer requires an attribute to enable
 --> src/main.rs:3:12
  |
3 | #![feature(asm)]
  |            ^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: the feature `global_asm` has been stable since 1.59.0 and no longer requires an attribute to enable
 --> src/main.rs:2:12
  |
2 | #![feature(global_asm)]
  |            ^^^^^^^^^^

error: instruction requires: Not 64-bit mode
    push ds
    ^
error: instruction requires: Not 64-bit mode
    push es
    ^


(...)
```

**Comment by AribYadi** [comment]
Hey, i have the exact same issue, as this issue is closed i presumed that you found a fix for this, would you be able to tell me what the fix is?

**Comment by kristoiv** [comment]
@AribYadi Honestly I just relented and used MacOS directly (no Docker). That worked for me. Didn't really need to clutter my system much.

**Comment by ymanyamn** [comment]
> Great series so far! Trying to build not working with my setup though, wanted to build inside docker to void having to clutter my main system (with qemu etc.).
> 
> Host system:
> ```
> Macbook Air (M1, 2020)
> macOs Big Sur
> ```
> 
> Docker container, build host system:
> ```
> root@c9bdd59d07e1:/work# cat /etc/lsb-release 
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=20.04
> DISTRIB_CODENAME=focal
> DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
> 
> root@c9bdd59d07e1:/work# history | grep apt-get
>    12  apt-get update && apt-get dist-upgrade -y
>    13  apt-get install vim
>    14  apt-get install qemu-system
>    15  apt-get install curl
>    26  apt-get install git-core
>    62  apt-get install -y build-essential
> 
> root@c9bdd59d07e1:/work# history | grep rustup
>    16  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
>   104  rustup override set nightly-2021-12-13
>   106  rustup component add rust-src --toolchain nightly-2021-12-13-aarch64-unknown-linux-gnu
>   109  rustup component add llvm-tools-preview
> 
> root@c9bdd59d07e1:/work# history | grep "cargo insta"
>    76  cargo install bootimage
> 
> root@c9bdd59d07e1:/work# cargo bootimage --version
> bootimage 0.10.3
> 
> root@c9bdd59d07e1:/work# rustc --version
> rustc 1.59.0-nightly (6bda5b331 2021-12-12)
> ```
> 
> Bootloader version locked:
> ```
> [[package]]
> name = "bootloader"
> version = "0.9.21"
> source = "registry+https://github.com/rust-lang/crates.io-index"
> checksum = "a62c8f6168cd106687ee36a2b71a46c4144d73399f72814104d33094b8092fd2"
> ```
> 
> Failure to create bootimage output:
> ```
> root@c9bdd59d07e1:/work# cargo bootimage
> Building kernel
>     Finished dev [unoptimized + debuginfo] target(s) in 0.09s
> Building bootloader
>    Compiling bootloader v0.9.21 (/root/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.9.21)
> error: instruction requires: Not 64-bit mode
>     push ds
>     ^
> error: instruction requires: Not 64-bit mode
>     push es
>     ^
> error: instruction requires: Not 64-bit mode
>     lgdt [gdt32info]
>     ^
> error: instruction requires: Not 64-bit mode
>     mov eax, cr0
>     ^
> 
> 
> (...)
> 
> 
> error: instruction requires: Not 64-bit mode
>    |
> note: instantiated into assembly here
>   --> <inline asm>:42:5
>    |
> 42 |     push ds
>    |     ^
> 
> error: instruction requires: Not 64-bit mode
>    |
> note: instantiated into assembly here
>   --> <inline asm>:43:5
>    |
> 43 |     push es
>    |     ^
> 
> error: instruction requires: Not 64-bit mode
>    |
> note: instantiated into assembly here
>   --> <inline asm>:45:5
>    |
> 45 |     lgdt [gdt32info]
>    |     ^
> 
> 
> (...)
> 
> 
> error: could not compile `bootloader` due to 48 previous errors
> Error: Bootloader build failed.
> Stderr: 
> ```
>[target.'cfg(target_os = "none")'] >runner = "bootimage runner"
