### ISSUE TITLE
Steps to divide the address space in kernel space and user space

### ISSUE THREAD

**Issue by sauravdeshpande** [phil-opp/blog_os#1081]
Great blog, I have followed all the articles so far from the blog os post, I was thinking about how to divide the address spaces.
What modifications are needed to divide the virtual memory into kernel space and user space and how context switch can be done.

Thank you

**Comment by nullium21** [comment]
Here's an article about how to get to usermode (a.k.a Ring 3 on x86): https://wiki.osdev.org/Getting_to_Ring_3
> * Add two new GDT entries (at least) configured for ring 3.
> * Set up a barebones [TSS](https://wiki.osdev.org/TSS) with an ESP0 stack.
> * Set up an [IDT](https://wiki.osdev.org/IDT) entry for ring 3 system call interrupts (optional).

**Comment by phil-opp** [comment]
For moving the kernel to the higher half, it should be enough to instruct the linker to use a different base address. You can do this through a linker script or by [passing an `--image-base` argument](https://github.com/rust-osdev/bootloader/blob/66637c11f5d459cfb4aa5d4f9538e70f012aa442/tests/test_kernels/higher_half/x86_64-higher_half.json#L15-L17).
