### ISSUE TITLE
Bootloader logs warning on each Cargo command

### ISSUE THREAD

**Issue by peterkhayes** [phil-opp/blog_os#1084]
Hello! I'm loving this tutorial - thank you so much for writing it!

I noticed that any time I run a cargo command (e.g. build, run, or test), I get the following error:

```
Building bootloader
   Compiling bootloader v0.9.21 (/Users/phayes/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.9.21)
warning: the feature `asm` has been stable since 1.59.0 and no longer requires an attribute to enable
 --> src/main.rs:3:12
  |
3 | #![feature(asm)]
  |            ^^^
  |
  = note: `#[warn(stable_features)]` on by default

warning: the feature `global_asm` has been stable since 1.59.0 and no longer requires an attribute to enable
 --> src/main.rs:2:12
  |
2 | #![feature(global_asm)]
  |            ^^^^^^^^^^

warning: `bootloader` (bin "bootloader") generated 2 warnings
```

This doesn't block progress in the tutorial, but it's visually noisy.

I tried updating bootloader to `0.10.12`, but this lead to another error:

```
Error: An error occured while trying to build the bootloader: The `bootloader` dependency has not the right format: No `package.metadata.bootloader.target` key found in Cargo.toml of bootloader

(If you're using the official bootloader crate, you need at least version 0.5.1)

Caused by:
    The `bootloader` dependency has not the right format: No `package.metadata.bootloader.target` key found in Cargo.toml of bootloader

    (If you're using the official bootloader crate, you need at least version 0.5.1)
```

I made various attempts at correcting `Cargo.toml` to make that go away, but was not successful.

Any advice?

**Comment by peterkhayes** [comment]
Ok, makes sense. And just confirming, there's no way to configure Cargo to mute this warning? For example, is there a flag that tells the compiler to ignore certain errors on a project-wide basis? I tried looking up some documentation around linting settings but couldn't get it to work.

**Comment by bjorn3** [comment]
This is not a lint, so it can't be suppressed. If it was a lint rustc would already tell you the lint name. Cargo already suppresses lints for dependencies.

**Comment by phil-opp** [comment]
> Hello! I'm loving this tutorial - thank you so much for writing it!

Great to hear that :).



> Fixing the warning will require changing bootloader to no longer enable the asm and global_asm feature gates in their `lib.rs`.

Should be fixed by https://github.com/rust-osdev/bootloader/pull/227. After it's released, you should be able to silence the warning by updating to the latest v0.9 release by running `cargo update -p bootloader`.
