### ISSUE TITLE
Inline assembly is now stable

### ISSUE THREAD

**Issue by dscottboggs** [phil-opp/blog_os#1086]
I just found this blog, and noticed at the part where you install nightly, you do so because inline assembly ~~is~~ _was_ nightly-only. It was merged into stable in the [1.59.0 release](https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html#inline-assembly). Does this still require nightly?

**Comment by bjorn3** [comment]
The bootloader crate is not yet updated to not use the feature gate, so it still requires nightly. (https://github.com/phil-opp/blog_os/issues/1084) In addition blog os itself uses several other nightly only features: https://github.com/phil-opp/blog_os/blob/f1dec65abbeca7ff921563626e38ab0f4547f349/src/lib.rs#L3-L6

* custom_test_frameworks: necessary for testing
* abi_x86_interrupt: this is how interrupt handlers are currently implemented. it would be possible to rewrite using `global_asm!`. see also https://internals.rust-lang.org/t/pre-rfc-interrupt-calling-conventions/16182/12
* alloc_error_handler: this is necessary for using liballoc without libstd.
* const_mut_refs: used by the memory allocator. see https://os.phil-opp.com/allocator-designs/#implementation-1

And finally it uses a custom target specification. It may be possible to migrate to x86_64-unknown-none.

**Comment by phil-opp** [comment]
This is answered.
