### ISSUE TITLE
General protection fault when PIC is reprogrammed

### ISSUE THREAD

**Issue by BomBardyGamer** [phil-opp/blog_os#1087]
Currently working on an operating system using the tutorial for the blog, and I'm doing lesson 7, where we setup the PIC and reprogram it with a hardware timer handler, but every time I enable interrupts, it prints 1 dot and then spams me with general protection faults with error code 16. I don't have a console log unfortunately, but I do have the source code, which is right here: https://github.com/HalogenPowered/os
Specifically, the interrupt folder contains the interrupt code.

I don't understand why this happens, and I've tried looking up to see why this occurs. I've looked on wikipedia at the GPF, I've looked on the OSDev wiki, and I've looked on StackOverflow, and found nothing.

Not sure if this is even the right place to ask questions. Usually I look for something like a Discord server or another similar service, but I couldn't find anything like that.

**Comment by kennystrawnmusic** [comment]
Per comments on that post I’ve encountered the exact same problem. Not sure why at all.

**Comment by BomBardyGamer** [comment]
I wonder what can be done then. Do you know of any temporary workarounds to fix this problem whilst we wait for it to be sorted in whatever crate is causing it? Or are we screwed?

**Comment by phil-opp** [comment]
A general protection fault with an error code != 0 means that there is something wrong with a segment, e.g. in the GDT. See https://wiki.osdev.org/Exceptions#Selector_Error_Code for more details on the structure of that error code. Assuming that you mean error code `0x16` (hex not decimal), it means that your second GDT entry is faulty. 

As you're using version 0.10 of the `bootloader` crate, it sounds to me like you're hitting https://github.com/rust-osdev/bootloader/issues/196. To fix this, you need to reload the `ss` segment register (and for consistency also the `ds` and `es` registers). You can either set up a kernel data desriptor in the GDT and load that, or just load 0 (this [won't work with syscalls](https://github.com/rust-osdev/x86_64/issues/160) though).

The reason that this is not required with v0.9 is that it already loads the registers with 0. In v0.10, we changed this to allow people to use the provided GDT together with syscalls.

**Comment by phil-opp** [comment]
I think this is answered.
