### ISSUE TITLE
Nasm warning on checksum calculation on Mac OS

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#11]
```nasm
dd 0x100000000 - (0xe85250d6 + 0 + (header_end - header_start))
```
produces the warning: 

```bash
multiboot_header.asm:7: warning: numeric constant 0x100000000 does not fit in 32 bits
```

The following version compiles without warnings (but causes a warning on Linux):

```nasm
dd - (0xe85250d6 + 0 + (header_end - header_start))
```

See [comment from Georgiy Slobodenyuk](http://blog.phil-opp.com/rust-os/multiboot-kernel.html#comment-2327365502).

**Comment by jcaudle** [comment]
It seems worth noting that installing a newer `nasm` than the system provided one will allow the same code to work without warning on both Mac OS X as the code provided for Linux. Also, the version without `0x100000000` produces the warning mentioned in the original post.

**Comment by phil-opp** [comment]
Ok, then I will close it for now. But I added an issue for [a `Get started on Mac OS` page](https://github.com/phil-opp/blog_os/issues/55). 

If you got it working on Mac OS, I would really appreciate a quick summary of the needed steps in the linked issue!

**Comment by phil-opp** [comment]
Thanks for your comment!
