### ISSUE TITLE
Use official bitflags with no_std feature instead of own fork

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#110]
~~@cmr created a [bitflags-core](https://crates.io/crates/bitflags-core/) fork, so we should switch to it.~~

_Update_: It seems like the official bitflags crate has a no_std feature now. See rust-lang-nursery/bitflags#29.

**Comment by cmr** [comment]
Note that upstream now has a no_std feature, I saw the pr but didn't evaluate it yet

On January 12, 2016 4:19:35 PM EST, Philipp Oppermann <notifications@github.com> wrote:
>@cmr created a [bitflags-core](https://crates.io/crates/bitflags-core/)
>fork, so we should switch to it.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/phil-opp/blog_os/issues/110

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by phil-opp** [comment]
Awesome! Thanks for the info.
