### ISSUE TITLE
Hardware Interrupts tutorial not working

### ISSUE THREAD

**Issue by MTRNord** [phil-opp/blog_os#1104]
Hi I started to implement Hardware Interrupts as described. But neither the timer nor the keyboard handlers get called. I am using uefi by using the newer bootloader crate. Otherwise my kernel follows the tutorial. Any ideas what may be happening or how to debug this?

**Comment by MTRNord** [comment]
(Code can be seen at https://gitlab.nordgedanken.dev/toy-kernel/toy-kernel/-/commit/37cc6e38c769c73bcce5d41ae40ea554d36e144a )

**Comment by bjorn3** [comment]
AFAIK you can't use the 8259 PIC with UEFI. You need to use the APIC instead if you want UEFI support.

**Comment by phil-opp** [comment]
This is answered, so I'll close it. I'm still working on the upcoming third edition of the blog, which will feature UEFI booting and use the APIC instead of the legacy PIC for interrupt handling.
