### ISSUE TITLE
How can I get involved in translation work

### ISSUE THREAD

**Issue by lubingyucn** [phil-opp/blog_os#1124]
How can I get involved in translation work？I want to translation these in chinese,but only four completed

**Comment by phil-opp** [comment]
There is no formal process for adding a translator. You can just create a new translation and open a pull request, then we look for someone else that also speaks the language for a review. To avoid duplicated work, it's a good idea to open a draft PR very early to show other people what you're working on.

For Chinese translations, we also have a tracking issue at https://github.com/phil-opp/blog_os/issues/961. It's probably a good idea to leave a comment there when you start working on a new translation.

**Comment by phil-opp** [comment]
Another way to help is to review translation PRs by other people. For Chinese, there is currently #1131 waiting for a review.

**Comment by phil-opp** [comment]
Closing as this is answered
