### ISSUE TITLE
instant crash after VGA Text Mode tutorial

### ISSUE THREAD

**Issue by Skyslycer** [phil-opp/blog_os#1128]
Hi people, so I followed the VGA Text Mode tutorial up until where we print `Hello Wörld!`. I tried it and it instantly crashed.
It printed the yellow text providing information and after that, it should display the `Hello Wörld!`. But it didn't.

So I came here and copied the source for the `vga_buffers` and tried again. Instant crash and no compilation errors.
And no I haven't forgotten a `loop {}`.

Main: https://paste.skyslycer.de/hjgPO

Thanks in advance!

**Comment by phil-opp** [comment]
Did you find a solution to your problem?

**Comment by Skyslycer** [comment]
> Did you find a solution to your problem?

No, I just found out that your solution didn't work with the new bootloader crate. Have to find something working there.

**Comment by phil-opp** [comment]
For the blog, I recommend sticking to `bootloader v0.9` for now.
