### ISSUE TITLE
adding code of conduct file

### ISSUE THREAD

**Issue by anamikarawat** [phil-opp/blog_os#1143]
I want to create a code_of_conduct.md file . please assign me this issue under hacktoberfest 2022.

**Comment by Vishnu-VPK** [comment]
I want to add code of conduct file, please sign me.

**Comment by phil-opp** [comment]
As already mentioned on the blog, we follow [Rust's code of conduct](https://www.rust-lang.org/policies/code-of-conduct). So we don't need our own file.

Also, please don't spam projects with random changes just for hacktoberfest.
