### ISSUE TITLE
Minimal Rust Kernal - Hello World Just Flashes 

### ISSUE THREAD

**Issue by pratushrai0309** [phil-opp/blog_os#1153]
In kali linux Hello World Just flashes when qemu loads

**Comment by bjorn3** [comment]
A couple of options:

* qemu 6.0 has a bug that causes issues for blog os in some cases. Make sure you are not using this version. (not sure if this bug applies to linux)
* Try passing `-d cpu_reset -d guest_errors` to qemu to see if there is a triple fault or something like that.

**Comment by pratushrai0309** [comment]
It didn't work for me 
and also qemu version is 7.1.0

**Comment by phil-opp** [comment]
Have you tried checking out the [`post-02`](https://github.com/phil-opp/blog_os/tree/post-02) branch of this repo? Maybe you have some typo in your code.

**Comment by pratushrai0309** [comment]
Thanks it worked for me!
