### ISSUE TITLE
Container should be main tag it specifies the main content of a document

### ISSUE THREAD

**Issue by rohanagroya** [phil-opp/blog_os#1155]

**Comment by rohanagroya** [comment]
please assign me this

**Comment by dynamicashuu** [comment]
please assign  me this one

**Comment by phil-opp** [comment]
We're already using the `<main>` tag: https://github.com/phil-opp/blog_os/blob/341e05b84396695926212e1668324c3dd8163b62/blog/templates/edition-2/base.html#L51
