### ISSUE TITLE
error: linking with `cc` failed: exit status: 1

### ISSUE THREAD

**Issue by DuyKhangTruong** [phil-opp/blog_os#1157]
Hi everyone I was doing the first steps of the blog, I was at the step adding panic = "abort" to cargo.toml and I got this error with cargo build

`error: linking with `cc` failed: exit status: 1
 = note: ld: entry point (_main) undefined. for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by tsatke** [comment]
What is the linker error?
Do you have a function `_main`?
Do you maybe have to take more steps in the tutorial to get to a working state?

**Comment by DuyKhangTruong** [comment]
Hi I fixed the link cc error by doing this step in the blogs `cargo rustc -- -C link-arg=-nostartfiles`
