### ISSUE TITLE
What is a frame?

### ISSUE THREAD

**Issue by Ketsuban** [phil-opp/blog_os#116]
Your blog series is normally easy to follow, but I got a bit lost when I started reading "Frame Allocation" because you leapt straight in without saying what a frame is. Could you dedicate a paragraph or two to this so the reader knows where they're standing?

**Comment by phil-opp** [comment]
Thanks a lot for reporting this! There should really be some kind of introduction/explanation in the post. 


When using paging, the memory is split into equally sized chunks (normally 4096 bytes) Such a chunk is called "physical page" or "frame". I use "frame" to disambiguatiate it from _virtual_ pages.

**Comment by Ketsuban** [comment]
Ahh, okay. Thank you very much.
