### ISSUE TITLE
error: linking with `rust-lld` failed: exit status: 1

### ISSUE THREAD

**Issue by netherous** [phil-opp/blog_os#1161]
Hi, I am currently in chapter 2 of the blog. Build and install bootimage are both successful, but when I ran "cargo bootimage" these warnings and errors appear. WARNING: `CARGO_MANIFEST_DIR` env variable not set .  

error: linking with `rust-lld` failed: exit status: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "/tmp/rustcToqTyx/symbols.o"

          rust-lld: error: undefined symbol: __bootloader_start
          >>> referenced by main.rs:112 (src/main.rs:112)
          >>>               /home/george/code/personal/personal_os/blog_os/target/bootimage/bootloader/x86_64-bootloader/release/deps/bootloader-b4a8a4a109acd4d8.bootloader.26c362f9-cgu.1.rcgu.o:(stage_4)
          >>> referenced by main.rs:105 (src/main.rs:105)
          >>>               /home/george/code/personal/personal_os/blog_os/target/bootimage/bootloader/x86_64-bootloader/release/deps/bootloader-b4a8a4a109acd4d8.bootloader.26c362f9-cgu.1.rcgu.o:(stage_4)
          

error: could not compile `bootloader` due to previous error
Error: Bootloader build failed.
Stderr:

**Comment by netherous** [comment]
https://github.com/hawkw/mycelium/pull/335

**Comment by phil-opp** [comment]
This should be fixed with the latest nightly.
