### ISSUE TITLE
the option `Z` is only accepted on the nightly compiler

### ISSUE THREAD

**Issue by Degra02** [phil-opp/blog_os#1168]
Hello everyone, I really don't understand why this thing is happening, currently on 6.0.3-arch1-1-surface.
Whenever I try to compile, it just doesn't recognize the nightly build, even if I have a rust-toolchian.toml set to nightly, overridden the toolchain to nightly and passing the +nightly subcommand to cargo.
This is the error I'm getting:
`
Compiling compiler_builtins v0.1.73
   Compiling core v0.0.0 (/usr/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/usr/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling degros v0.1.0 (/home/degra/Coding/Rust/degros)
error: the option `Z` is only accepted on the nightly compiler
`

If I try to pass the `-Z build-std` option, I get the following 3 errors:
`error: `sys_common::condvar::Condvar::new` is not yet stable as a const fn
   --> /usr/lib/rustlib/src/rust/library/std/src/sync/condvar.rs:129:26
    |
129 |         Condvar { inner: sys::Condvar::new() }
    |                          ^^^^^^^^^^^^^^^^^^^
    |
    = help: const-stable functions can only call other const-stable functions

error: `sys_common::mutex::MovableMutex::new` is not yet stable as a const fn
   --> /usr/lib/rustlib/src/rust/library/std/src/sync/mutex.rs:220:20
    |
220 |             inner: sys::MovableMutex::new(),
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: const-stable functions can only call other const-stable functions

error: `sys_common::rwlock::MovableRwLock::new` is not yet stable as a const fn
   --> /usr/lib/rustlib/src/rust/library/std/src/sync/rwlock.rs:159:20
    |
159 |             inner: sys::MovableRwLock::new(),
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: const-stable functions can only call other const-stable functions`

Anyone got any clue?

**Comment by bjorn3** [comment]
> If I try to pass the -Z build-std option, I get the following 3 errors:

Try updating your nightly. There was a bug in rust a while ago causing those 3 errors.

**Comment by Degra02** [comment]
Still getting the same error, even with updated rustup. 
Also tried using the x86_64-unknown-none target mentioned in another issue but still nothing

**Comment by tsatke** [comment]
Did you update `rustup` or did you update your nightly (`rustup update nightly`)?
Can you post the output of `rustup show`?

**Comment by Degra02** [comment]
Fixed the errors by reinstalling rust through the "rustup method".
