### ISSUE TITLE
Update cross-compile-libcore page to use nightly-libcore

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#117]

**Comment by cardoe** [comment]
You might want to have a look at https://github.com/japaric/cargo-sysroot as well.

**Comment by phil-opp** [comment]
Thanks! His https://github.com/japaric/xargo looks even cooler. The only problem is compiling without float support (which we'll need as soon as we handle interrupts). I hope that rust-lang/rfcs#1364 makes some process soon.

**Comment by phil-opp** [comment]
Fixed in #221
