### ISSUE TITLE
cargo install bootimage does not work unless config.toml deleted

### ISSUE THREAD

**Issue by bentotten** [phil-opp/blog_os#1194]
Unfortunately when attempting to install bootimage with `cargo bootimage`, it fails with several errors. After some initial scouting online, I retried this from the stable version and from the parent directory, but no luck. After deleting my config.toml, it installed correctly. 

Sample error messages:
error[E0425]: cannot find function, tuple struct or tuple variant `Some` in this scope
error[E0425]: cannot find function, tuple struct or tuple variant `Err` in this scope
error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope

[Ubuntu 22.04.1 LTS running in a VirtualBox VM]

**Comment by phil-opp** [comment]
This is unfornuately a known problem in cargo. It should normally ignore `.cargo/config.toml` keys for `cargo install`, but apparently it doesn't do that for some `build-std` keys. The current workaround is to run the `cargo install` command from a parent directory, e.g. your home directory.

See also #853 .

**Comment by bentotten** [comment]
Unfortunately it also did not work from the parent directory; a quick removal of the config.toml did the trick though

**Comment by johnvan08** [comment]
but  how work  on windows？

**Comment by phil-opp** [comment]
@johnvan08 If you're encountering issues on Windows, please oen a new issue to discuss this.
