### ISSUE TITLE
From the Minimal Kernel Setup

### ISSUE THREAD

**Issue by SajeevanJSPY** [phil-opp/blog_os#1195]
I did what in the page, but I got too many errors like this
I am here on the page https://os.phil-opp.com/minimal-rust-kernel/#building-our-kernel
I got all of the errors after I created ./cargo/config.toml
My Machine Specs => x86_64 windows

![error](https://user-images.githubusercontent.com/108508613/222367121-b8669313-0f50-4320-bb2e-a03f48a9ce87.png)

**Comment by bjorn3** [comment]
What are the first couple of errors?

**Comment by SajeevanJSPY** [comment]
![err](https://user-images.githubusercontent.com/108508613/222374098-85475e48-e193-4e47-964e-b09d036534ab.png)

I got too many of them like this

**Comment by SajeevanJSPY** [comment]
![first](https://user-images.githubusercontent.com/108508613/222382180-eb86eaf5-8b64-46ae-84bb-a744f0cacfed.png)

**Comment by bjorn3** [comment]
That is not an helpful error at all... Maybe you could try `cargo clean` and building again? Maybe some cache got messed up. If that doesn't help you could try opening an upstream rust bug with the exact project you used and the exact rustc version (as shown by `rustc -vV`).

**Comment by SajeevanJSPY** [comment]
Thank You For Your Time @bjorn3, I updated my rust packages using `rustup update`, and now working fine
