### ISSUE TITLE
build-std broken as of nightly 74c482104 (2023-05-04)

### ISSUE THREAD

**Issue by krstn42** [phil-opp/blog_os#1220]
rust-lang/rust#108865 added a "sysroot" dummy crate, which seems to have broken `build-std`, cf. rust-lang/rust#111225.

```
% cargo build
error: Package `test v0.0.0 ([…]/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test)` does not have the feature `compiler-builtins-mem`
```

Mainly opening this issue in case anyone else happens to stumble upon it and thinks they are doing something wrong :-) I'm not completely sure if any changes may be necessary here or if this will be fixed in Rust/Cargo.

Switching to an older nightly version seems to be the best workaround for now.
```
rustup install nightly-2023-05-03
rustup override set nightly-2023-05-03
```

**Comment by weihanglo** [comment]
This should now be fixed in the latest nightly (2023-05-05).

**Comment by kingdevnl** [comment]
For me it's complaining about 
`error: Package `test v0.0.0 (/home/jasper/.rustup/toolchains/nightly-2023-05-05-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test)` does not have the feature `backtrace``

**Comment by weihanglo** [comment]
Would branch were you in? Could you provide a `cargo -vV` output here? Thank you.

**Comment by kingdevnl** [comment]
Updating to nightly-05-06 worked
