### ISSUE TITLE
post-04 - Conditional compilation does not seem to work

### ISSUE THREAD

**Issue by AlexandreMarcq** [phil-opp/blog_os#1229]
Hello,

I'm following along the *Testing* part of the blog.
Unfortunately, `cargo run` and `cargo test` yield the same result in QEMU.

I have added a `#[cfg(test)]` before a `println!` and it does not appear on the screen.

Here is the code I have : 

```rust
#![no_std]
#![no_main]
#![feature(custom_test_frameworks)]
#![test_runner(crate::test_runner)]
#![reexport_test_harness_main = "test_main"]

use core::panic::PanicInfo;

mod vga_buffer;

#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    println!("{}", info);
    loop {}
}

#[no_mangle]
pub extern "C" fn _start() -> ! {
    #[cfg(test)]
    println!("Hello world{}", "!");

    #[cfg(test)]
    test_main();

    loop {}
}

#[cfg(test)]
fn test_runner(tests: &[&dyn Fn()]) {
    println!("Running {} tests", tests.len());
}
```

And here is the output : 
![image](https://github.com/phil-opp/blog_os/assets/50714185/d14218c3-d2c1-4724-a87c-6a032f793c84)

Is there something I'm missing ?

**Comment by phil-opp** [comment]
I don't see any issues with your code. Do you have your full code online somewhere so that I can take a look?

Could you try cloning the `post-04` branch of this repo? When I put the code you posted above into the `src/main.rs` I get different output for `cargo test --bin blog_os` and `cargo run`:


- `cargo test --bin blog_os`
  ![image](https://github.com/phil-opp/blog_os/assets/1131315/1e132af3-a252-4e45-990a-f5104a2c5342)
- No output for `cargo run`

**Comment by AlexandreMarcq** [comment]
I've uploaded my code in [my repo](https://github.com/AlexandreMarcq/rust-os).
I tried with the `post-04` branch. I got the expected output with `cargo run` but `cargo test` seems to hang : 
![image](https://github.com/phil-opp/blog_os/assets/50714185/c631577e-4804-4b76-be52-e6e20b722655)

**Comment by michihupf** [comment]
Is help still needed here? @AlexandreMarcq I'd be happy to assist, unfortunately it seems the repository is private or deleted. Either way I can't access it to take a look. 

From what I can see everything seems fine. Your `println!` probably only prints to the VGA buffer not to your hosts `stdio`. I can see you have the serial interface mapped to stdio so you could print to there to see output in your terminal. 

If you want to see the output in qemu then you need to remove `"-display", "none"` from `test-args` in your `Cargo.toml` in the section `package.metadata.bootimage` to make the qemu window show.
