### ISSUE TITLE
cargo bootimage failing 

### ISSUE THREAD

**Issue by KilroyWasHere-cs-j** [phil-opp/blog_os#1241]
Running "cargo bootimage" yields this error : "error: could not compile `serde` (lib) due to 5097 previous errors"

rustc version -- rustc 1.74.0-nightly (c469197b1 2023-08-22)
bootimage = "0.10.3"

**Comment by AtomicGamer9523** [comment]
You seem to be using rust edition `2018`, change it to `2021` and try again

**Comment by nskobelevs** [comment]
Could be related to #1236
Using bootimage version 0.9 fixed the massive errors I was getting (with 2021 edition)

**Comment by phil-opp** [comment]
Yeah, the second edition of the blog only works with `bootloader v0.9`.
