### ISSUE TITLE
Table of Content

### ISSUE THREAD

**Issue by Durgesh4993** [phil-opp/blog_os#1245]
Can i create Table of Content for readme.md file which helps to find links easily

**Comment by bjorn3** [comment]
Github has been generating a table of content for every markdown file for a while now. Right to the left of the `Readme.md` filename is a button with three ._ on top of each other. If you click on this you get a table of content.

**Comment by Durgesh4993** [comment]
ok  sir @bjorn3 i'll create some new issues

**Comment by Durgesh4993** [comment]
Thank you

**Comment by Durgesh4993** [comment]
![image](https://github.com/phil-opp/blog_os/assets/98798977/57b1ac81-ecc3-4932-92c4-fda7be598f0d)

can i update this index page into landing page, if you are intresing i'll create suitable designes
