### ISSUE TITLE
Unable to run the project as the project crashes after post 3 and i have not even used volatile yet.

### ISSUE THREAD

**Issue by AKgit834** [phil-opp/blog_os#1258]
It throws the following error when i try "cargo run"

error: linking with `rust-lld` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/aadityakaushik/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/aadityakaushik/.cargo/bin:/home/aadityakaushik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "rust-lld" "-flavor" "gnu" "/tmp/rustcRfe5IM/symbols.o" "/home/aadityakaushik/mine/vs/rust/os/target/specs/debug/deps/os-77a1319f10335eec.125ktcj43x1j77lw.rcgu.o" "/home/aadityakaushik/mine/vs/rust/os/target/specs/debug/deps/os-77a1319f10335eec.4bxv69p99dqq6ztg.rcgu.o" "--as-needed" "-L" "/home/aadityakaushik/mine/vs/rust/os/target/specs/debug/deps" "-L" "/home/aadityakaushik/mine/vs/rust/os/target/debug/deps" "-L" "/home/aadityakaushik/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/specs/lib" "-Bstatic" "/home/aadityakaushik/mine/vs/rust/os/target/specs/debug/deps/librustc_std_workspace_core-bd2f432810c8a3c0.rlib" "/home/aadityakaushik/mine/vs/rust/os/target/specs/debug/deps/libcore-06e145513a31b9ac.rlib" "/home/aadityakaushik/mine/vs/rust/os/target/specs/debug/deps/libcompiler_builtins-0b72f5350e608b72.rlib" "-Bdynamic" "--eh-frame-hdr" "-z" "noexecstack" "-L" "/home/aadityakaushik/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/specs/lib" "-o" "/home/aadityakaushik/mine/vs/rust/os/target/specs/debug/deps/os-77a1319f10335eec" "--gc-sections"

  = note: rust-lld: error: undefined symbol: memset
          >>> referenced by num.rs:217 (src/fmt/num.rs:217)
          >>>               core-06e145513a31b9ac.core.2d03f973ff1cd8f1-cgu.13.rcgu.o:(core::fmt::num::imp::fmt_u64::h29d6854c72ef82b1) in archive /home/aadityakaushik/mine/vs/rust/os/target/specs/debug/deps/libcore-06e145513a31b9ac.rlib
          

error: could not compile `os` (bin "os") due to 1 previous error

Help me i have no idea what to do

**Comment by bjorn3** [comment]
Do you have the following things in `.cargo/config.toml`?

```toml
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
```

`compiler-builtins-mem` should cause `memset` to be defined.

**Comment by AKgit834** [comment]
It worked i guess i had some typo error , Thank you so much I thought I had to drop this project because of some error i cannot undertand. Thank you so much.

**Comment by bjorn3** [comment]
Happy to hear that it works for you now!

**Comment by phil-opp** [comment]
@bjorn3 Thanks a lot for answering so many questions here!
