### ISSUE TITLE
Boooting post-03 (vga text mode) on real hardware does not work

### ISSUE THREAD

**Issue by lachsdachs** [phil-opp/blog_os#1263]
I am trying to create a bootable usb stick. `cargo run` is working, and i have all the necessary tools installed, but when i try to boot from the stick it fails, even though writing the image seemed to work fine.

I have tried on two different machines. On one of them i can select the stick as a boot medium, but when i try to run it the screen just flashes black and goes back to normal. The other machine has no OS installed on the primary disk and when i insert the usb stick there and try to reboot it it just prints errors like `DISK BOOT FAILURE, INSERT SYSTEM DISK AND PRESS ENTER` or `not a bootable drive, insert bootable floppy`

**Comment by bjorn3** [comment]
Do you have CMS enabled in the firmware setup for BIOS compatibility?

**Comment by lachsdachs** [comment]
I enabled that  now (had to also disable Kernel DMA protection), but still nothing. And my much older PC probably has it enabled by default. To me it seems like there is an issue with the bootimage tool, but it seems like it's working for other people.
