### ISSUE TITLE
Latest nightly rust requires bootloader = "0.9.24" to work

### ISSUE THREAD

**Issue by yhaliaw** [phil-opp/blog_os#1273]
It seems newer version of LLVM has changed the data layout. 
The `minimal-rust-kernel/#target-specification` section was updated for this.

The `minimal-rust-kernel/#creating-a-bootimage` section would require a update as well:
```
# in Cargo.toml

[dependencies]
bootloader = "0.9.23"
```
The bootloader version should be update to `"0.9.24"`.

**Comment by phil-opp** [comment]
Thanks for reporting!

Note that cargo will automatically pick the latest patch version when setting up a project. You can also run `cargo update` to update your dependencies to their latest compatible versions, without needing to change the `Cargo.toml`.

If you think that updating the Cargo.toml would avoid confusion, feel free to open a PR for this.
