### ISSUE TITLE
Why aren't new posts coming out?

### ISSUE THREAD

**Issue by 88Igor88** [phil-opp/blog_os#1279]
### Discussed in https://github.com/phil-opp/blog_os/discussions/1278

<div type='discussions-op-text'>

<sup>Originally posted by **88Igor88** February  1, 2024</sup>
Why is the last post of 2020?
and why aren't new posts coming out?
Please start writing posts!

Don't ignore me!</div>

**Comment by PitchBlackNights** [comment]
Because they are currently working on edition 3. There was a big stop a little while ago, though that was just because of some issues with the bootloader crate I believe.

**Comment by phil-opp** [comment]
> Because they are currently working on edition 3

Yes, exactly. Also note that I'm working on this project in my free time only and I had less of that since 2020. I know that many people are waiting for new posts and I try my best to finish the new posts soon!

**Comment by 88Igor88** [comment]
THANKS!

**Comment by 88Igor88** [comment]
> Потому что в настоящее время они работают над версией 3. Некоторое время назад произошла большая остановка, хотя, я полагаю, это было просто из-за некоторых проблем с загрузчиком.
> 
> Проверьте, есть ли новые посты в ветке edition-3

There are no new posts.
