### ISSUE TITLE
Change `multiboot_header` section to `multiboot` to match git source and later tutorial

### ISSUE THREAD

**Issue by jasonfagan** [phil-opp/blog_os#13]
On http://blog.phil-opp.com/rust-os/multiboot-kernel.html you have used *multiboot_header* but in the git source and the page http://blog.phil-opp.com/rust-os/setup-rust.html you refer to the section *multiboot* .  little confusing if following along step by step.

As a foot-note, thank you so much for this series, it is a great educational piece.

**Comment by phil-opp** [comment]
Thanks! I think I like `multiboot_header` more, so I will update the later post and the git source to match it.

**Comment by jasonfagan** [comment]
yup I agree, `multiboot_header` is much clearer.

**Comment by phil-opp** [comment]
Cherry picked to tags `multiboot_bootstrap`, `entering_longmode`, `setup_rust`, and `printing_to_srceen`.
