### ISSUE TITLE
 cargo build --target x86_64-blog_os.json  error[E0463]: can't find crate for `core`

### ISSUE THREAD

**Issue by shashank-jain45** [phil-opp/blog_os#1302]
If your issue persists even after installing rust-src  and setting up [unstable] 

Refer to this - 
https://os.phil-opp.com/cross-compile-libcore/#:~:text=If%20you%20get%20an%20error,t%20find%20the%20core%20library.

TLDR;
`cargo install xargo`
`xargo build --target x86_64-blog_os`

It would be nice to add link to this blog in post-2

**Comment by shashank-jain45** [comment]
If your issue persists even after installing rust-src  and setting up [unstable] 

Refer to this - 
https://os.phil-opp.com/cross-compile-libcore/#:~:text=If%20you%20get%20an%20error,t%20find%20the%20core%20library.

TLDR;
`cargo install xargo`
`xargo build --target x86_64-blog_os`

It would be nice to add link to this blog in post-2

**Comment by phil-opp** [comment]
Could you try `cargo build -Z build-std=core --target x86_64-blog_os`? If that works, there is probably an issue with the setup of the `[unstable]` table.

**Comment by shashank-jain45** [comment]
Yupp worked, there was an issue with my cargo.toml ! Thanks
