### ISSUE TITLE
Should I follow edition 2 or 3?

### ISSUE THREAD

**Issue by BoostedDampi** [phil-opp/blog_os#1318]
Hello there,

Firstly, I want to express my gratitude for your exceptional blog series. It's been immensely helpful. Having completed the first chapter of the second edition, I recently became aware of a third edition in development. Now, I'm torn between continuing with the second edition or waiting for the third. Could you please offer some advice on which edition I should follow?

Thank you!

**Comment by kennystrawnmusic** [comment]
I would say a combination of both. Start with what if anything of Edition 3 is written so far and then switch to Edition 2 when you have the basic understanding down — that's how I was able to get things accomplished.

Something for @phil-opp to note is that if he wants someone to work on an Edition 3 interrupts tutorial, given how much work I've done to get it working through trial and error myself using the x2apic crate, I'd be more than happy to oblige.

**Comment by BoostedDampi** [comment]
> I would say a combination of both. Start with what if anything of Edition 3 is written so far and then switch to Edition 2 when you have the basic understanding down because more of Edition 2 is written — that's how I was able to get everything working on my end.

Thank you very much. Is there a way to build edition 3? I've come across some Docker files, but I'm uncertain about how to utilize them.

**Comment by kennystrawnmusic** [comment]
> > I would say a combination of both. Start with what if anything of Edition 3 is written so far and then switch to Edition 2 when you have the basic understanding down because more of Edition 2 is written — that's how I was able to get everything working on my end.
> 
> 
> 
> Thank you very much. Is there a way to build edition 3? I've come across some Docker files, but I'm uncertain about how to utilize them. 

Not sure. Building the posts is @phil-opp's job anyway.

**Comment by FallenDeity** [comment]
> I would say a combination of both. Start with what if anything of Edition 3 is written so far and then switch to Edition 2 when you have the basic understanding down because more of Edition 2 is written — that's how I was able to get everything working on my end.
> 
> Something for @phil-opp to note is that if he wants someone to work on an Edition 3 interrupts tutorial, given how much work I've done to get it working through trial and error myself using the x2apic crate, I'd be more than happy to oblige.

Would you be able to create a gist of some sort along with a bit of explanation and code snippets if possible think tha would be very helpful for the community and a bunch of people looking to use apic and implement keyboard and timer interrupts.
