### ISSUE TITLE
Compiling and running the blog_os

### ISSUE THREAD

**Issue by jeb2239** [phil-opp/blog_os#132]
![image](https://cloud.githubusercontent.com/assets/5044729/13034413/dcd92800-d302-11e5-844e-3fc5d9a04d8b.png)

Is this what the start up is supposed to look like when you download and do  make run?

It is complaining there is no bootable device.

**Comment by phil-opp** [comment]
No, it should look like this:

![screenshot-qemu - press ctrl-alt to exit mouse grab](https://cloud.githubusercontent.com/assets/1131315/13034666/118c0f5c-d33c-11e5-8869-9d301eadf3f6.png)

It should boot after `Booting from DVD/CD...` Unfortunarely I'm not sure what's going on here. Do you have a recent GRUB and QEMU version?
