### ISSUE TITLE
`post-07` typo

### ISSUE THREAD

**Issue by nightmare-tech** [phil-opp/blog_os#1327]
On line 68 should it be: "... e.g., **line 5** of the secondary PIC is assigned to the mouse..." instead of "**line 4**" ?
![image](https://github.com/phil-opp/blog_os/assets/73050725/df9277ff-7d99-4fb3-b25d-83d0cd0e90f4)

**Comment by phil-opp** [comment]
I use zero-based counting here, so the first line is "line 0".
