### ISSUE TITLE
APIC enable failed on UEFI, but work on BIOS

### ISSUE THREAD

**Issue by xuanplus** [phil-opp/blog_os#1335]
I try to add apic for my code, and it works on bios.
When I selected the uefi, I got result like that:
![image](https://github.com/phil-opp/blog_os/assets/107631981/137c5b10-92cd-4b7f-8a12-9c9d9cc6e9f6)

I have closed the pic, and my local apic code is following:
```rust
self.lapic = LocalApicBuilder::default()
    .timer_vector(32)
    .error_vector(51)
    .spurious_vector(39)
    .set_xapic_base(apic_virtual_address)
    .build()
    .ok();
```
I don't what cause that, what should I do for that?

**Comment by phil-opp** [comment]
Thanks for reporting! 

Closing in favor of https://github.com/rust-osdev/bootloader/issues/447
