### ISSUE TITLE
Final disc image not produced, but I have got stages (5MB) and an EFI file

### ISSUE THREAD

**Issue by hydroperfox** [phil-opp/blog_os#1337]
I was following this tutorial part: [Minimal Rust kernel: Printing to screen](https://os.phil-opp.com/minimal-rust-kernel/#printing-to-screen).

I have stopped as I migrated the project structure conforming to the Create a Disk Image section referenced in the [Bootloader crate home](https://github.com/rust-osdev/bootloader/blob/HEAD/docs/create-disk-image.md).

I have done that, but I had to discard my `x64.json` target description due to location errors involving `../` segments and use the official `x86_64-unknown-none` target that produces an ELF executable.

[Log and prints](https://gist.github.com/hydroperfox/ee2e413279def587201f78314ada1b2a)

**Comment by bjorn3** [comment]
It looks like you are using bootloader 0.11. The second edition of blog os depends on bootloader 0.9.

**Comment by hydroperfox** [comment]
@bjorn3 I wasn't aware! I have just cloned the `post-03` branch and it worked perfectly with QEMU. Guess I'll just use it ready then.

**Comment by hydroperfox** [comment]
I have just one question: there are two license files in the `post-03` branch, but they have copyright owner and year.
