### ISSUE TITLE
seemingly a typo in 3rd edition's booting chapter

### ISSUE THREAD

**Issue by bingmatv** [phil-opp/blog_os#1339]
https://github.com/phil-opp/blog_os/blob/edition-3/blog/content/edition-3/posts/02-booting/index.md The offset of partition entry 4 is written as 444, which may be wrong.

**Comment by bingmatv** [comment]
There are 2 "use" in "We can now use use a simple cargo build to cross-compile our kernel".

**Comment by phil-opp** [comment]
Thanks for reporting! I fixed it in commit [ce01059](https://github.com/phil-opp/blog_os/commit/ce010596206ea2bab9c4a89ee28f2b4d66117a3c). 

Feel free to just send a PR for such changes in the future. You can easily do this through GitHub's web interface: https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files
