### ISSUE TITLE
VGA colors: 'variant is never used'

### ISSUE THREAD

**Issue by wolfgang42** [phil-opp/blog_os#134]
Rust complains that most of the VGA colour constants are dead code. This creates a big pile of compiler warnings to wade through; perhaps this enum should have the `#[allow(dead_code)]` attribute?

**Comment by phil-opp** [comment]
The `#[allow(dead_code)]` attribute is there [in the code](https://github.com/phil-opp/blog_os/blob/printing_to_screen/src/vga_buffer.rs#L41) but I forgot to mention it in the post. Thanks for reporting!
