### ISSUE TITLE
PIT handler not being called

### ISSUE THREAD

**Issue by shinobu-uwu** [phil-opp/blog_os#1351]
Hello! I've been following, loosely, the blog post and during the interrupts I tried running the kernel but the PIT handler is not being called at all. I double checked if interrupts are enabled, I added an inline asm with the `sti` call, but no luck, so I'm guessing the problem is that the handler is not being called.

You can check the code in this repository: https://github.com/shinobu-uwu/jon

More especifically, the relevant code is here:
 https://github.com/shinobu-uwu/jon/blob/9caded006b42431da1b7f03051cab520c537030a/kernel/src/arch/x86/interrupt.rs#L4

https://github.com/shinobu-uwu/jon/blob/9caded006b42431da1b7f03051cab520c537030a/kernel/src/arch/x86/idt.rs#L21

https://github.com/shinobu-uwu/jon/blob/9caded006b42431da1b7f03051cab520c537030a/kernel/src/arch/x86/mod.rs#L15 

I even asked in a discord channel if anyone knew why it's not working, but no one could find an answer, so I figured I'd ask here, maybe it's a known issue

**Comment by AtomicGamer9523** [comment]
You don't have any `#[no_mangle]`s in `idt.rs`, maybe try adding them?

**Comment by shinobu-uwu** [comment]
Unfortunately `#[no_mangle]` didn't change anything, which makes sense since a pointer to a function is being passed as the handler, but thanks for the suggestion!

**Comment by AtomicGamer9523** [comment]
I just compared these two lines, [yours](https://github.com/shinobu-uwu/jon/blob/main/kernel/src/arch/x86/idt.rs#L21) and [phil's](https://github.com/phil-opp/blog_os/blob/post-07/src/interrupts.rs#L39)

Is there a reason you are adding the `+ 1` to the offset ?
In Phil's the value is `32` while in your code it ends up being `33`.
Everything else looks the same... maybe try removing that `+1` ?

**Comment by shinobu-uwu** [comment]
Uh, I have no idea why I was adding 1 to the offset, however the handler's still inexplicably not running...

I didn't have much time to investigate this up until now, so first I decided to run qemu with `-monitor stdio`, when I run `info pic` I get this output

```
ioapic0: ver=0x20 id=0x00 sel=0x00
  pin 0  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 1  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 2  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 3  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 4  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 5  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 6  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 7  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 8  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 9  0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 10 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 11 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 12 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 13 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 14 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 15 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 16 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 17 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 18 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 19 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 20 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 21 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 22 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  pin 23 0x0000000000010000 dest=0 vec=0   active-hi edge  masked fixed  physical
  IRR      (none)
  Remote IRR (none)
pic1: irr=00 imr=ff isr=00 hprio=0 irq_base=28 rr_sel=0 elcr=00 fnm=0
pic0: irr=01 imr=ff isr=00 hprio=0 irq_base=20 rr_sel=0 elcr=00 fnm=0
```

As you can see all the pins have the same value, and that one bit set to `1`, the 16th, means that the interrupt is masked, meaning it won't be forwarded to the CPU. I'm still investigating how to solve this, will report back when I find something new

**Comment by shinobu-uwu** [comment]
I feel so stupid for this

The reason why it's not working is because PIC is not supported under UEFI, if I run the BIOS binary it works...

Sorry for wasting your time 🙃

**Comment by shinobu-uwu** [comment]
I feel so stupid for this

The reason why it's not working is because PIC is not supported under UEFI, if I run the BIOS binary it works...

Sorry for wasting your time 🙃
