### ISSUE TITLE
Where is the full source code?

### ISSUE THREAD

**Issue by ViktorPopp** [phil-opp/blog_os#1362]

**Comment by tsatke** [comment]
In the branches
https://github.com/phil-opp/blog_os/tree/post-01/src

**Comment by ViktorPopp** [comment]
> In the branches
> https://github.com/phil-opp/blog_os/tree/post-01/src

Oh. I already knew that 🙃. Just forgot it.

**Comment by tsatke** [comment]
You've created it, only you and the maintainers can close it.
