### ISSUE TITLE
"Printing to Screen" contains a funny character

### ISSUE THREAD

**Issue by mtnygard** [phil-opp/blog_os#151]
At https://github.com/phil-opp/blog_os/blob/gh-pages/printing-to-screen.html#L250, 

Should be repr(C), but appears in HTML as repr\&copy;

**Comment by phil-opp** [comment]
Thanks for reporting! I've migrated to a new static site generator today, which uses the [blackfriday](https://github.com/russross/blackfriday) markdown renderer. It seems like it has a "feature" to automatically convert (C) to ©. I'll take a closer look tomorrow…

**Comment by phil-opp** [comment]
Note to myself: 

https://gohugo.io/overview/configuration#configure-blackfriday-rendering

and

https://github.com/russross/blackfriday/blob/b43df972fb5fdf3af8d2e90f38a69d374fe26dd0/smartypants.go#L152

seem relevant.
