### ISSUE TITLE
Build Fails With rustc 1.11.0-nightly

### ISSUE THREAD

**Issue by leokhachatorians** [phil-opp/blog_os#175]
When attempting to run 'make run':

/raw-cpuid-2.0.0/src/lib.rs:435:25: 435:35 error: `raw::Slice` does not name a structure [E0422]
/raw-cpuid-2.0.0/src/lib.rs:2097:29: 2097:39 error: `raw::Slice` does not name a structure [E0422]

**Comment by phil-opp** [comment]
Thanks for reporting! It's an issue in the raw-cpuid crate: gz/rust-cpuid#4

It's already fixed in on github and a new crates.io version will be released on Wednesday.

**Comment by leokhachatorians** [comment]
Awesome. Thanks for taking the time and effort into making this, really helpful.
