### ISSUE TITLE
Catch Divide-By-Zero faults instead of Page Faults in “Catching Exceptions” Post

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#184]
Currently, we try to catch page faults using a simple `extern "C" fn() -> !` handler function. The problem is that the CPU pushes an error code on page faults, which leads to a wrong stack pointer alignment. Thus the final code causes a general protection fault on real hardware (or in QEMU with `-enable-kvm`) (reported by @nxnfufunezn in #179).

Possible solutions:

1. Insert a random `push 0` in the handler, without a detailed explanation.
2. Add a `Testing on real Hardware` section at the end of [Catching Exceptions](http://os.phil-opp.com/catching-exceptions.html), where we discover the bug. Debug the GP fault in the upcoming post.
3. Avoid the GP fault by catching Divide-By-Zero error (DE) instead of page faults. The DE doesn't push an error code, so the stack is correctly aligned.

I don't like option 1, since it's only a hacky workaround. Option 2 is fine and emphasizes the differences between QEMU and real hardware (QEMU doesn't check alignment on `movaps` instructions). However, newer QEMU version might do the alignment check and then our code doesn't work anymore.

So I think that option 3 is the best solution.

**Comment by nxnfufunezn** [comment]
I added two macro for isr with and without err.
https://github.com/nxnfufunezn/RstyOS/blob/fix-idt/src/interrupts/idt.rs#L45-L70
Is it ok ?
