### ISSUE TITLE
Incorrect <atom:link> in RSS feed

### ISSUE THREAD

**Issue by KarboniteKream** [phil-opp/blog_os#211]
While scraping the RSS, I noticed that the `<atom:link>` tag specifies the feed's URL as `http://os.phil-opp.com/post/atom.xml`, while the actual feed is at `http://os.phil-opp.com/atom.xml`.

**Comment by phil-opp** [comment]
Thanks a lot for reporting!

**Comment by phil-opp** [comment]
Fixed in #212
