### ISSUE TITLE
BumpAllocator allocate() function vunerable to overflow

### ISSUE THREAD

**Issue by 4e554c4c** [phil-opp/blog_os#220]
This might be a complete non-issue because it would only happen in release mode, but I thought I should bring it up. Calling allocate(-n as usize, 0) would actually _free_ n bytes in the allocator and never run out of memory. A better option would be use a saturating add which would never free memory make the function simply return `None` when called with a negative number.

**Comment by phil-opp** [comment]
Good catch! This should definitely be a saturating add. Thanks a lot for reporting!

Do you want to send a PR? Alternatively, I could fix it myself if you don't have the time…

**Comment by 4e554c4c** [comment]
Sure! If you are fine waiting a day, I will fix this.

**Comment by phil-opp** [comment]
> If you are fine waiting a day

Of course! Thanks a lot!
