### ISSUE TITLE
Add a “compiling on other operating systems” guide

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#222]
In this guide we could collect the easiest solutions for operating systems other that 64-bit Linux. For example:
- Mac OS
- Windows
- 32 bit Linux
- how to do it using a virtual machine

**Comment by cardoe** [comment]
I'd recommend possibly using Docker to bundle up all your dependencies.

**Comment by andre-richter** [comment]
Hi,

I just started with chapter one. I encapsulated the toolchain into a docker container and adapted the Makefile accordingly. Makes the development more independent of the host OS.

@phil-opp kindly have a look. If you think its useful, you can add something like that to your blog repo and hook it to https://hub.docker.com/. This way, people starting the tutorial would just pull a prebuilt and QA'ed container from there.

Best regards,
Andre

**Comment by phil-opp** [comment]
@andre-richter Thanks, seems like a good idea! I'm on vacation until end of August, but I will take a look when I'm back.

**Comment by phil-opp** [comment]
The work on the second edition (which supports Windows and macOS natively) is making good progress, so I'm going to close this issue in favor of https://github.com/phil-opp/blog_os/issues/360.
