### ISSUE TITLE
QUESTION: Using relative paths without blog_os workspace

### ISSUE THREAD

**Issue by 4e554c4c** [phil-opp/blog_os#234]
Hello, I am trying to work on crates that are used in blog_os such as multiboot2 which require me to use a relative path (or relative git repository). When I try to compile blog_os I get this error message:
```
error: workspace member `.../multiboot2-elf64/Cargo.toml` is not hierarchically below the workspace root `.../blog_os/Cargo.toml`
```
Is there any way to have a dependancy as a relative path without having it in the blog_os workspace?

**Comment by phil-opp** [comment]
Hmm, good question… The [RFC](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md) says:

> a crate which specifies [workspace] without a members key will transitively crawl path dependencies to fill in this key. This way all path dependencies (and recursively their own path dependencies) will inherently become the default value for workspace.members.

I don't think that this is a good default. A better default might be _“all path dependencies below the workspace root”_. I would recommend to open an issue at [rust-lang/cargo](https://github.com/rust-lang/cargo).

--

**Possible workarounds** (untested):

- specify the workspace members explicitely:

```toml
[workspace]
members = ["crate1", "crate2", "crate3"]
```

- use [.cargo/config` overrides](http://doc.crates.io/specifying-dependencies.html#overriding-with-local-dependencies)

**Comment by 4e554c4c** [comment]
Possible workaround number 1 does not work, I have tried it before opening this issue.

Possible workaround number 2 works perfectly, thank you for finding this.

**Comment by phil-opp** [comment]
Sounds like a bug to me. Did you open a cargo issue?

**Comment by 4e554c4c** [comment]
@phil-opp The relavent issue is rust-lang/cargo#3156 if you did not get a notification from me opening it
