### ISSUE TITLE
Use redox-os/ralloc? 

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#237]

**Comment by 4e554c4c** [comment]
Redox-os/ralloc is a top notch allocator and would certainly be nice to use in an opperating systems project. However (to me) it seems like the point of blog OS is to have every part of the operating system simple and easy to explain, and a full fledged allocator is not so. Of course the `hole_list_allocator` crate that is created in the project is contains another crate that does much of the work but this is explained well in the blog and every part of the allocate feature is implemented in the blog itself. 

A good counter-argument to this would be that you have already explained allocators and it would now be more useful to include a high performance one for later use.

I think that either way will work fine, but I think there should be a discussion on it.

**Comment by Redrield** [comment]
Seems like using ralloc won't just be an easy swap of extern crate definitions. Trying to do that for what I've been building up with the help of your blog just resulted in compile-time errors, because ralloc depends on `sc`, and we don't have a platform for that

**Comment by Evrey** [comment]
Does Blog OS need it for the kernel? Or is a mere page allocator everything the kernel needs, delaying `ralloc` or whatever until Blog OS reaches user space?

Pick whichever you prefer, but if the decision would be to include a general purpose allocator like `ralloc` into the kernel, then I'd like Blog OS to first build a stupidly simple own one to teach the basic inner workings. Just like the old blog taught handling interrupt calling convention with assembly before introducing that magic x86 interrupt `extern` declaration. Such a simple allocator might be based on [LuaJIT 3's ideas](http://wiki.luajit.org/New-Garbage-Collector#arenas), which are very easy to understand and implement.

**Comment by phil-opp** [comment]
It was just something I stumpled upon back then, which I wanted to explore further. It seems like ralloc is a pure userspace allocator, so it's not suitable for our kernel. Maybe we can use it when we reach user space, but this will take some time, so I think it's best to close this issue for now.

@Evrey Thanks for the link, looks interesting! I like the idea of putting more allocator types into blog_os.

> Just like the old blog taught handling interrupt calling convention with assembly before introducing that magic x86 interrupt extern declaration.

You do not like the x86 interrupt calling convention? The old assembly based posts are still online and linked from the new one, so you can still do it this way if you like. For me, the x86-interrupt calling convention seemed like a good idea, since it made the topic much easier and less error-prone.

**Comment by Evrey** [comment]
I guess you misunderstood me. =D I do like that calling convention. I'll take whatever makes me need less `#[naked] fn`s. What I meant was:

By linking back to the assembly-based interrupt handling post, you not only taught the proper use of the interrupt calling convention, but also taught what that thing actually does and how it works behind the curtain.

In a similar way, if the blog goes *"let's link that allocator crate and have `extern crate alloc;`"*, then I'd like the blog to have an article about how general purpose allocators work and what Rust magic is required to get one.

**Comment by phil-opp** [comment]
Ah, thanks for clarifying! I fully agree that we should have a post that explains how allocators work (generally and in Rust).
