### ISSUE TITLE
Incorrect in make file on blog post "set up rust"

### ISSUE THREAD

**Issue by millasvs** [phil-opp/blog_os#255]
In the make file from the blog post on setting up rust, a backslash is lacking in the $(kernel) part of the source code of the make file on here. It's correct on the blog, but not here.

**Comment by phil-opp** [comment]
I'm not quite sure what you mean. The backslash should be only needed if the rule is split into multiple lines (the backslash marks a line break).

**Comment by phil-opp** [comment]
Just to ensure that I understand everything correctly: Are you referring to this code from the blog?:

```make
$(kernel): cargo $(rust_os) $(assembly_object_files) $(linker_script)
	@ld -n -T $(linker_script) -o $(kernel) \
		$(assembly_object_files) $(rust_os)
```

**Comment by phil-opp** [comment]
@millasvs I'm gonna close this, since I don't understand the problem. However, I'm happy to reopen it if I misunderstood something…

**Comment by millasvs** [comment]
No, my issue was incorrect. So it's right of you to close it. Thanks for a
nice blog!

Den 19 dec 2016 11:46 skrev "Philipp Oppermann" <notifications@github.com>:
