### ISSUE TITLE
Multi Core Issues in Linux Kernel Scheduler

### ISSUE THREAD

**Issue by RobertWHurst** [phil-opp/blog_os#260]
I found this very interesting paper on the linux kernel scheduler. It demonstrates some serious issues with wasting cores while overloading others for seconds at a time. I thought you might find it interesting @phil-opp. I hope it's at least distantly relevant. You can find the paper here => http://www.ece.ubc.ca/~sasha/papers/eurosys16-final29.pdf. They have also provided their own solutions to the problem in the form of patches found here => https://github.com/jplozi/wastedcores

Thanks for this awesome series. I can't explain how much I've enjoyed it thus far.
Cheers 🍻

**Comment by phil-opp** [comment]
Sorry for the late reply.

This looks really interesting, thanks for the links!

> Thanks for this awesome series. I can't explain how much I've enjoyed it thus far.

Thanks a lot! :)

**Comment by Mubelotix** [comment]
This issue could be closed
