### ISSUE TITLE
Tag catching_exceptions no longer compiles due to x86 crate change

### ISSUE THREAD

**Issue by Zynist** [phil-opp/blog_os#269]
The IDT submodule needs a small update to compile with the latest `x86` crate.

There is no `shared` or `bits64` submodules in x86, so the following must be changed:

```
use x86::shared::segmentation::{self, SegmentSelector};
use x86::shared::PrivilegeLevel;
```
becomes:
```
use x86::segmentation::{self, SegmentSelector};
```

(`PrivilegeLevel` is no longer required).

The load function should be changed like so:
```
pub fn load(&'static self) {
  use x86::dtables::{DescriptorTablePointer, lidt};   // change here
  use core::mem::size_of;

  let ptr = DescriptorTablePointer {
    base: self as *const _ as *const ::x86::irq::IdtEntry as u64,  // and here
    limit: (size_of::<Self>() - 1) as u16,
  };

  unsafe { lidt(&ptr) };
}
```

and finally the `Entry::missing()` function:
```
fn missing() -> Self {
  Entry {
    gdt_selector: SegmentSelector::new(0), // PrivilegeLevel::Ring0 no longer required
    pointer_low: 0,
    pointer_middle: 0,
    pointer_high: 0,
    options: EntryOptions::minimal(),
    reserved: 0,
  }
}
```

**Comment by phil-opp** [comment]
> The IDT submodule needs a small update to compile with the latest x86 crate.

Just to be sure: The latest version of the x86 crate is 0.8.0, isn't it? I just updated to it in #266.

> There is no shared or bits64 submodules in x86

According to [the docs](https://docs.rs/x86/0.8.0/x86/) and [the source](https://github.com/gz/rust-x86/tree/0.8.0/src), there is. Maybe you're using an older version of x86?

**Comment by Zynist** [comment]
Ah! Sorry, I should have checked more closely, my apologies. I have been following along in the past week, so the change must have happened mid-way and I'm essentially suggesting a revert. I've just updated to 0.8.0 and now my old code has broken in build, so while I'm fixing it to match the latest API I'll close this issue. Thanks for the quick response, Philipp, and thank you for the tutorial, it's really useful.

**Comment by phil-opp** [comment]
> Ah! Sorry, I should have checked more closely, my apologies.

No worries! Please don't hesitate to report similar problems in the future.

> I've just updated to 0.8.0 and now my old code has broken in build

Sorry for the sudden breakage. The problem is that I need a feature of 0.8.0 for the upcoming post, so I had to update it eventually.

> Thanks for the quick response, Philipp, and thank you for the tutorial, it's really useful.

You're welcome, I'm glad you like it :).
