### ISSUE TITLE
“Double Faults” post breaks returning from exceptions

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#277]
“`int!(3)` produces a double fault while it returned correctly in the previous post”. ([reported by Blaž Šnuderl](http://os.phil-opp.com/double-faults.html#comment-3091388494))

It seems like the problem is our new GDT, which doesn't have a data segment descriptor. This alone is fine, but the `ss` register still holds a value which is saved to the stack when an exception occurs and checked by `iretq` when we return. If the saved value is not a valid data segment descriptor (or a null descriptor), a general protection fault occurs.

One possible solution is to load 0 into the `ss` register after entering long mode (null descriptors are explicitely allowed in `ss` in 64-bit mode). Another solution is to add a valid writable data segment to our new GDT.

I'm pretty sure that this is also the cause of the problem reported by @TengenJulian [on gitter](https://gitter.im/phil-opp/blog_os?at=586ed823aa6be0472f125c45):

>  I have been reusing the same GDT code for stack switching, but without the data segment, the iretq generates a GPF.

Related to #273

**Comment by tiehexue** [comment]
perfect tutorial. I am so expecting next one.

**Comment by bjorn3** [comment]
Looks like utterances thinks this issue is the comment issue for https://os.phil-opp.com/double-fault-exceptions/

**Comment by phil-opp** [comment]
@tiehexue Thanks a lot!

@bjorn3 Seems like the github search API has no way to search for exact matches, so it returns this issue for the search term "double-fault-exceptions" since all three words are in the title. Seems like we should switch utterances to look for the full URL instead of just the pathname.

**Comment by phil-opp** [comment]
Fixed in 56c9b0e. This issue should no longer be chosen by utterances.
