### ISSUE TITLE
BitField's set/get_range methods are now set/get_bits

### ISSUE THREAD

**Issue by iBelieve** [phil-opp/blog_os#280]
Thanks for the great blog series! It's been very interesting and helpful as I rebuild my toy OS kernel from x86 and C++ to x86_64  and Rust.

I was working my way through http://os.phil-opp.com/catching-exceptions.html, and noticed that the set_range and get_range methods on the bit_field::BitField trait are gone. It looks like they recently got renamed to set_bits and get_bits in a pull request merged in https://github.com/phil-opp/rust-bit-field/commit/027be1c67a2e5ab1e55a5f88b3ab93362075e7f8.

**Comment by phil-opp** [comment]
Thanks for reporting!
