### ISSUE TITLE
Do we need to save callee saved registers in an interrupt handler?

### ISSUE THREAD

**Issue by liuzix** [phil-opp/blog_os#284]
You mentioned in your blog that we only need to save the caller saved registers because the interrupt handler function will take care of the callee saved registers. But it seems that if I set `optimization = 3`, then the interrupt handler would not save any register other than `rbp`. I'm not an expert in ABI but I guess if the compiler discovers none of  the callers  need a certain register, it will just not save it? Therefore it might be necessary for the programmer to take care of that in an interrupt handler.

**Comment by 4e554c4c** [comment]
As f ar as I'm aware interrupt handler function does not need to save any callee registers if it does not modify them. If any functions higher in the call stack modify them, they must save them first by the calling convention.

**Comment by liuzix** [comment]
It is true that you don't have to save any state if you don't modify them, but how can you prevent the compiler from modifying them? What I am wondering is, whether there is a way to force the compiler to save them, or not to use them. @4e554c4c

**Comment by 4e554c4c** [comment]
From what I can tell `rbp` is the only callee saved register that the interrupt handler function modifies, so it's the only one that needs to be saved. If the function modifies any other callee registers it should end up saving them first. `extern C` functions should do exactly what you said by default: saving registers or not using them.

**Comment by phil-opp** [comment]
> What I am wondering is, whether there is a way to force the compiler to save them, or not to use them.

That's exactly what we do at the moment by using the C calling convention. Basically, we tell the compiler "you are free to modify registers xyz as you like, but you need to restore the original values of registers uvw  before returning" (xyz are the caller-saved registers and uvw are the callee saved registers here). So the compiler can either avoid using callee saved registers or doing a backup&restore. In this specific case, it seems like the compiler backups&restores `rbp` and doesn't modify the other callee saved registers.

Ideally, we would use a special calling convention that says "_all_ registers must be restored to their original values before returning". Thus, we could avoid the manual backup of caller saved registers too. The compiler would then ensure that all registers that are modified by the function are restored to their previous state before returning. LLVM seems to support [such a calling convention](https://reviews.llvm.org/D15567) already, but the Rust compiler unfortunately doesn't.

**Comment by phil-opp** [comment]
Closing, since the x86-interrupt calling convention works now.
