### ISSUE TITLE
.bss section is not zeroed

### ISSUE THREAD

**Issue by ghost** [phil-opp/blog_os#288]
in the multiboot2 specifications at [](http://download-mirror.savannah.gnu.org/releases/grub/phcoder/multiboot.pdf) chapter 3 `3.1.5`

> bss_end_addr
> Contains the physical address of the end of the bss segment.  The boot loader
> initializes this area to zero, and reserves the memory it occupies to avoid placing
> boot modules and other data relevant to the operating system in that area.  **If
> this field is zero, the boot loader assumes that no bss segment is present**
> 

so if it's zero the boot loader will not initializes it to zero

**Comment by phil-opp** [comment]
Good catch, thanks for reporting!

Luckily, it seems like GRUB will automatically zero the `.bss` section when loading an ELF file, even without `bss_end_addr`. See this [thread on hacker news](https://news.ycombinator.com/item?id=7590790) and the [grub-core/loader/multiboot_elfxx.c](https://github.com/coreos/grub/blob/ccf8c4a280d29f7fe0df7b26f33982e71fab9e18/grub-core/loader/multiboot_elfxx.c#L160-L162) file.

**Comment by hackereg35** [comment]
Good to know, thank you

**Comment by le-jzr** [comment]
> If this field is zero,

This actually requires that the field exists in the first place. BlogOS doesn't include the address tag at all, so the bootloader reads all those values from the ELF file instead.

**Comment by phil-opp** [comment]
Closing since this seems to be resolved (and it doesn't affect the second edition anyway).
