### ISSUE TITLE
undefined reference to rust_begin_unwind error

### ISSUE THREAD

**Issue by rajiv256** [phil-opp/blog_os#293]
Even after adding `rlibc ` a new error crept into the build. There was a problem with panic_fmt() function in `lib.rs`. 
if it(a function) is marked with #[lang = "panic_fmt"] then it will be assigned "rust_begin_unwind" as symbol name. As referred from this [https://github.com/rust-lang/rust/issues/38281](issue). 

So adding `#[no_mangle]` solves this issue.

**Comment by phil-opp** [comment]
> So adding #[no_mangle] solves this issue.

I thought we already solved this issue. Maybe we forgot to update something… Where did you find the `panic_fmt` function without `no_mangle`?

**Comment by phil-opp** [comment]
Closing as stale. This only affects the first edition, which is no longer maintained.
