### ISSUE TITLE
Introduce custom target earlier

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#300]
We used to introduce the custom target in the “Returning from Exceptions” post. This post is no longer part of the main series, since it was replaced by “Handling Exceptions”. However, the new post does not introduce the custom target. This means that we're still using the `x86_64-unknown-linux-gnu` target with SSE and red zone enabled, which is a very bad idea…

I think the best solution is to introduce the custom target already in “Set Up Rust”, since the process is a lot easier now thanks to xargo.

**Comment by zarevucky** [comment]
On the other hand, the original position is more educational, as people following the post will get to experience the faults that happen with red zone enabled.

**Comment by phil-opp** [comment]
The problem is that it's difficult to deterministically introduce a fault caused by the red zone, especially without hardware interrupts. The [previous posts](http://os.phil-opp.com/returning-from-exceptions.html#the-red-zone) disabled the red zone without any previous fault, too.

Another argument for disabling the red zone earlier is that people might only read “Set Up Rust” without reading all the details of the following posts. When these people leave the red zone enabled they will experience ugly bugs eventually without any idea what's happening. So I think it's better to mention such pitfalls as soon as possible, especially when they're as suprising as the red zone.

**Comment by gil0mendes** [comment]
The red zone bugs are really difficult to debug and to get the source of problems. I think the @phil-opp is right. We cloud include the concept and explain the problems in "Set Up Rust" post, and also introduce Xargo at that point.

**Comment by zarevucky** [comment]
Fair points. A separate post explaining red zone would still be nice though, since it's hard to explain the problem without explaining interrupts first. So maybe a note like 

> **it's absolutely necessary to disable red zone in kernel code, as will be explained once interrupt handling is introduced**

in the target setup, and a separate side post on red zone in the interrupt handling section (mostly a copypasta from the old post)?

**Comment by phil-opp** [comment]
I decided to move the _complete_ red zone explanation [to “Set Up Rust”](http://os.phil-opp.com/set-up-rust.html#the-red-zone), even though we don't really explain the exception procedure at this point. But I think it's better than some unexplained “this is really bad, so just disable it”.
