### ISSUE TITLE
Handling Exceptions post outdated link and compilation errors

### ISSUE THREAD

**Issue by NullP01nt** [phil-opp/blog_os#303]
On the post about Handling Exceptions, where it links to the content on GitHub, it links to a branch/tag 'handling_exceptions' that no longer exists on the repository.

Further down, where it describes how to generate a breakpoint interrupt, my rust compiler tells me that `x86_64::instructions::interrupts::int3()` is not found, however, replacing it with x86_64's macro `unsafe { int!(3) };` works. This would require that the crate definition be marked with `#[macro_use]`.

I just upgraded to x86_64 version 0.1.2, which fixes the issue of finding the `int3()` function.

**Comment by phil-opp** [comment]
Sorry for the late reply.

Thanks a lot for reporting! I was short on time when I published “Handling Exceptions” and decided to postpone the creation of the GitHub tag to the next day. But I still did not have the time to do it :disappointed: .

I'll try to fix both things over the easter weekend.
