### ISSUE TITLE
Double Faults SegmentSelector::empty(), old x86 code

### ISSUE THREAD

**Issue by NullP01nt** [phil-opp/blog_os#304]
On the Double Faults blog post, you're using `SegmentSelector::empty()` in the `interrupts::init()` function.
However, on my version of `x86_64` (0.1.2), `SegmentSelector` has no member function called `empty()`, also according to the official docs. How would I initialize a SegmentSelector to be empty?

**Comment by NullP01nt** [comment]
I've managed to solve this, looks like some of the code in the post was still dependent on the x86 crate. By replacing the call to `SegmentSelector::empty()` with `SegmentSelector::new(0, PrivilegeLevel::Ring0)`, you're effectively doing the same thing. Just don't forget to write `use x86_64::PrivilegeLevel;` somewhere appropriately in `src/interrupts/mod.rs`.

The code should be updated to complete the transition to the `x86_64` crate.

**Comment by gil0mendes** [comment]
If you use just `SegmentSelector(0)` is actually the same thing, but a bit shorter. 🙂 And yes, you must put the `use x86_64::structures::gdt::SegmentSelector;` inside of the `init` function (you can also put it at the top of the page, but you won't use it anywhere else).

**Comment by phil-opp** [comment]
Fixed in #305
