### ISSUE TITLE
The multiboot2 crate can be a problem

### ISSUE THREAD

**Issue by gil0mendes** [phil-opp/blog_os#308]
Hey,

After reading all the posts, me and a friend of mine, we continued implementing other things. We already divide the code into two different parts, one is a crate with the architecture specific code, and another with the common code (in order words, the real kernel).

Now, we need the MemoryController in order to map some space for the initial process. For that, we have tried to make a static with a mutable reference for the MemoryController instance, but the `multiboot2::memory_map::MemoryArea` don't let us do that because it doesn't satisfy the `core::marker::Send` in order to create a shared type.

This can be a issue to the future, here too?

```text
error[E0277]: the trait bound `*const multiboot2::memory_map::MemoryArea: core::marker::Send` is not satisfied in `arch::memory::MemoryController`
  --> src/lib.rs:26:1
   |
26 | static MEMORY_CONTROLLER: Mutex<Option<&'static mut MemoryController>> = Mutex::new(None);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ within `arch::memory::MemoryController`, the trait `core::marker::Send` is not implemented for `*const multiboot2::memory_map::MemoryArea`
   |
   = note: `*const multiboot2::memory_map::MemoryArea` cannot be sent between threads safely
   = note: required because it appears within the type `multiboot2::memory_map::MemoryAreaIter`
   = note: required because it appears within the type `arch::memory::AreaFrameAllocator`
   = note: required because it appears within the type `arch::memory::MemoryController`
   = note: required because of the requirements on the impl of `core::marker::Send` for `&'static mut arch::memory::MemoryController`
   = note: required because it appears within the type `core::option::Option<&'static mut arch::memory::MemoryController>`
   = note: required because of the requirements on the impl of `core::marker::Sync` for `spin::Mutex<core::option::Option<&'static mut arch::memory::MemoryController>>`
   = note: shared static variables must have a type that implements `Sync`
```

**Comment by le-jzr** [comment]
IMO multiboot2 crate should be used only to read the multiboot structure from memory and set up kernel's own memory tracking. Once you start working with distinct processes, even just holding on to the initial multiboot references in memory might cause a world of problems.

**Comment by gil0mendes** [comment]
Yap, I agree with that. One of my approaches was copying the memory areas into another structure and starting using that one. That probably will solve the issue. Other inconvenience, is the need to pass a FrameAllocator for each method from the mapper, that can be really tedious in the future. :)

**Comment by le-jzr** [comment]
By the way, is that code of yours public? I'm trying to discover and keep track of all the Rust projects that implement "that OS stuff every system needs to handle pretty much the same way".

**Comment by gil0mendes** [comment]
Cloning the Multiboot areas to another structure fix the problem, tks. [Commit with the fix.](https://github.com/Infinity-OS/infinity/commit/e8a5cd1df55614e868b4eef21d35ccad278bf168)
