### ISSUE TITLE
Boot failed: Could not read from CDROM (code 0009)

### ISSUE THREAD

**Issue by mickvangelderen** [phil-opp/blog_os#309]
After following http://os.phil-opp.com/multiboot-kernel.html I ran qemu and received the error `Boot failed: Could not read from CDROM (code 0009)`.

![image](https://cloud.githubusercontent.com/assets/5444990/24744963/21faf194-1ab4-11e7-90ee-047154291fcb.png)

Following the advice given on http://wiki.osdev.org/Bare_Bones solved this issue:

> ##### I get Boot failed: Could not read from CD-ROM (code 0009) when trying to boot the iso image in QEMU
> If your development system is booted from EFI it may be that you don't have the PC-BIOS version of the grub binaries installed anywhere. If you install them then grub-mkrescue will by default produce a hybrid ISO that will work in QEMU. On Ubuntu this can be achieved with: apt-get install grub-pc-bin.

The troubleshooting information given in the multiboot-kernel blog post suggests the following:

> If you’re using an EFI-system, grub-mkrescue tries to create an EFI image by default. You can either pass -d /usr/lib/grub/i386-pc to avoid EFI or install the mtools package to get a working EFI image

For me, `mtools` was already installed and `/usr/lib/grub/i386-pc` did not exist. Installing `apt install grub-pc-bin` created `/usr/lib/grub/i386-pc`.

**Comment by phil-opp** [comment]
Thanks a lot for reporting this problem and your solution in so much detail! There are lots of problems around GRUB so I think it might be a good idea to create a separate “known problems” / “troubleshooting” site. This would fit really well there.

**Comment by callodacity** [comment]
FWIW I was getting `Boot failed: Could not read from CD-ROM (code 0004)` and running `apt-get install grub-pc-bin` worked for me :+1:

**Comment by lilijreey** [comment]
my ubuntu 16.04 can not install grub-pc-bin

The following packages have unmet dependencies:
 grub-pc-bin : Depends: grub-common (= 2.02~beta2-36)
E: Unable to correct problems, you have held broken packages.

**Comment by hausdorff** [comment]
I also go the `code 0004` issue, and resolved it by building the ISO in a container: https://github.com/hausdorff/blog_os/commit/3317681c6f1123136fc6f3f72a8907f7466b52a5

**Comment by MikuGhoul** [comment]
I sloved this problem.

Try to change you **ISO** file permission to `rwxrw-rw-`

Especially the `x` perminission. So the BIOS can find and read the file.

**Comment by phil-opp** [comment]
Closing since it only affects the first edition, which is no longer maintained.

**Comment by chinesefod** [comment]
THANKS
