### ISSUE TITLE
Double Faults before Handling Exceptions in bottom navigation

### ISSUE THREAD

**Issue by kyrias** [phil-opp/blog_os#315]
For the previous/next post links under the posts themselves, Double Faults shows up before Handling Exceptions

**Comment by bjorn3** [comment]
Dup of #298

**Comment by kyrias** [comment]
Ah, completely missed that one, sorry.

**Comment by phil-opp** [comment]
No worries, thanks for reporting! Better to have an issue reported twice than never.
