### ISSUE TITLE
In "set up rust" xargo isn't building the project

### ISSUE THREAD

**Issue by pfgithub** [phil-opp/blog_os#321]
When using xargo to build, I get the same error as with cargo.

   ### cargo build --target x86_64-blog_os
    error: failed to run `rustc` to learn about target-specific information

    To learn more, run the command again with --verbose.

   ### xargo build --target x86_64-blog_os
    error: failed to run `rustc` to learn about target-specific information

    To learn more, run the command again with --verbose.

   ### xargo build --target x86_64-blog_os --verbose
    + "rustc" "--print" "sysroot"
    + "rustc" "--print" "target-list"
    + "cargo" "build" "--target" "x86_64-blog_os" "--verbose"
    error: failed to run `rustc` to learn about target-specific information

    Caused by:
      process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type staticlib --target x86_64-blog_os` (exit code: 101)
    --- stderr
    error: Error loading target specification: Could not find specification for target "x86_64-blog_os"
      |
      = help: Use `--print target-list` for a list of built-in targets

   ### xargo build --target x86_64-blog_os --verbose --print target-list
    + "rustc" "--print" "sysroot"
    + "rustc" "--print" "target-list"
    + "cargo" "build" "--target" "x86_64-blog_os" "--verbose" "--print" "target-list"
    error: Unknown flag: '--print'

    Usage:
        cargo build [options]

**Comment by phil-opp** [comment]
It seems like there is an error in the target specification. What's the output with `--verbose`?

**Comment by pfgithub** [comment]
Updated the comment with that

**Comment by phil-opp** [comment]
Thanks!

> error: Error loading target specification: Could not find specification for target "x86_64-blog_os"

The problem is that cargo can't find the `x86_64-blog_os.json` file. Maybe you forgot to create it or chose a different name?

**Comment by pfgithub** [comment]
Now a different error
    + "rustc" "--print" "sysroot"
    + "rustc" "--print" "target-list"
    + "cargo" "build" "--release" "--manifest-path" "/tmp/xargo.h3NNRHqRJ4IK/Cargo.toml" "--target"     "x86_64-blog_os" "-v" "-p" "core"
    error: failed to run `rustc` to learn about target-specific information

    Caused by:
      process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --sysroot /root/.xargo --crate-type bin --crate-type rlib --target x86_64-blog_os` (exit code: 101)
    --- stderr
    error: Error loading target specification: Field linker-flavor in target specification is required
      |
      = help: Use `--print target-list` for a list of built-in targets


    error: `"cargo" "build" "--release" "--manifest-path" "/tmp/xargo.h3NNRHqRJ4IK/Cargo.toml" "--target"     "x86_64-blog_os" "-v" "-p" "core"` failed with exit code: Some(101)
    note: run with `RUST_BACKTRACE=1` for a backtrace

**Comment by phil-opp** [comment]
Oh, I forgot to add the `linker-flavor` field in the post. Try to add `"linker-flavor": "gcc"` to the json file.

**Comment by phil-opp** [comment]
Fixed in 6ef85ecd697952994a2e4bca480acad91bcb4bc6

**Comment by pfgithub** [comment]
Fixed
