### ISSUE TITLE
Fix dead links

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#327]
There are various dead links across all posts (e.g. links to the rust book whose URL changed).

**Comment by 64** [comment]
Dead link report: (from http://www.deadlinkchecker.com/)

Error | URL | Anchor Text | Linked From
-- | -- | -- | --
404 | https://doc.rust-lang.org/book/lang-items.html | language item | https://os.phil-opp.com/set-up-rust/
404 | https://doc.rust-lang.org/nightly/libc/index.html | libc crate | https://os.phil-opp.com/set-up-rust/
404 | https://crates.io/crates/rlibc | rlibc | https://os.phil-opp.com/set-up-rust/
404 | https://crates.io/crates/spin | spin crate | https://os.phil-opp.com/printing-to-screen/
404 | http://rust-lang.github.io/book/ch18-00-patterns.html | destructuring | https://os.phil-opp.com/double-faults/
404 | https://docs.rs/x86/0.8.0/x86/shared/task/fn.load_tss.html | load_tss | https://os.phil-opp.com/double-faults/
404 | https://crates.io/crates/bit_field | bit_field | https://os.phil-opp.com/catching-exceptions/
404 | https://doc.rust-lang.org/book/inline-assembly.html | inline assembly | https://os.phil-opp.com/catching-exceptions/
404 | https://doc.rust-lang.org/nightly/book/inline-assembly.html | inline assembly | https://os.phil-opp.com/better-exception-messages/
404 | https://doc.rust-lang.org/nightly/core/num/trait.One.html | One | https://os.phil-opp.com/remap-the-kernel/
404 | https://doc.rust-lang.org/book/custom-allocators.html | the book | https://os.phil-opp.com/kernel-heap/
404 | https://crates.io/crates/once | once | https://os.phil-opp.com/kernel-heap/
404 | https://crates.io/crates/linked_list_allocator | linked_list_allocator | https://os.phil-opp.com/kernel-heap/
404 | http://phil-opp.github.io/linked_list_allocator/struct.Heap.html | Heap struct | https://os.phil-opp.com/kernel-heap/

**Comment by phil-opp** [comment]
Closing as stale (it's about the no longer maintained first edition).

**Comment by phil-opp** [comment]
Closing as stale. I created a new dead link issue at https://github.com/phil-opp/blog_os/issues/636
