### ISSUE TITLE
Double free of table frames in "Remap the Kernel" post

### ISSUE THREAD

**Issue by 4e554c4c** [phil-opp/blog_os#342]
When temporarily mapping an `InactivePageTable`, which occurs in both `ActivePageTable::with()` and `InactivePageTable::new()` the page table frame is duplicated and freed to an allocator even though it is owned by the `InactivePageTable`.  This only occurs because a clone in both places duplicates the frame.
In my kernel, I added a `TinyAllocator::flush()` method that flushes all frames to a closure. However, this doesn't consider the case where more than just the InactivePageTable frame was freed. Also it requires having the allocator be public. I would suggest having an `TemporaryPage::unmap_table_frame()` method that frees all frames to the TinyAllocator, except the one physical frame that is the page table.

**Comment by phil-opp** [comment]
Closed since it only affects the first edition, which is no longer maintained.
