### ISSUE TITLE
Unknown option -n

### ISSUE THREAD

**Issue by Unaimend** [phil-opp/blog_os#343]
When executing the line
ld -n -o kernel.bin -T linker.ld multiboot_header.o boot.o from your minimal x86 Kernel Tutorial I get the following error: ld: unknown option: -n
PS: I am on OSX

**Comment by 64** [comment]
You can't link elf64 executables using the default linker on OSX.

You'll need to cross compile binutils for x86_64-elf, I think.

**Comment by Unaimend** [comment]
Can you give me some information on how to do this, because I don't really know what you mean by "cross compile binutils for x86_64-elf"

**Comment by 4e554c4c** [comment]
@Unaimend See https://os.phil-opp.com/cross-compile-binutils/ for this blog's tutorial and http://wiki.osdev.org/GCC_Cross-Compiler for a more in-depth and general explaination.

**Comment by Unaimend** [comment]
Thank you very much

**Comment by 4e554c4c** [comment]
No problem. Please close this issue if it's solved.
