### ISSUE TITLE
Post 6: Error thrown by bitflags: No rules expected the token "flags"

### ISSUE THREAD

**Issue by too-r** [phil-opp/blog_os#344]
As above, when I try to compile the code from post 6, I get this error. I have `extern crate bitflags;` in my `src/lib.rs`, and the code I am using to define `EntryFlags` (in `src/memory/paging/entry.rs` is:
```rust
bitflags! {
    pub flags EntryFlags: u64 {
        const PRESENT = 1 << 0,
        const WRITABLE = 1 << 1,
        const USER_ACCESSIBLE = 1 << 2,
        const WRITE_THROUGH = 1 << 3,
        const NO_CACHE = 1 << 4,
        const ACCESSED = 1 << 5,
        const DIRTY = 1 << 6,
        const HUGE_PAGE = 1 << 7,
        const GLOBAL = 1 << 8,
        const NO_EXECUTE = 1 << 63,
    }
}
```
Could anyone shed any light on this matter?

**Comment by le-jzr** [comment]
There are actually two problems with the definition, both related to the fact that the blog post is outdated.

In recent versions of `bitflags`,
1. `struct` is used instead of `flags`
2. semicolons are used instead of commas

Here's fixed version:
```rust
bitflags! {
    pub struct EntryFlags: u64 {
        const PRESENT = 1 << 0;
        const WRITABLE = 1 << 1;
        const USER_ACCESSIBLE = 1 << 2;
        const WRITE_THROUGH = 1 << 3;
        const NO_CACHE = 1 << 4;
        const ACCESSED = 1 << 5;
        const DIRTY = 1 << 6;
        const HUGE_PAGE = 1 << 7;
        const GLOBAL = 1 << 8;
        const NO_EXECUTE = 1 << 63;
    }
}
```

**Comment by le-jzr** [comment]
As a side note, the code in the post would work just fine if you keep the dependency as `bitflags = "0.7.0"`.

**Comment by too-r** [comment]
that's fantastic, thank you for your help. I will close this now, hopefully the post can be updated to avoid future confusion
