### ISSUE TITLE
Unique::new now returns Option

### ISSUE THREAD

**Issue by crawfxrd** [phil-opp/blog_os#345]
Ref: rust-lang/rust/pull/42959

`Unique::new` was changed to return an `Option<Self>`.
`Unique::new_unchecked` offers the same behavior as the old `new`.

I am up to [Printing Characters](https://os.phil-opp.com/printing-to-screen/#printing-characters). `print_something` does not compile using rustc 1.21.0-nightly (52a330969 2017-07-27) due to this change.

**Comment by phil-opp** [comment]
Thanks for reporting! Yeah, we should change it to `new_unchecked` or maybe `new().unwrap()` to avoid the unsafety.

I'm on vacation until end of August, so I won't be able to fix this until then. However, I should be able to merge a pull request if someone wants to send one.
