### ISSUE TITLE
Set up rust

### ISSUE THREAD

**Issue by yarwelp** [phil-opp/blog_os#350]
The link for the "set up rust" article leads to a page not found error, both from the homepage and from the article that precedes it. Don't know if this is a mistake or if it's just that it hasn't been written yet.

**Comment by 4e554c4c** [comment]
Cannot reproduce

**Comment by le-jzr** [comment]
Me neither.
@yarwelp Can you provide more information? Exact links for the affected pages would be best.

**Comment by yarwelp** [comment]
Well it works now but I swear it was saying that the page could not be found yesterday.

The URL in question was https://os.phil-opp.com/set-up-rust/ and the links that I followed to get to it were from the pages https://os.phil-opp.com/entering-longmode/ and then https://os.phil-opp.com/ and I tried both multiple times without success yesterday, but as I said now it works.

Heisenbug?

**Comment by le-jzr** [comment]
*/shrug*
The web works in mysterious ways.
