### ISSUE TITLE
warning: unused extern crate

### ISSUE THREAD

**Issue by swarajd** [phil-opp/blog_os#351]
I am including the rlibc crate, but the compiler says the crate is unused:

![image](https://user-images.githubusercontent.com/1250084/30005863-d27206cc-90b9-11e7-9d08-5b52e502081a.png).

If I run the command `make run` again, it works fine (although still contains a warning):

![image](https://user-images.githubusercontent.com/1250084/30005922-f7041344-90ba-11e7-8ec0-9a5f6f97c2db.png)

However, without the crate, it errors saying memcpy is undefined. Is there a reason the compiler thinks this crate is unused?

![image](https://user-images.githubusercontent.com/1250084/30005869-e6607de4-90b9-11e7-8eef-d4e514e69a8e.png)

I have finished everything until the end of the "Set Up Rust" post.

**Comment by swarajd** [comment]
In addition I do run across this warning: `warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]` 

For reference the repository I am working with is here: https://github.com/swarajd/rust_kernel

**Comment by le-jzr** [comment]
The rlibc thing is normal. We need to include `rlibc` because it defines C functions that Rust needs, but it's not actually used in the visible Rust code, so the compiler doesn't know it's useful. Simply annotate the declaration like this:

```rust
#[allow(unused_extern_crates)]
extern crate rlibc;
```

That gets rid of the warning. (@phil-opp, perhaps mention this in the blog post?)

**Comment by le-jzr** [comment]
@swarajd, `warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]` is telling you that your kernel is trying to use a CPU feature that is not supported/enabled. You probably have a typo in a bitmask somewhere.

**Comment by andre-richter** [comment]
I also get that. I don't think it matters much though. Looks like its trying to use hardware virtualization features that arent there when using qemu.

probably something you have to explicitly turn off?

**Comment by swarajd** [comment]
Yeah I think that warning is probably safe to ignore. I don't really care enough to search for what exactly to turn off since it doesn't affect the functionality of the kernel in any way as far as I know. Thanks for the help @le-jzr @andre-richter !!

**Comment by le-jzr** [comment]
Oh, maybe it's the qemu itself that's trying to use the virtualization, and not the kernel. I'm thinking maybe you are using `-enable-kvm` with hardware that's too old to support it properly?

**Comment by andre-richter** [comment]
@le-jzr, I just looked this up. Actually, its the other way round.
It seems that `qemu-system-x86_64` by default tries to emulate a CPU model that has Intel Virtualization Extensions`VMX`. I am not sure if the emulated CPU model is a hardcoded one or it simply tries to mirror the host CPU (thats what I would suppose).
By default, though, QEMU uses the Tiny Code Generator (TCG) for emulating the CPU. But TCG can not emulate hardware virtualization extensions, thats where the warning comes from.

If your CPU is new enough to support nested VMX, though, the warning goes away if you use `-enable-kvm`. Nice side effect of using KVM: The kernel runs faster.

**Comment by le-jzr** [comment]
Interesting! Thanks for letting us know. :) (And sorry for my laziness and wrong answers.)
