### ISSUE TITLE
Add target-c-int-width in x86_64-blog_os.json

### ISSUE THREAD

**Issue by aoowweenn** [phil-opp/blog_os#353]
There was an error in [Travis-CI](https://travis-ci.org/phil-opp/blog_os)
>error: Error loading target specification: Field target-c-int-width in target specification is required

So I add "target-c-int-width" to the _x86_64-blog_os.json_ file
>{
  "llvm-target": "x86_64-unknown-none",
  "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
  "linker-flavor": "gcc",
  "target-endian": "little",
  "target-pointer-width": "64",
  "target-c-int-width": "32",
  "arch": "x86_64",
  "os": "none",
  "disable-redzone": true,
  "features": "-mmx,-sse,+soft-float"
}

I think the value is "32" which is the same in [other OS](https://github.com/rust-lang/rust/blob/master/src/librustc_back/target/x86_64_unknown_linux_gnu.rs)

**Comment by phil-opp** [comment]
Thanks for reporting! It seems like the field was introduced it this PR: https://github.com/rust-lang/rust/pull/44906

As far as I understand it, the field controls the size of the return type and the `argc` parameter used by the native `main` function, which is called from `libc`. We don't use `libc`, so the value of this field doesn't matter to us (but 32 is the right choice for most C calling conventions).
