### ISSUE TITLE
Use coralproject/talk for comments?

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#356]
We originally used [Disqus](https://disqus.com/) for comments, but abandoned it due to excessive tracking (see [[1]](https://notes.ayushsharma.in/2017/09/im-killing-disqus-comments-on-my-blog-heres-why) [[2]](http://donw.io/post/github-comments/)). We switched to a self-hosted [isso](https://posativ.org/isso/) instance, which works well but [does not support email notifications yet](https://github.com/posativ/isso/pull/50).

Now there is [coralproject/talk](https://github.com/coralproject/talk#talk-), a new commenting system sponsored by Mozilla which is used e.g. by the [Washington Post](https://www.washingtonpost.com/pr/wp/2017/09/06/the-washington-post-launches-talk-commenting-platform/). I think it's worth giving a try. Does anybody have experiences with it?

**Comment by phil-opp** [comment]
Interesting alternative: https://staticman.net/

**Comment by rybot666** [comment]
Sorry to bump this, but the blog is now based on utterances comments, so this probably needs closing

**Comment by phil-opp** [comment]
Thanks!
