### ISSUE TITLE
Why GDT first enter is 0?

### ISSUE THREAD

**Issue by lilijreey** [phil-opp/blog_os#358]
Hi phil, thank your  blog, It is the best book that  my have read. 

section .rodata
gdt64:
    dq 0 ; zero entry ; why need this line, can delete it ?
    dq (1<<43) | (1<<44) | (1<<47) | (1<<53) ; code segment

**Comment by le-jzr** [comment]
The first entry must always be zero. I think it's required by the architecture.

**Comment by 4e554c4c** [comment]
From the Intel manual:

> The first descriptor in the GDT is not used by the processor. A segment selector to this “null descriptor” does not generate an exception when loaded into a data-segment register (DS, ES, FS, or GS), but it always generates a general-protection exception (#GP) when an attempt is made to access memory using the descriptor. By initializing the segment registers with this segment selector, accidental reference to unused segment registers can be guaranteed to generate an exception.

The first descriptor isn't used(and isn't valid), so we just set it to zero. So you can't delete that line.
