### ISSUE TITLE
`next_table_address` doesn't always yield a canonical address - sign extension bug

### ISSUE THREAD

**Issue by IsaacWoods** [phil-opp/blog_os#362]
Firstly, thank you Phil for a great set of tutorials.

I've been trying to move the tutorial kernel into the higher-half, which has been interesting. In the `next_table_address` method of `Table`, we do something along the lines of:
```
let table_address = (self as *const _) as usize;
Some((table_address << 9) | (index << 12))
```
However, for some `table_address`s, this shift can mess up the sign extension required to make the address canonical, and so leads to General Protection Faults when trying to access the next page table.

I fixed this by manually re-extending the required bits:
```
let table_address = (self as *const _) as usize;
Some(((table_address << 9) | (index << 12)) | (0o177777_000_000_000_000_0000 * ((table_address>>47)&0b1)))
```

**Comment by kevinaboos** [comment]
I also experienced the same problem when moving my kernel to higher-half addresses. I did something similar to what you did; however, note that your solution is fine for higher-half addresses, but sign extension may not always be all 1s for the most significant bits.

**Comment by IsaacWoods** [comment]
Ohh, yeah I understand what I've done wrong. This should do a better job:
``` rust
let table_address = (self as *const _) as usize;
let sign_extension = 0o177777_000_000_000_000_0000 * ((table_address >> 47) & 0b1);
Some((((table_address << 9) | (index << 12)) & ((1 << 48) - 1)) | sign_extension)
```

**Comment by phil-opp** [comment]
Thanks for reporting this issue and sorry for the delay! We should absolutely fix this issue and I'm happy to merge a PR that does so.

**Comment by IsaacWoods** [comment]
Sure, I'll try to get a pull request submitted if nobody else is already working on this? (although it may not go as planned, never done one before :P)

**Comment by phil-opp** [comment]
Cool, thanks!
