### ISSUE TITLE
404 on several pages

### ISSUE THREAD

**Issue by koenw** [phil-opp/blog_os#365]
Since today, I'm receiving a 404 page on several blog pages, including https://os.phil-opp.com/set-up-rust/ and https://os.phil-opp.com/printing-to-screen/ (which is where https://os.phil-opp.com/ links to).

**Comment by phil-opp** [comment]
Strange.. Seems like this was an issue on netlify (our static site host). I triggered a redeploy and now it works again. Thanks for reporting!

**Comment by koenw** [comment]
Thanks, it works again :)
