### ISSUE TITLE
Set Up Rust, Xargo compiling issues

### ISSUE THREAD

**Issue by sumberg** [phil-opp/blog_os#379]
Hello! I'm quite new to OS programming, taking your tutorial together with a university course. You're explanations are fantastic, thanks a lot for your hard work!

I've run in to some issues with Cargo/Xargo in the Set Up Rust part of your tutorial. I've followed your instructions and installed Cargo, then Xargo, together with all of the small necessary bits and bobs. I'm now trying to run `xargo build --target=x86_64-blog_os`, but the compiling fails. This is the output when running the same command with `-v`:

```
> xargo build --target x86_64-blog_os -v
+ "rustc" "--print" "sysroot"
+ "rustc" "--print" "target-list"
+ "cargo" "build" "--release" "--manifest-path" "/tmp/xargo.UeQjJDzmdqr9/Cargo.toml" "--target" "x86_64-blog_os" "-v" "-p" "core"
   Compiling core v0.0.0 (file:///home/usr/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
     Running `rustc --crate-name core /home/usr/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=2574ddbde34f06b1 -C extra-filename=-2574ddbde34f06b1 --out-dir /tmp/xargo.UeQjJDzmdqr9/target/x86_64-blog_os/release/deps --target x86_64-blog_os -L dependency=/tmp/xargo.UeQjJDzmdqr9/target/x86_64-blog_os/release/deps -L dependency=/tmp/xargo.UeQjJDzmdqr9/target/release/deps --sysroot /home/usr/.xargo -Z force-unstable-if-unmarked`
error: Error loading target specification: Could not find specification for target "x86_64-blog_os"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Could not compile `core`.

Caused by:
  process didn't exit successfully: `rustc --crate-name core /home/usr/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C metadata=2574ddbde34f06b1 -C extra-filename=-2574ddbde34f06b1 --out-dir /tmp/xargo.UeQjJDzmdqr9/target/x86_64-blog_os/release/deps --target x86_64-blog_os -L dependency=/tmp/xargo.UeQjJDzmdqr9/target/x86_64-blog_os/release/deps -L dependency=/tmp/xargo.UeQjJDzmdqr9/target/release/deps --sysroot /home/usr/.xargo -Z force-unstable-if-unmarked` (exit code: 101)
error: `"cargo" "build" "--release" "--manifest-path" "/tmp/xargo.UeQjJDzmdqr9/Cargo.toml" "--target" "x86_64-blog_os" "-v" "-p" "core"` failed with exit code: Some(101)
note: run with `RUST_BACKTRACE=1` for a backtrace

```

The file JSON-file has the same name, as does the source file (`lib.rs`), and I've literally copied and pasted your code for the different necessary files.
I'm running Ubuntu 16.04 LTS EFI-booted on a Macbook Pro.

Any ideas?

Thanks!

**Comment by phil-opp** [comment]
> Hello! I'm quite new to OS programming, taking your tutorial together with a university course. You're explanations are fantastic, thanks a lot for your hard work!

Thanks a lot :). Which course is it?

The target json file needs to be in the same folder as the `Cargo.toml`, not in the `src` folder. Maybe that's the problem?

**Comment by light4** [comment]
Xargo with the latest nightly(2017-12-25) won't compile this project. Try to installed nightly-2017-11-29 (or other nightly versions).

**Comment by robert-w-gries** [comment]
japaric/xargo#186

**Comment by robert-w-gries** [comment]
[The root cause is described here, along with a workaround to the issue](https://github.com/japaric/xargo/issues/186#issuecomment-354008950)

**Comment by sumberg** [comment]
> Thanks a lot :). Which course is it?

It's a course on operating system basics at the Royal Institute of Technology in Stockholm :).


> The target json file needs to be in the same folder as the Cargo.toml, not in the src folder.


The files are both in the same folder.


> Try to installed nightly-2017-11-29 (or other nightly versions).

I tried running `rustup default nightly-2017-11-29` and `2017-12-24`, still getting the same error on both.


Maybe I'm not doing it right (as I said I'm fairly new to OS and Linux in general). I tried reinstalling Xargo by executing `cargo uninstall xargo` and reinstalling it. I'm not sure how to go about reinstalling Cargo, or Rust in general. Could you give any advice?

**Comment by robert-w-gries** [comment]
@sumberg Try `rustup override set nightly-2017-12-23` to force use the functional nightly.

When `xargo` fixes the issue, you can remove the override and go back to nightly rust by running

```
rustup override unset
rustup update
```

**Comment by sumberg** [comment]
@robert-w-gries 
Thanks, this seems to have worked! I'll make sure to remove the override once the issue is fixed.

Again, thanks for the help!

**Comment by phil-opp** [comment]
Let's keep this open, since the workaround is not yet included in the blog posts.
