### ISSUE TITLE
use of unstable library feature 'ptr_internals'

### ISSUE THREAD

**Issue by cmontella** [phil-opp/blog_os#384]
Using the latest nightly, we encounter the error:

```
use of unstable library feature 'ptr_internals': use NonNull instead and consider PhantomData<T> (if you also use #[may_dangle]), Send, and/or Sync (see issue #0)
```

Anywhere `Unique` is used. For example, in the VGA buffer and the page mapper. Users following along with the blog will encounter errors if they are just starting out.

This is related to https://github.com/phil-opp/linked-list-allocator/pull/9 and can probably be fixed in the same way.

**Comment by phil-opp** [comment]
Thanks for reporting. From a quick search it seems like we use Unique in the vga buffer driver and in the page table logic. I think it should be possible to replace these with `&'static mut`s, but I don't know when I will find some time to look into this.

I would be happy to merge a PR that either turns on the `ptr_internals` feature (to fix the build temporarily) or converts these `Unique`s to `&'static mut`, `NonNull`, or something else (the long term fix).

**Comment by phil-opp** [comment]
I think this is no longer relevant. I'm happy to reopen if this is still an issue.
