### ISSUE TITLE
BootInfo Not Found

### ISSUE THREAD

**Issue by flounders** [phil-opp/blog_os#388]
I'm really enjoying the second edition posts. While I was going through _A Minimal Rust Kernel_, one problem I ran into is the snippet for "Hello World!" and this line that causes errors:

`pub fn _start(boot_info: &'static mut BootInfo) -> ! {`

And this is the error:

```$ bootimage --target x86_64-blog_os
    Compiling blog_os v0.1.0 (file:///home/swilliams/workspace/learning/blog_os)
error[E0412]: cannot find type `BootInfo` in this scope
   --> src/main.rs:18:46
   |
18 | pub extern fn _start(boot_info: &'static mut BootInfo) -> ! {
   |                                              ^^^^^^^^ not found in this scope

error: aborting due to previous error

error: Could not compile `blog_os`.
```

At first I thought I missed something in the tutorial until the code snippet was the only instance of that variable, and then I checked the source code here, and found variable definition wasn't there. I don't know if you are planning on including that later, but it tripped me up for a few minutes.

**Comment by lachlansneff** [comment]
Ah, the BootInfo struct is in the os_bootinfo crate. You'll have to include that in your Cargo.toml file.

**Comment by phil-opp** [comment]
Thanks for reporting! I did indeed intend to introduce the `BootInfo` parameter in a later post.
