### ISSUE TITLE
Bootloader fails to load minimal kernel in release mode

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#409]
Reported by [Trinity on Twitter](https://twitter.com/FDB_hiroshima/status/972546013645934592).

The failure message "Failed to load the kernel" comes from the bootloader in real mode, so it seems like the issue is only related to file size.

**Comment by lachlansneff** [comment]
This has been happening periodically to with my os. As far as I can tell, it's dependent on file size, but not a maximum file size. Generally, if you remove a print or something along those lines, it'll work.

**Comment by phil-opp** [comment]
@fdb-hiroshima @lachlansneff I fixed some alignment problems in https://github.com/rust-osdev/bootloader/commit/2a36320dedf2a47e67943096620a565e3859fb6c, which solves the problem for me. Could you try if the newest bootloader version fixes it for you too? Just execute `cargo clean`, then the updated bootloader should be downloaded on the next build.
