### ISSUE TITLE
80x25 or 80x50?

### ISSUE THREAD

**Issue by sajattack** [phil-opp/blog_os#410]
In the "Minimal Rust Kernel" blog post you say "[The vga text buffer] normally consists of 50 lines that each contain 80 character cells." But in the "VGA Text Mode" blog post you say "The VGA text buffer is a two-dimensional array with typically 25 rows and 80 columns, which is directly rendered to the screen." Which is correct?

**Comment by phil-opp** [comment]
Thanks for reporting! 25 lines is the correct number.
