### ISSUE TITLE
Set Up Rust - Compiling Issue with rlibc

### ISSUE THREAD

**Issue by fabienpesquerel** [phil-opp/blog_os#414]
First I would like to thank you so much for your work since it is very helpful and allows beginner (like me) to be introduce to OS programming. I am currently following a course in the topics of OS and I have to write a mini OS as an assignment. I decided to do it using Rust since we had to write a compiler for a Rust fragment last semester. Before I go to do my own little OS I try to catch as many infos as I can and that's how I discovered your awesome work. So again thanks a lot !

*Here is my issue*. I am currently in the **Set Up Rust** and everything compile just fine up to the moment rlibc decides to get involved. I get this message : 
![err01](https://user-images.githubusercontent.com/34126914/37257176-c3af8fba-2565-11e8-85d8-d6adb139098a.png)

To be sure that I made no obvious mistakes, I downloaded and run your final version of the *set up rust* part and it seems that I get the same message : 
![err02](https://user-images.githubusercontent.com/34126914/37257191-f9c873aa-2565-11e8-8bba-c8a13827a639.png)

So I guess that I somewhat messed up somewhere but I really can't find where. If anyone can enlighten me, I would be so happy !

P.S. : while reading the *set up rust* part I remark that the Makefile changes when you introduce xargo : 
![xargo](https://user-images.githubusercontent.com/34126914/37257222-62f43bca-2566-11e8-9470-3a330bd2e570.png)

Above in this part, and instead of writing xargo, you create a kernel instruction in the makefile.

**Comment by stumpylog** [comment]
I'm also experiencing this issue while following along.  I wonder if xargo being in maintenance mode has anything to do with it?  Maybe a feature has changed that's needed?

`rustc 1.26.0-nightly (2789b067d 2018-03-06)`
`cargo 0.26.0-nightly (1d6dfea44 2018-01-26)`
`xargo 0.3.11`

**Comment by fabienpesquerel** [comment]
I am fairly new to Rust and OS programming and I think you might be right. But I don't know for you but it could be that newest version of *nightly* makes the bug.
See : https://github.com/phil-opp/blog_os/issues/379
It seems here that in order to make things work, one should override the version of **nightly** (2018-03-06) with nightly-2017-11-29.
However, I don't think that I know how to do that...

**Comment by fabienpesquerel** [comment]
I tried what is said in this issue but it only gets me : 
![err03](https://user-images.githubusercontent.com/34126914/37346482-b666553a-26cf-11e8-87ed-609efbcd2d63.png)

If anyone has an idea, I would be very thankful

**Comment by stumpylog** [comment]
@fabienpesquerel I'm assuming you ran `rustup override set nightly-2017-11-29`?  You'll need to do `rustup component add rust-src` to get the source.  But it runs into other issues, as least for me, where it appears the override didn't correctly take or download something?
```
Compiling core v0.0.0 (file:///home/user/.rustup/toolchains/nightly-2017-11-29-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
Finished release [optimized] target(s) in 16.91 secs
error: intermittent IO error while iterating directory `/home/user/.rustup/toolchains/nightly-2017-11-29-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin`
caused by: IO error for operation on /home/user/.rustup/toolchains/nightly-2017-11-29-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` for a backtrace
make: *** [Makefile:37: kernel] Error 1
```

The location it's looking for definitly doesn't exist for me.  Not sure if it's another component missing?

**Comment by phil-opp** [comment]
@fabienpesquerel is correct: It is a bug in rustc: https://github.com/rust-lang/cargo/issues/4905. To work around you can either by using an older nightly (see @stumpylog's [comment](https://github.com/phil-opp/blog_os/issues/414#issuecomment-372691415)) or set the `RUST_TARGET_PATH` environment variable to the current working directory when invoking `xargo`:

```
> RUST_TARGET_PATH=$(pwd) xargo build --target […]
```

You can also update your Makefile:

```diff
 cargo:
-	@xargo build --target $(target)
+	@RUST_TARGET_PATH="$(pwd)" xargo build --target $(target)
```

**Comment by phil-opp** [comment]
> But it runs into other issues, as least for me, where it appears the override didn't correctly take or download something?

The newest version of `xargo` only works on recent nightlies. The error you're seeing comes from https://github.com/japaric/xargo/pull/200, where the new `bin` directory (added in newer compilers) is copied to the target sysroot. So either use a recent nightly with the `RUST_TARGET_PATH` workaround or downgrade `xargo` to version `0.3.10`.

**Comment by phil-opp** [comment]
@fabienpesquerel 

> First I would like to thank you so much for your work since it is very helpful and allows beginner (like me) to be introduce to OS programming. I am currently following a course in the topics of OS and I have to write a mini OS as an assignment. I decided to do it using Rust since we had to write a compiler for a Rust fragment last semester. Before I go to do my own little OS I try to catch as many infos as I can and that's how I discovered your awesome work. So again thanks a lot !

Awesome! Really cool that you decided to use Rust! Feel free to ask questions here or in our [gitter channel](https://gitter.im/phil-opp/blog_os).

**Comment by phil-opp** [comment]
I added the `RUST_TARGET_PATH` workaround to the post: https://github.com/phil-opp/blog_os/pull/416

**Comment by fabienpesquerel** [comment]
Ok, thanks you very much, everything seems to work again ! (except that I have to do the `RUST_TARGET_PATH=$PATH xargo build --target=x86_64...` via command line and that it won't work in the Makefile, even if I do an `export RUST_TARGET_PATH=$PATH` beforehand)

**Comment by phil-opp** [comment]
It should be `$(pwd)`, not `$PATH`.

**Comment by fabienpesquerel** [comment]
Yes, sorry for the typo. I don't know why, but `$(pwd)` didn't work. However double-dollar `$$PWD` makes it just fine in the Makefile.

**Comment by phil-opp** [comment]
I don't know about `$$PWD`, but `$(shell pwd)` and `$(CURDIR)` should also work. I updated the Makefile in the post to `$(shell pwd)` too: https://github.com/phil-opp/blog_os/commit/8d312293b175a47b82e3b06d623dab626cd3f19a. Seems like we can close this issue then. Thanks a lot for your help!
