### ISSUE TITLE
A Minimal Rust Kernel - getting 'Failed to load kernel' error on trying to boot with qemu.

### ISSUE THREAD

**Issue by akritrime** [phil-opp/blog_os#418]
I am just a beginner, both to Rust and OS dev. And first of all, I really appreciate the blog posts, the writing style really makes it a breeze to learn. Now, my issue.

I am unable to boot the kernel using qemu. The only difference in the code is an extra newline in the unsafe block. Both compiles, however, if there's a newline inside the unsafe block, the kernel fails to load.
```rust
unsafe {
        *vga_buffer.offset(i as isize * 2) = byte;
        *vga_buffer.offset(i as isize * 2 + 1) = 0xb;

}
```
![selection_083](https://user-images.githubusercontent.com/32516978/37405514-d5c78e30-27ba-11e8-9134-525bc9139252.png)

**Comment by phil-opp** [comment]
That's really strange. A newline shouldn't affect compilation at all, so I have no idea how it leads to different results on loading. Might be related to #409. Thanks for reporting @akritrime!

**Comment by akritrime** [comment]
@phil-opp I did a rust update and seems like that fixed it. Should I close this issue?

**Comment by phil-opp** [comment]
I'm pretty sure that is has the same underlying issue as #409, so I think we can close this if it is no longer reproducible. Thanks again!
