### ISSUE TITLE
What it the name of the OS you are talking about on this blog?

### ISSUE THREAD

**Issue by getreu** [phil-opp/blog_os#419]
I came to your blog by accident, stayed there for a minute or so and it is still not clear to me about what OS your are talking about! Any links to the project page, documentation, downloads?

**Comment by phil-opp** [comment]
The plan is to write our own OS. The blog provides step-by-step tutorials for doing so.

**Comment by phil-opp** [comment]
I hope that I could answer your question. If not, I'm happy to reopen this issue!

**Comment by getreu** [comment]
Yes, thank you. Maybe you want to give it a name and mention "The plan is to write our own OS. The blog provides step-by-step tutorials for doing so." on your website?

**Comment by phase** [comment]
well it states

> This blog series creates a small operating system in the Rust programming language. Each post is a small tutorial and includes all needed code, so you can follow along if you like.

**Comment by getreu** [comment]
Thank you, I am very interested in you project and will follow it closely.
