### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by jendrikw** [phil-opp/blog_os#422]
Thank you very much for all of you work!

I'm currently working through the first series and have just implemented the vga buffer abstraction. I would like to write tests for it, but `cargo test` complians with

```
error: cannot produce bin for `os v0.1.0 (file:///home/jendrik/dev/rust/os)` as the target `x86_64-blog_os` does not support these crate types
```

I tried adding `"executable": true` to the target json file, but that didn't work. How can I tell xargo how to compile binaries?

**Comment by phil-opp** [comment]
Using `cargo test` for the VGA buffer is a very good idea. Maybe I'll write a blog post about it.

> I tried adding "executable": true to the target json file, but that didn't work.

You just made a typo. It needs to be "executable**s**": true (plural). No idea why rust doesn't error for misspelled fields.

**Comment by phil-opp** [comment]
I think this can be closed, given that there is now a dedicated post about unit testing.
