### ISSUE TITLE
How to go about deleting only one character?

### ISSUE THREAD

**Issue by just-a-martian** [phil-opp/blog_os#430]
This is more of a question than anything else. 

I used your wonderful guide (first edition) to design the groundwork for [my OS](https://github.com/just-a-martian/Project-Longhorn) and I wanted to make a basic shell. To do this, I would have to have backspace functionality (I already have interrupts and that jazz setup). So, I ask, how would I delete the previous character?

For example,

    Hello, World!!(hangs here at the end (this is not printed))

How could I delete that last ! in Hello, World!!?

Thanks!

**Comment by phil-opp** [comment]
Hi! Your project looks already pretty advanced, really cool!

To delete a character, you could overwrite the character with a space character (like we do on a newline) and reset the cursor to the previous position.

**Comment by just-a-martian** [comment]
Alright! Thanks a lot! :)
