### ISSUE TITLE
Rename panic_implementation attribute to panic_handler

### ISSUE THREAD

**Issue by TuringDisciple** [phil-opp/blog_os#465]
The panic_implementation attribute has been deprecated for [RFC 2070](https://github.com/rust-lang/rust/issues/44489#issuecomment-416645946) and renamed to [panic_handler](https://github.com/rust-lang/rust/issues/44489#issuecomment-415140224)

**Comment by Ben-PH** [comment]
Forking now. I ran into this and didn't think to put the issue up. I'm getting a lot of value out of this, will feel good to contribute.

**Comment by Ben-PH** [comment]
found the commit in the rust repo

[deprecating panic_implementation](https://github.com/rust-lang/rust/tree/master/src/test/ui/panic-implementation)

**Comment by phil-opp** [comment]
Fixed in #467. Thanks for reporting @TuringDisciple!
