### ISSUE TITLE
First printing of stack frame differs between mine and example.

### ISSUE THREAD

**Issue by Ben-PH** [phil-opp/blog_os#466]
Awesome blog posts, BTW. Learning a lot.

the example that I am referring to is [this image](https://os.phil-opp.com/cpu-exceptions/qemu-breakpoint-exception.png/) found towards the bottom of [this post](https://os.phil-opp.com/cpu-exceptions/)

The output that I get is the image below
![s_frame](https://user-images.githubusercontent.com/16680090/46139716-9f64d780-c292-11e8-8a4f-d4e59cda5d8b.png)

Notice how mine doesn't new-line?
It looks like the same happens for both `serial_println!` and `println!` when i print the stack frame.
I ran the `serial_println!` to a txt file: 
[s_frame.txt](https://github.com/phil-opp/blog_os/files/2423694/s_frame.txt)

[Here](https://github.com/Ben-PH/tetanus/tree/cecb4f47d5e59e65080493076749e274c605217b) is a link to a commit that exhibits the behaviour.

**Comment by phil-opp** [comment]
The difference is that I'm using pretty-printed debug output with `{:#?}` instead of normal debug output with `{:?}`. See the [fmt::Debug docs](https://doc.rust-lang.org/std/fmt/trait.Debug.html) for more info.

**Comment by Ben-PH** [comment]
Thank you so much.

In such an unfamiliar environment, the simple things escape me. I'm still pretty naive when it comes to this sort of work.
