### ISSUE TITLE
Kernel mapping failed: PageAlreadyMapped

### ISSUE THREAD

**Issue by TsubameDono** [phil-opp/blog_os#469]
Good day, everyone !

So I have just started in kernel programming and find this interesting website (https://os.phil-opp.com/minimal-rust-kernel/).
I followed meticulously this first step "minimal-rust-kernel" (Second Edition).
Everything compiled well, but when I run (using `qemu` or `bootimage run`) I receive the following error:
```sh
panicked at 'kernel mapping failed: PageAlreadyMapped', /home/philipp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:945:5
```
So first of all, I am not 'philipp'.
I compile this project on a ``Window 10 (x64)``.
I am using ``nightly-x86_64-pc-windows-msvc`` toolchain  with the version `1.31.0-nightly (5597ee8a6 2018-10-03)`
My "main.rs" is:
```rust
#![no_std] // don't link the Rust standard library
#![no_main] // disable all Rust-level entry points

extern crate bootloader_precompiled;

use core::panic::PanicInfo;

/// This function is called on panic.
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}

// On Windows:
#[no_mangle]
pub extern "C" fn mainCRTStartup() -> ! {
    main();
}

#[no_mangle]
pub extern "C" fn main() -> ! {
    loop {}
}
```

I am using the same `x86_64-blog_os.json` file as shown in the post.
I also use the `bootloader_precompiled = "0.2.0"` as shown in the post.
And the crate `bootimage = ^0.5.0` not as a dependency.

Is this because of my Rust version or Windows?
Could someone can help understand what I am doing wrong? 

Thanks you for your time.

**Comment by TsubameDono** [comment]
Me, again.
My bad, I find my error. I have confused the `main.rs` file from the previous tutorial and the second one.

```rust
#[no_mangle]
pub extern "C" fn _start() -> ! {
    loop {}
}```

**Comment by phil-opp** [comment]
Thanks for the update!
