### ISSUE TITLE
Transition the code to Rust 2018

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#500]
Rust 2018 is about to be released and it's already the default for new crates on nightly. So we should update this crate and the blog posts to the 2018 edition of Rust.

After transitioning:

- [ ] Use `#![cfg_attr(not(test), no_std)]` instead of `#[cfg(test)] extern crate std` as proposed [here](https://github.com/phil-opp/blog_os/issues/429#issuecomment-437750231).

**Comment by kballard** [comment]
With Rust 2015, you can use `#![cfg_attr(not(test), no_std)]` just by adding

```rust
#[cfg(test)]
extern crate core;
```

I took my copy of the source, removed the 2018 edition, and added that one snippet (to `lib.rs` and to `bin/test-exception-double-fault-stack-overflow.rs`) and it compiled.

**Comment by phil-opp** [comment]
Yeah, but this wouldn't really be an improvement over the current situation (`#[cfg(test)] extern crate std` and unconditional `#![no_std]`).
