### ISSUE TITLE
Testing memory causes crash (first-edition/posts/02-entering-longmode/) 

### ISSUE THREAD

**Issue by blackdogbro** [phil-opp/blog_os#505]

**Comment by phil-opp** [comment]
In the "Entering Long Mode" post we map the first gigabyte of memory in the page table, so this should not cause the crash. Are you running your code in QEMU or another virtual machine? Or are you running it on real hardware?

The problem might be that you've not given the virtual machine enough memory. Or it could be that the memory region below 1 gigabyte is reserved by the hardware and must not be accessed (there are various reserved memory regions on every computer). See https://os.phil-opp.com/allocating-frames/#available-memory for more information.

**Comment by phil-opp** [comment]
Closing as stale. It only affects the first edition, which is no longer maintained.
