### ISSUE TITLE
Request for translating into Chinese

### ISSUE THREAD

**Issue by luojia65** [phil-opp/blog_os#507]
Dear @phil-opp,
Hello! 
I'm Luo Jia, a blog author on Rust programming from China. I'm here writing to ask for a permission to translate and repost your article *Writing an OS in Rust (Second Edition)*.
Your nice article has benefited me a lot, and is worth being known by a wide range of readers. What I want to do is to translate the whole series of articles into Chinese and post them onto my blog and special columns(of course with credits, origin authors, licenses, github address and origin article links).  I will spare no effort to polish my words and sentences, to meet up with the origin idea of the article, as well as meet up with the appetite of Chinese readers who wish to read pieces of wonderful article on Rust OS developing in our native language.
If permitted, I will be more than glad. 
Yours, 
Luo Jia (洛佳)
![default](https://user-images.githubusercontent.com/40385009/50377105-3ce16480-0652-11e9-8659-678f576d26ff.png)

**Comment by phil-opp** [comment]
Hi @luojia65! Thanks for the kind words :).

Translations are fine with me. It's great that the content of this blog will be available to more readers. Thanks for asking for permission!

**Comment by luojia65** [comment]
Thank you for your approval @phil-opp :) 
I've done one chapter today in my github repo http://github.com/luojia65/writing-an-os-in-rust

**Comment by phil-opp** [comment]
Nice! Let me know if you have any questions!
