### ISSUE TITLE
Nit: foo.rs allows foo/*.rs submodules

### ISSUE THREAD

**Issue by dato** [phil-opp/blog_os#525]
In the _VGA Text Mode_, it [says](https://github.com/phil-opp/blog_os/blob/4a257c6/blog/content/second-edition/posts/03-vga-text-buffer/index.md) (emphasis mine):

>The content of this module can live either in `src/vga_buffer.rs` or `src/vga_buffer/mod.rs`. **The latter supports submodules while the former does not.**

As I understand it, this is no longer true in edition 2018, so I think it’d make sense to drop the comment, either now or at some point in the future.

Thanks for considering.

**Comment by phil-opp** [comment]
Thanks for the suggestion! I updated the text in f03463b.
