### ISSUE TITLE
Maybe call HLT on → ! to save battery?

### ISSUE THREAD

**Issue by dato** [phil-opp/blog_os#528]
Hi—

I’m not sure whether this makes sense here, but whenever I’ve done OS development with QEMU in the past, I’ve _always_ ended up adding a `HLT` instruction at the end of `_start` and `panic`. 

I often forget QEMU’s window open, and it’s annoying to realize after a few minutes that my CPU is at 100%.

Perhaps it can be offered as a tip, and not necessarily included in the source.

Just my 2¢, feel free to close at will. :)

**Comment by phil-opp** [comment]
We do this in the [_Hardware Interrupts_](https://os.phil-opp.com/hardware-interrupts/#the) post. It's a bit late, but I think it makes sense to introduce in there since `HLT` waits until the next interrupt arrives.

**Comment by dato** [comment]
Aaah, makes sense. Thank you and sorry for the noise.

**Comment by phil-opp** [comment]
No worries, thank you for the suggestion :).

**Comment by correabuscar** [comment]
My mistake, I typoed the modded `dd` image so it was using an old one when creating the resulting .vdi, hence it was still using the loop without the hlt! 
So it does work!

Even simplified it to work without the x86_64 crate at this stage, by just using `asm!` directly:
```rust
use core::arch::asm;
...
    loop {
          unsafe {
              asm!("hlt", options(nomem, nostack, preserves_flags));
          }
      }
```

**Comment by correabuscar** [comment]
I'd say do it early anyway, for climate-change reasons, if nothing else :) Hey, you can say you did your part, or at least, you didn't make it worse. Think of all the power you'd be saving, by not having the CPU pinned to 100% (one core at full) for even 5 seconds if not more(depending how long the user will decide to look at it), if 10k people try blog_os.

I think it's harmless enough to include the `asm!` macro (with the `use`) in both panic and _start loops, somewhere as early as in https://os.phil-opp.com/minimal-rust-kernel/

Anyway, I'm not going to push it. It did matter to me(and OP?) enough that I stopped progressing until I got it working. Now it feels good, and I can continue with pride xD
