### ISSUE TITLE
might be good to remind users to override rust to nightly

### ISSUE THREAD

**Issue by lbrindze** [phil-opp/blog_os#53]
in ubuntu 14.04 after installing multirust and running the command `multirust update nightly` I ran into the following error: 
```
 #[feature] may not be used on the stable release channel
``` 
which suggested I was still using stable. running `multirust override nightly` did the trick, may be worth throwing into your document for other newbie readers such as myself.

Thanks for making a really excellent tutorial by the way!

**Comment by phil-opp** [comment]
Thanks for the hint!
