### ISSUE TITLE
Build fails with latest nightly: rustc 1.34.0-nightly (4b1e39b7b 2019-02-05)

### ISSUE THREAD

**Issue by gmadrid** [phil-opp/blog_os#549]
$ rustc --version
rustc 1.34.0-nightly (4b1e39b7b 2019-02-05)
$ git clone https://github.com/phil-opp/blog_os.git
$ git co -b post-01
$ bootimage run 

error[E0432]: unresolved import `if_arc`
 --> /Users/gmadrid/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/task.rs:6:9
  |
6 | pub use if_arc::*;
  |         ^^^^^^ did you mean `self::if_arc`?

error[E0432]: unresolved import `SearchResult`
 --> /Users/gmadrid/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/collections/btree/search.rs:6:5
  |
6 | use SearchResult::*;
  |     ^^^^^^^^^^^^ did you mean `self::SearchResult`?

error[E0432]: unresolved import `UnderflowResult`
  --> /Users/gmadrid/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/collections/btree/map.rs:14:5
   |
14 | use UnderflowResult::*;
   |     ^^^^^^^^^^^^^^^ did you mean `self::UnderflowResult`?

....and many more.

**Comment by phil-opp** [comment]
Have you tried updating to the latest cargo-xbuild? There was some recent breakage in how liballoc is built (2018 edition).

Also, the post-01 branch contains the state after the first post, but bootimage is only introduced in the second post.

**Comment by gmadrid** [comment]
Sorry about this bug. nightly breakage isn't really your problem. :) It was
late, and I was loving your blog, and I was really annoyed that updating
rust made me stop following along. Not your fault. Thanks for offering some
help anyway.

I worked around this by installing an old nightly image and using that
toolchain instead.

Like I said, I'm loving your blog. You're covering low-level nitty-gritties
that I've never been exposed to before, and I've been doing this coding
thing for 30 years.

Cheers,

George

**Comment by phil-opp** [comment]
It's all good, thank you for filing this bug! I always want the blog to work with the latest nightly.

I think the problem is that `cargo-xbuild` needed an update to work with the latest nightly. Version 0.5.5 should work with the current nightly. At least the CI builds which run every night with the latest nightly [are all green](https://dev.azure.com/phil-opp/blog_os/_build/results?buildId=44).

Can you try `cargo xbuild --version` and see if you're still on an older version? To update `cargo-xbuild` run `cargo install cargo-xbuild --force`.

> Like I said, I'm loving your blog. You're covering low-level nitty-gritties that I've never been exposed to before, and I've been doing this coding thing for 30 years.

I'm glad you like it :)

**Comment by gmadrid** [comment]
Broken version:

Georges-MacBook-Air:blog_os gmadrid$ cargo xbuild --version
cargo-xbuild 0.5.4


After forcing the upgrade:

Georges-MacBook-Air:blog_os gmadrid$ cargo xbuild --version
cargo-xbuild 0.5.5

And, you called it. It works now.

So, is there an easy way to know if those cargo installs need to be
updated?

Thanks for your help with this.

George

**Comment by phil-opp** [comment]
Perfect, thanks for testing!

> So, is there an easy way to know if those cargo installs need to be updated?

There are tools like [`cargo-update`](https://github.com/nabijaczleweli/cargo-update) or [`cargo-update-installed`](https://github.com/phil-opp/cargo-update-installed) that update all tools installed through `cargo install` to their latest versions.

The former is the de facto standard. It is installed through `cargo install cargo-update` and invoked through `cargo install-update -a`. The latter is a lightweight (i.e. less dependencies) alternative that I mostly use for CI. It is installed through `carog install cargo-update-installed` and invoked through `cargo update-installed`.

**Comment by gmadrid** [comment]
Thanks for the help.

-g
