### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#55]
Some Mac OS users seem to have tool problems in the first post. So it might be a good idea to create a separate page that lists all needed extra steps (such as updating `nasm`). 

Unfortunately, I have zero Mac experience and can only copy instructions from the post's comments. So if someone got it working, I would really appreciate a list of required commands!

**Comment by sptramer** [comment]
Here's what I did to get up and running on OS X:

* Install Xcode 7.1.1 and Command Line Tools (`xcode-select --install` once Xcode is installed)
* Install rust (latest stable? Not quite at the point where features from Nightly might be getting used)
* Install homebrew: http://brew.sh/
* Install latest nasm: `brew install nasm`
* Install GCC: `brew install gcc` -- this is only necessary for the binutils compilation, and if you want, you can nuke GCC afterwards.
* Cross-compile binutils: Just follow the handy instructions provided by you -- although I used `/usr/local` as the prefix install point just for ease of use.

**Comment by sptramer** [comment]
Note on the binutils cross-compile -- looks like it builds into `/usr/local/x86_64-elf/` (a change with binutils 2.26.51?) and no longer prefixes the commands automatically. Instead it looks like `--program-prefix` does the name prefixing.

**Comment by phil-opp** [comment]
Thank you very much! I hope I find some time to create a first draft soon.

**Comment by sptramer** [comment]
No problem. There's still one missing piece, which is building the GRUB toolchain. For now there is an (outdated; sketchy?) homebrew tap that can be used, found by a commenter on the blog post:

http://os.phil-opp.com/multiboot-kernel.html#comment-2374018414

Others have said that the OSDev wiki grub building instructions worked:

http://wiki.osdev.org/GRUB_2#Installing_GRUB2_on_Mac_OS_X

**Comment by jcaudle** [comment]
Do you think you'd prefer a list of commands or a PR with how someone could get things set up on a Mac? I was planning on adding a `README` to my own implementation of the OS, but if you need a writer for the page, I'd be happy to put something together when I get the chance to write out what I did to get things going on my own Mac.

**Comment by phil-opp** [comment]
@jcaudle That would be really awesome!

**Comment by jcaudle** [comment]
@sptramer have you been able to link the rust code into your kernel as described in the [Setup Rust post](http://os.phil-opp.com/setup-rust.html)? I've been running into a problem where I need to run `ranlib`, which then doesn't properly add the symbol for `rust_main` (I think...). If you've gotten past that, I'd be much more able to write something up for future OS builders! :smile:

**Comment by sptramer** [comment]
@jcaudle Not yet - I'm still setting up the cross-compilers correctly. It looks like I goofed on the i386 binutils above by putting them in `/usr/local` -- cross-compiling GCC against these binutils, even setting CC/CXX/CPP/LD to the correct installed gcc version seems to force it to link against the clang assembler, which screws everything up.

I just installed rust from the `.pkg` distribution they offered. If it turns out that's not quite enough, I'll look into it when I reach that point.

**Comment by sptramer** [comment]
Here's how I was able to eventually get a grub build working:
* When cross-compiling `i386` binutils, make sure that they go into a non-standard location. I used `--prefix=/opt/i386-toolchain`. The full command line that worked for me was: `CC=gcc-5 CXX=g++-5 CPP=cpp-5 LD=gcc-5 ../binutils-2.26.51/configure --target=i386-elf --prefix=/opt/i386-toolchain --disable-nls --disable-werror --disable-gdb --disable-libdecnumber --disable-readline --disable-sim`
* In addition to cross-compiling i386 binutils, you need an i386 GCC for grub: `CC=gcc-5 CXX=g++-5 CPP=cpp-5 LD=gcc-5 ../gcc-5.2.0/configure --target=i386-elf --disable-nls --enable-languages=c,c++ --without-headers --prefix=/opt/i386-toolchain`.
* Build `objconv` for the host architecture, meaning that you can just use `gcc-5` as the compiler invoke.
* Configure grub to use the cross-compiled tools and also the host GCC toolchain: `CC=gcc-5 CXX=g++-5 CPP=gcc-5 LD=gcc-5 ../grub/configure --disable-werror TARGET_CC=i386-elf-gcc TARGET_STRIP=i386-elf-strip TARGET_NM=i386-elf-nm TARGET_RANLIB=i386-elf-ranlib --target=i386-elf --prefix=/opt/i386-toolchain`
* *NOTE:* You may need to upgrade flex for building grub. You want to `brew install flex` and then `brew link --force flex` so it replaces the system `flex`. Then `brew unlink flex` to clean it up when you're done.

Other brew formulas you'll probably need are `qemu` and `xorriso`. At this point I had the bootloader working and showing `OK` from `make run`.

**Comment by sptramer** [comment]
Well, get ready for the bad news on cross-compiling a bare metal capable rust libcore on OS X:

https://github.com/rust-lang/rust/issues/16259

Seems like the rust team doesn't have the bandwidth to resolve the issue at this time. Cross-compiler support for rust in general seems pretty back-burner, but Darwin -> i686/x86_64 seems like an especially low priority because how how screwed up Apple's linker is.

**Comment by phil-opp** [comment]
This seems to be much more complicated than I thought… Maybe it's easier to use a virtual Linux machine. For example, see [Lifepillar's comment](http://os.phil-opp.com/multiboot-kernel.html#comment-2382552717).

Ashley Williams's [x86-kernel repository](https://github.com/ashleygwilliams/x86-kernel) contains a Vagrantfile that should make it easy to get a working virtual environment. There are some instructions in the readme, too.

**Comment by jcaudle** [comment]
Good call on suggesting the use of vagrant. After the find by @sptramer, I was going to switch to setting up vagrant myself.

**Comment by steveklabnik** [comment]
cc @ashleygwilliams, who was mentioned upthread but not in a way that would ping her :)

**Comment by ashleygwilliams** [comment]
hey @phil-opp would you be interested in a PR with the vagrantfile and the mac docs? i'd me more than happy to contribute

**Comment by phil-opp** [comment]
That would be awesome!

**Comment by emkay** [comment]
FWIW I have a script that is working for me to build the  cross compiler tools and compile `grub` on OSX.

https://gist.github.com/emkay/a1214c753e8c975d95b4

**Comment by jcaudle** [comment]
@emkay nice work on the script. I'm curious what you do when you start using rust itself as that's where I decided to look into using a VM.

**Comment by phil-opp** [comment]
@emkay this looks pretty great! 

@jcaudle the problem with rust was related to cross-compiling libcore, wasn't it?

**Comment by jcaudle** [comment]
@phil-opp exactly. I basically shelved the project when I saw that, but have considered putting in the "heaps of work" necessary to getting it to work properly, I just haven't taken the time for it yet.

**Comment by phil-opp** [comment]
@jcaudle Maybe [nighly-libcore](https://github.com/phil-opp/nightly-libcore) with the following target json works:

```json
{
  "llvm-target": "x86_64-unknown-none-gnu",
  "target-endian": "little",
  "target-pointer-width": "64",
  "os": "none",
  "arch": "x86_64",
  "data-layout": "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128-n8:16:32:64-S128",
  "pre-link-args": [ "-m64" ],
  "cpu": "x86-64",
  "no-compiler-rt": true,
}
```

**Comment by emkay** [comment]
> @emkay nice work on the script. I'm curious what you do when you start using rust itself as that's where I decided to look into using a VM.

I haven't gotten to this point yet. I'm following along at [intermezzOS](http://intermezzos.github.io/) so will attempt to cross that bridge when we get there.

**Comment by n4matti** [comment]
> https://gist.github.com/emkay/a1214c753e8c975d95b4

Hi emkay, I tried your script, but it failed for me when it compiled libgcc with "make all-target-libgcc":


In file included from /Users/mathiasbauer/opt/arm-linux-gnueabihf/sys-include/pthread.h:21:0,
                 from ./gthr-default.h:35,
                 from ../../../gcc-5.3.0/libgcc/gthr.h:148,
                 from ../../../gcc-5.3.0/libgcc/libgcov-interface.c:27:
/Users/mathiasbauer/opt/arm-linux-gnueabihf/sys-include/features.h:361:25: fatal error: sys/cdefs.h: No such file or directory

"/Users/mathiasbauer/opt" is my $PREFIX
"sys/cdefs.h" is exactly where it should be, it's in $PREFIX/arm-linux-gnueabihf/sys-include/ and also in $PREFIX/include.
I'm using Yosemite, but I don't expect that this makes a big difference, as it's the cross-gcc that is used here.


Seems that something is missing or different at my system. Do you have an idea?

**Comment by Others** [comment]
I don't think that this is exactly what is being looked for here, but I have a Vagrantfile that works for this project, that I use to run it on macOS. I've put it in a gist [here](https://gist.github.com/Others/b21cfb18bc4925176ff21dcc61995ac4). To use it you just have to download it into the root directory of the project, and then run `vagrant up && vagrant ssh -- -Y`. Then once you're ssh'd in, you can cd to `/vagrant`, and run any command shown in the blog posts. (Obviously this whole process requires having vagrant installed.)

**Comment by Zynist** [comment]
After cross-compiling gcc and binutils, and building grub, I'm able to follow along the tutorial no problems. However, since qemu only supports kvm on Linux, and (as far as I can find) no other accelerators on macOS, I'm unable to do the advanced debugging linked in [better exception messages](http://os.phil-opp.com/better-exception-messages.html) by using `-enable-kvm`. There may be a way to get Qemu to use Intel's HAXM extension, with extra development.

For the meantime, I've created a VirtualBox machine (Type: Other, Version Other/Unknown 64-bit) that can boot the image and reproduce the triple fault expected in "Reproducing the bug in QEMU", but I haven't yet managed to attach a debugger to VirtualBox. This might be a usable alternative to qemu -enable-kvm for Mac users.

**Comment by steveklabnik** [comment]
We got a PR to intermezzos that might be helpful: https://github.com/intermezzOS/kernel/pull/101

**Comment by phil-opp** [comment]
That's great! Thanks for keeping me updated.

**Comment by berdon** [comment]
For anyone who wants to debug via MacOS/gdb, https://svbtle.com/vscode-gdb-and-debugging-an-os.

**Comment by gil0mendes** [comment]
@berdon That looks amazing, I'm using Radare2 at the moment. We can connect, for example, with QEMU using the following command:

```shell
r2 -d gdb://localhost:1234
```

**Comment by phil-opp** [comment]
The work on the second edition (which supports macOS natively) is making good progress, so I'm going to close this issue in favor of https://github.com/phil-opp/blog_os/issues/360.
