### ISSUE TITLE
Crate x86_64 has changed a lot

### ISSUE THREAD

**Issue by FirstLoveLife** [phil-opp/blog_os#556]
it is [0.5.0-alpha](https://docs.rs/x86_64/0.5.0-alpha.1/x86_64/) now, and removes structs like InterruptDescriptorTable struct, which is used in blog: https://os.phil-opp.com/cpu-exceptions/#an-idt-type

**Comment by phil-opp** [comment]
Thanks for opening this! It's a good idea to track the required changes for the upcoming `x86_64` version.

The `0.5.0-alpha` version is just an early pre-release for the upcomping `0.5.0` version and highly unstable (semver has no stability guarantees for pre-releases: https://semver.org/#spec-item-9), so it's not a good idea to use it in the blog yet. Also, the `InterruptDescriptorTable` struct [still exists](https://docs.rs/x86_64/0.5.0-alpha/x86_64/structures/idt/struct.InterruptDescriptorTable.html) in the alpha version.

**Comment by FirstLoveLife** [comment]
Good to know, thanks!
