### ISSUE TITLE
Calling low-level C function from Rust (How to use both of C and Rust together?) 

### ISSUE THREAD

**Issue by Dentrax** [phil-opp/blog_os#560]
**Warning:** This issue is not related to **blog_os** project.

I did a simple bootloader in assembly and simple `main()` in **C**. 

My `main.c` file:

```
#include <stdint.h>
#include <os/output.h>

int main()
{
  printf("Hello, World!\t");
  for(;;);
}
```

It is working currently. But I want to combine this code with Rust. That means: I want to use both of **C** and **Rust** together.

For **C**: I just wanna use little low-level operations like `scanf()` and `printf()`

For **Rust**: For all other things. 

For example, in this [lib.rs](https://github.com/phil-opp/blog_os/blob/first_edition_post_3/src/lib.rs) file, I want to call `printf()` from my own C file. How can i link my **C** calls to Rust? And how can I call **C** functions in Rust? Is it possible to link (ld) **gcc** and **cargo** outputs together?

**Note:** I am using GCC for compiling **.S** _(.asm)_ and **.c** files and using **ld** for linking both of **.o** and **.bin** files.

**P.S:** The main reason of making this is: Learn how to work actually C and Rust together.

Thanks in advance...

**Comment by phil-opp** [comment]
So I assume that you have defined your own `scanf`/`printf` functions? Because the default functions are [not available](https://wiki.osdev.org/Implications_of_writing_a_freestanding_C_project) in a freestanding environment.

For calling C from Rust and vice versa, the Rust book contains a [short overview](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#using-extern-functions-to-call-external-code). Linking works by compiling your C code to a static library and linking it with your Rust code (or the other way around). The Cargo documentation contains a case study that shows how to build and link C code [using a Cargo build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html#case-study-building-some-native-code).

I hope this helps!

**Comment by Dentrax** [comment]
@phil-opp 

Yes, i defined my own `scanf()`/`printf()` funcstions manually. And working well. Also thank you for your _freestanding_ document advise.

I read both documents. And I have a few questions that still I don't know how to do it.

1. In my `output.h`, i have a `printf()` function: `void printf(char *format, ...);` 
Should i need to implement to Rust like that?

```
extern "C" {
    fn printf(input: *char) -> void;
    fn scanf() -> string;
}
```

2. I still i don't know how to link together **GCC** and **cargo** builds. All of my kernel related **.c** files combines in a file that called **kernel.bin** (from **kernel.o**) Should the files I compiled with **cargo**, be in "kernel.bin"? (With other compiled **.c** files (**.o**))

3. I am calling that kernel main function (`void main()`) from bootloader. If I'm going to use it with Rust, will i have to call Rust's `main()` first?

**Comment by phil-opp** [comment]
You can either link your C code into Rust or your Rust code into C. For doing the latter the best approach is to build a static library by adding the following to your Cargo.toml:

```toml
[lib]
crate-type = ["staticlib"]
```

You need to rename your `main.rs` to `lib.rs` then because you're creating a static _libary_ now. This will result in an `.a` file, which you can link together with your `.o` files.

**Comment by Dentrax** [comment]
@phil-opp Thank you, but how do I call to the `printf()` function from Rust if I link Rust code into C? Because I already coded the printf() function in C. That means `main` in C too. In that case, shouldn't I do the first thing you say?

When I call `printf()` from Rust; **Rust > C > Assembly** (The call order should be like this)

**Comment by phil-opp** [comment]
You define it in an `extern "C"` block in Rust like you wrote above. This works for both approaches (linking C code to your Rust binary and linking Rust code to your C binary). It is the Rust equivalent of a header file, so it will just let the linker figure out which function to link.

**Comment by Dentrax** [comment]
@phil-opp  For the **cargo** build documentation you mentioned in your first comment, the second example uses [cc-rs](https://crates.io/crates/cc) package for cross compiling stuff. Is it ok to use `cc-rs` in my own kernel? And also you used `xargo` package in your [Makefile](https://github.com/phil-opp/blog_os/blob/first_edition_post_3/Makefile) to compiling and linking objects. So, I am confused about which compiler to use. Currently, I am using `gcc` and `ld` only. Which one should I use for the compilation process?

Currently my `rust_main.rs` looks like this:

```
#![feature(lang_items)]
#![no_std]

extern crate libc;

use libc::{c_char, c_int};

extern "C" {
    #[no_mangle]
    fn printf(fmt: *const c_char, ...) -> c_int;
}
fn main() {
    unsafe {
        printf("Hello World! (from Rust main())\n\0".as_ptr() as *const i8);
    }
    loop{}
}
```

Thank you!

**Comment by phil-opp** [comment]
It's probably easiest to explain by looking at the Makefile.

The `kernel` target defines the build step and uses `xargo` to compile the Rust code into a static library:

```make
kernel:
	@xargo build --target $(target)
```

The `$(kernel)` target is the link step. It depends on the `kernel` target, the generated static library (`libblog_os.a`), the assembly object files, and the linker script. It uses `ld` to link everything together:

```make
$(kernel): kernel $(rust_os) $(assembly_object_files) $(linker_script)
	@ld -n --gc-sections -T $(linker_script) -o $(kernel) \
		$(assembly_object_files) $(rust_os)
```

If you want to compile and link C code, you can add a `c_code` target that invokes your [cross-compiled gcc](https://wiki.osdev.org/GCC_Cross-Compiler) and then add the resulting `.o` or `.a` files in the linking step (the `$(kernel)` target). For example:

```make
$(kernel): kernel $(rust_os) $(assembly_object_files) $(linker_script)
	@ld -n --gc-sections -T $(linker_script) -o $(kernel) \
		$(assembly_object_files) $(your_o_files) $(rust_os)
```

**Comment by phil-opp** [comment]
I think this is answered, therefore closing.
