### ISSUE TITLE
The KERNEL environment variable must be set for building the bootloader

### ISSUE THREAD

**Issue by pjzhong** [phil-opp/blog_os#576]
Hi, phil-opp. thanks for the great tutorials! 

I get a error message while running **bootimage build**,  as below.  Did I forget something?
```
Building kernel
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
Building bootloader v0.5.2
   Compiling bootloader v0.5.2 (/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.5.2)
error: failed to run custom build command for `bootloader v0.5.2 (/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.5.2)`
process didn't exit successfully: `/home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/bootloader-0.5.2/target/release/build/bootloader-32a07e818805476f/build-script-build` (exit code: 1)
--- stderr
The KERNEL environment variable must be set for building the bootloader.
```

**Comment by phil-opp** [comment]
Your version of `bootimage` is probably too old. Try updating it through `cargo install bootimage --force`.

The build system of the bootloader changed with version 0.5.0 (it now requires a KERNEL environment variable), so we needed to release a new version of `bootimage` as well.

I just published a new `bootloader` version (0.5.3) that improves this error message and suggests updating `bootimage`.

**Comment by pjzhong** [comment]
Thanks, compiled success!!!!!!!

**Comment by phil-opp** [comment]
Perfect, thanks for the quick update!
