### ISSUE TITLE
Utterances not working

### ISSUE THREAD

**Issue by bjorn3** [phil-opp/blog_os#589]
I hit the login with github button, but after allowing it access to my github account, it just keeps showing the same login button.

**Comment by bjorn3** [comment]
I wanted to comment that I really enjoy this series!

**Comment by phil-opp** [comment]
I'm glad to hear that, thanks!

This seems like an issue with utterances to me, so perhaps open an issue [there](https://github.com/utterance/utterances)? If you block third party cookies, this might be related to https://github.com/utterance/utterances/issues/123.

**Comment by bjorn3** [comment]
> If you block third party cookies

Yes I am, allowing them fixed it.
