### ISSUE TITLE
Moving page table mapping into page fault handler

### ISSUE THREAD

**Issue by redamith2** [phil-opp/blog_os#593]
I am trying to move the mapping into the page fault handler, but i would like to create a pub static variables for both mapper and frame_allocator where I can pass it along to the mapping in the page fault handler 

```
# in lib.rs
use memory::BootInfoFrameAllocator;
pub static mut FRAME_ALLOCATOR : Option<BootInfoFrameAllocator<Iterator<Item = PhysFrame>>> = None;
pub static mut MAPPER: Option<&'static mut RecursivePageTable> = None;
```

On doing so I get the error

> doesn't have a size known at compile-time for Option<BootInfoFrameAllocator<Iterator<Item = PhysFrame>>>

**Comment by bjorn3** [comment]
`dyn Iterator<Item = PhysFrame>` doesnt have a statically known size, as any type implementing `Iterator<Item = PhysFrame>` could be behind it.

**Comment by phil-opp** [comment]
That's a tricky issue that I didn't consider. My intuition would be to use `BootFrameAllocator<impl Iterator<…>>` since otherwise it is treated like a dynamic trait object `dyn Iterator` as @bjorn3 said. However, it turns out this doesn't work either because the Rust compiler can't (yet) infer the correct type when a static is initialized with `None`.

I opened https://github.com/rust-lang/rust/issues/60367 in the Rust repository for this. Let's see what they say.

**Comment by andre-richter** [comment]
In the meantime, I think you would need to pack the Iterator as a trait object, e.g. putting it in a Box.

```rust
pub struct BootInfoFrameAllocator<I> where I: Iterator<Item = PhysFrame> {
    frames: Box<I>,
}
```

**Comment by phil-opp** [comment]
@andre-richter That should work. The problem is that we don't have heap allocation on the blog yet.

**Comment by andre-richter** [comment]
Ah, my bad :sweat_smile:

**Comment by phil-opp** [comment]
> Ah, my bad sweat_smile

Not at all. It is the best solution to this problem currently, independent of the state of the blog.

**Comment by phil-opp** [comment]
I opened #595 to change the implementation of `BootInfoFrameAllocator`. The new implementation is non generic, so it should be usable in a `static` without problems.

**Comment by phil-opp** [comment]
Investing further, it seems like we could solve the original problem with a [_named existential type_](https://github.com/rust-lang/rfcs/pull/2071) in the future. However, the implementation of this feature is still in its early stages (some ICEs andlifetime problems, only placeholder syntax), so it's not a good fit for the blog right now.

**Comment by phil-opp** [comment]
@redamith2 Could you try the updated instructions at https://os.phil-opp.com/paging-implementation/#allocating-frames and see if it works?

**Comment by redamith2** [comment]
Thank you I after making those it worked.

**Comment by phil-opp** [comment]
Perfect, thanks for trying!
