### ISSUE TITLE
Testing Post: Pass `-serial stdio` instead of `-serial mon:stdio` to QEMU

### ISSUE THREAD

**Issue by phil-opp** [phil-opp/blog_os#602]
The former allows exiting through normal `crtl+c`, but I'm not sure from the QEMU docs if it works with windows.

**Comment by AntoineSebert** [comment]
I could exit with `ctrl+c` after running `cargo xrun`. I also got this message, but that was expected:
```
error: process didn't exit successfully: `bootimage runner 'target\x86_64-blog_os\debug\blog_os'` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```

**Comment by phil-opp** [comment]
@AntoineSebert Thanks for testing! Exiting `cargo xrun` with `ctrl+c` should work fine. We currently pass the `-serial mon:stdio` argument as `test-args`, so it only applies to `xtest`.

Given that you're using windows: Could you try adding a endless loop in a test and test whether you can exit `cargo xtest`? How about when you change the `test-args` in your `Cargo.toml` from `-serial mon:stdio` instead of `-serial stdio`?
