### ISSUE TITLE
It cannot run function print_something()

### ISSUE THREAD

**Issue by ZacRenis** [phil-opp/blog_os#613]
I was trying to follow your steps to build the kernel.Stupidly,the code could not function as you say, and I could not fix it , can you help me ?

[the RenOS repository](https://github.com/ZacRenis/ren_os)

**Comment by AntoineSebert** [comment]
I did not see anything that seemed wrong in your code.
Could you describe your problem a bit more precisely ?

**Comment by ZacRenis** [comment]
follow the step,it shoud print"Hello Zac.R!" in the kernel.but it does not work.
![image](https://user-images.githubusercontent.com/21033820/58367736-11bab400-7f15-11e9-9b00-d146cca33566.png)
https://os.phil-opp.com/vga-text-mode/#try-it-out

**Comment by bjorn3** [comment]
https://github.com/ZacRenis/ren_os/blob/9de97183935103725bb5888f1e2b926aa90db562/src/vga_buffer.rs#L124

The problem is that VGA text mode doesn't support unicode. So `ö` will be shown like that.

**Comment by AntoineSebert** [comment]
Well it does not look unexpected to me, it's pretty much what you're supposed to get.
From the tutorial:
> Notice that the ö is printed as two ■ characters. That's because ö is represented by two bytes in UTF-8, which both don't fall into the printable ASCII range. In fact, this is a fundamental property of UTF-8: the individual bytes of multi-byte values are never valid ASCII.

So everything's fine :)

**Comment by phil-opp** [comment]
As I understand it, the problem that @ZacRenis has is that the "Hello W■■rld" _isn't_ printed:

> it print nothing,rather than the pic bellow

@ZacRenis I checked your code at https://github.com/ZacRenis/ren_os. The problem is that you don't call the `print_something` function from your `_start` function. I updated the blog post in bd95ade6266f4cb73834f5fc9ea167d5977ebff0 to make it more clear.

**Comment by ZacRenis** [comment]
Got it,thanks.
