### ISSUE TITLE
Storing keyboard input

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#622]
So, I have an interrupt handler for keyboard input:
```rust
extern "x86-interrupt" fn handle_key(_stack_frame: &mut InterruptStackFrame) {
use crate::printk;
use x86_64::instructions::port::Port;

// PS/2 keyboard is port 0x60.
let mut keyboard = KEYBOARD.lock();
let mut port = Port::new(0x60);
let scancode: u8 = unsafe {
port.read()
};
if let Ok(Some(event)) = keyboard.add_byte(scancode) {
if let Some(key) = keyboard.process_keyevent(event) {
match key {
DecodedKey::Unicode(character) => { printk!("{}", character); },
DecodedKey::RawKey(character) => { printk!("{:?}", character); },
}
}
}
unsafe {
PICS.lock().notify_end_of_interrupt(InterruptType::Keyboard.as_u8());
}
}
```
I want to use the [Menu](https://github.com/thejpster/menu) crate to make a basic console. However, I want my implementation to be simple to extend so I can (maybe later on) use things like io::stdin().read() when I get that far, if I ever do.  How would I rewrite this function to make the keys accessible to the rest of the kernel? Would I just plop them in a alloc::vec::Vec<u8>? I was thinking of using a key buffer like BIOSes do, but I'm not sure how nice that would be.

**Comment by phil-opp** [comment]
Sorry for not responding earlier. The best solution to your problem would probably a lock-free single-producer, single-consumer (SPSC) queue. There are some crates on crates.io, however most of them need some adjustments to make then `no_std`. Using a `Mutex<Vec>` would work too, but you need to be careful to avoid deadlocks (e.g. by disabling interrupts while popping from the vec).
