### ISSUE TITLE
Libgcc/libc support?

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#631]
Currently, the kernel does not implement libgcc/libc, making running any kind of C program an impossibility. Are there plans to port libgcc and libc -- or write a custom libc ut port libgcc -- to provide a hosted compiler toolchain?

**Comment by phil-opp** [comment]
Good question! I think it's a bit out of scope for the blog, at least for the near future. Maybe we can add support for something like Redox' [`relibc`](https://gitlab.redox-os.org/redox-os/relibc) after we have userspace support.
