### ISSUE TITLE
Reading from memory-mapped ports

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#640]
I had this code snippet waiting to be worked on (was working on my allocator, thanks Phill-Opp). I'm trying to follow OSDev and access intel HDA devices (I'm visually impaired and would love to have some kind of sound). According to the OSDev forums, the HDA device is at memory-mapped address 0xFEBF0000. I can't read that address without mapping it in (for some reason), so I do, then I try reading from raw memory in a loop like so:
```rust
    unsafe {
        for addr in 0xFEBF0000u32..0xFEBF0008u32 {
            let inp: *mut u32 = addr as *mut u32;
            printkln!("{:X}h => {:X}h", addr, read_volatile(inp));
        }
    }
```
Is this how I might read something at a memory address stored in a variable or am I doing it wrong? I know in C its easier, but I'm not exactly sure how to do it in rust. (read_volatile comes from core::ptr.)

**Comment by phil-opp** [comment]
Yes, you can do it that way. Be aware that you need to read from _physical_ address `0xFEBF0000`, not map the virtual address `0xFEBF0000` to some random frame. You can e.g. use the `identity_map` function for that: https://docs.rs/x86_64/0.7.2-beta.0/x86_64/structures/paging/mapper/trait.Mapper.html#method.identity_map

Note that I didn't look into hard disk support yet, so I can't help you with the hardware part.

**Comment by ethindp** [comment]
I'm... confused on exactly how to use this. The syntax is:
```rust
unsafe fn identity_map<A>(
    &mut self, 
    frame: PhysFrame<S>, 
    flags: PageTableFlags, 
    frame_allocator: &mut A
) -> Result<MapperFlush<S>, MapToError>where
    A: FrameAllocator<Size4KiB>,
    S: PageSize,
    Self: Mapper<S>,
```
Would I then use it like this?
```rust
pub fn allocate_phys_page_range(start: u64, end: u64) {
    let mut mapper = MAPPER.lock();
    let mut allocator = FRAME_ALLOCATOR.lock();
    match (mapper.as_mut(), allocator.as_mut()) {
        (Some(m), Some(a)) => {
            let page_range = {
                let start = VirtAddr::new(start as u64);
                let end = VirtAddr::new(end);
                let start_page = Page::containing_address(start);
                let end_page = Page::containing_address(end);
                Page::range_inclusive(start_page, end_page)
            };
            for page in page_range {
                let frame = match a.allocate_frame() {
                    Some(f) => f,
                    None => panic!("Can't allocate frame!"),
                };
                let flags = PageTableFlags::PRESENT | PageTableFlags::WRITABLE;
                unsafe {
                    match m.identity_map(page, frame, flags, a) {
                        Ok(r) => r.flush(),
                        Err(e) => panic!(
                            "Cannot map memory page range {:X}h-{:X}h: {:#?}",
                            start, end, e
                        ),
                    }
                }
            }
        }
        _ => panic!("Memory allocator or frame allocator are not set"),
    }
}
```

**Comment by phil-opp** [comment]
```rust
let frame = match a.allocate_frame()
```

This allocates a random free frame. You don't want that. You want to map the frame at address `0xFEBF0000` into the virtual address space. The identity_map function maps it at the same virtual address, so that the virtual address `0xFEBF0000` points to the physical address `0xFEBF0000` after creating the mapping.

So instead of a `page_range`, you want to create a `frame_range` in this case (use `PhysAddr` instead of `PhysAddr` and `PhysFrame` instead of `Page`).

**Comment by ethindp** [comment]
OK. Is this how I do it? I've never done this before so this is new to me.
```rust
pub fn allocate_phys_range(start: u64, end: u64) {
    let mut mapper = MAPPER.lock();
    let mut allocator = FRAME_ALLOCATOR.lock();
    match (mapper.as_mut(), allocator.as_mut()) {
        (Some(m), Some(a)) => {
            let frame_range = {
                let start = PhysAddr::new(start as u64);
                let end = PhysAddr::new(end);
                let start_frame = PhysFrame::containing_address(start);
                let end_frame = PhysFrame::containing_address(end);
                PhysFrame::range_inclusive(start_page, end_page)
            };
            for frame in frame_range {
                let flags = PageTableFlags::PRESENT | PageTableFlags::WRITABLE;
                unsafe {
                    match m.identity_map(frame, flags, a) {
                        Ok(r) => r.flush(),
                        Err(e) => panic!(
                            "Cannot map memory page range {:X}h-{:X}h: {:#?}",
                            start, end, e
                        ),
                    }
                }
            }
        }
        _ => panic!("Memory allocator or frame allocator are not set"),
    }
}
```

**Comment by phil-opp** [comment]
Yes, looks good!

**Comment by ethindp** [comment]
It appears thatRust doesn't like that.
```
error[E0283]: type annotations required: cannot resolve `_: x86_64::structures::paging::page::PageSize`
   --> src\memory.rs:259:35
    |
259 |                 let start_frame = PhysFrame::containing_address(start);
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: required by `x86_64::structures::paging::frame::PhysFrame::<S>::containing_address`
```
I pasted in the code from my above comment verbatim. Ideas?

**Comment by phil-opp** [comment]
`PhysFrame` takes a generic parameter that describes the page size, which Rust can't infer here. Try `PhysFrame::<Size4KiB>::containing_address` (with https://docs.rs/x86_64/0.7.2-beta.0/x86_64/structures/paging/page/enum.Size4KiB.html).

**Comment by ethindp** [comment]
Thanks, that worked.
