### ISSUE TITLE
Attempting to enable SSE and FPU causes page fault

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#642]
Not sure if I'm getting the asm wrong or what, but I'm trying to enable the FPU and SSE support, if detected on the system. My code looks like this:
```rust
#![feature(proc_macro_hygiene)] 
#![feature(asm)] 
extern crate rusty_asm;
use raw_cpuid::*;
use x86_64::registers::control::*;
use bit_field::BitField;
use rusty_asm::rusty_asm;

unsafe fn configure_sse_cr4() {
rusty_asm! {
asm("volatile") {
r#"mov %cr4, %rax
or 3 << 9, %ax
mov %rax, %cr4"#
}
}
}

unsafe fn configure_fpu_cr4() {
rusty_asm! {
asm("volatile") {
r#"mov %cr4, %rax
or 9, %ax
or 10, %ax
or 18, %ax
mov %rax, %cr4
fninit"#
}
}
}

//... in kmain ...
    let cpu = CpuId::new();
    match cpu.get_feature_info() {
        Some(features) => {
            if features.has_sse() {
                printkln!("Detected SSE support; enabling");
                let mut cr0 = Cr0::read_raw();
                cr0.set_bit(2, false);
                cr0.set_bit(1, true);
                unsafe {
                    Cr0::write_raw(cr0);
                    configure_sse_cr4();
                }
                printkln!("SSE enabled!");
            }
            if features.has_fpu() {
                printkln!("Detected FPU; enabling");
                let mut cr0 = Cr0::read_raw();
                cr0.set_bit(2, false);
                cr0.set_bit(5, true);
                cr0.set_bit(1, true);
                unsafe {
                    Cr0::write_raw(cr0);
                    configure_fpu_cr4();
                }
            }
        }
        None => (),
    }
```
Am I reversing the registers/operands? I'm doing my best to follow along with the OSDev assembly given to enable SSE and the FPU, but if I use the EAX register the rusty_asm crate (which lets me do ASM functions much easier than the rust asm! macro does) tells me that Ican't use that register in 64-bit mode, which is odd.

**Comment by phil-opp** [comment]
Sorry, I never used rusty_asm and I haven't seen this error either, so I can't really help you with this.

**Comment by ethindp** [comment]
Ah OK. My problem when attempting to debug it with -S and -s is that
QEMU doesn't stop running and GDB doesn't catch anything. To gDB, no
error happens at all, even when it page faults; and to QEMU, it page
faults but loops indefinitely. How would I go about making GDB
function properly so I can debug this issue?

On 7/16/19, Philipp Oppermann <notifications@github.com> wrote:
> Sorry, I never used rusty_asm and I haven't seen this error either, so I
> can't really help you with this.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/642#issuecomment-511711486


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
You should be able to do `cargo xrun -- -s -S` and then connect a GDB instance.

See also https://os.phil-opp.com/set-up-gdb/#the-annoying-issue (note that it is a post of the first edition) for an issue with GDB and https://github.com/phil-opp/blog_os/issues/374 for an alternative workaround.

**Comment by ethindp** [comment]
That's not the problem though. The problem is that when GDB connects
and I hit continue, it just sits there. When the kernel page faults,
GDB does not interrupt it like a normal program. GDB never even sees
the problem -- its as though a problem never occurred even though one
actually did.

On 7/17/19, Philipp Oppermann <notifications@github.com> wrote:
> You should be able to do `cargo xrun -- -s -S` and then connect a GDB
> instance.
>
> See also https://os.phil-opp.com/set-up-gdb/#the-annoying-issue (note that
> it is a post of the first edition) for an issue with GDB and
> https://github.com/phil-opp/blog_os/issues/374 for an alternative
> workaround.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/642#issuecomment-512143577


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
A page fault doesn't necessarily mean that something went wrong. Consider demand paging, where pages are swapped out to disk and transparently loaded back into memory in the page fault handler. It would be annoying if the debugger always breaks on such a case.

If you want to break on a page fault, just add a breakpoint on your page fault handler.

**Comment by ethindp** [comment]
It would be annoying, but for some reason, me enabling SSE and AVX
causes a page fault (protection violation) at addr 0x600 or something
like that. I have absolutely no idea why that happens though.

On 7/17/19, Philipp Oppermann <notifications@github.com> wrote:
> A page fault doesn't necessarily mean that something went wrong. Consider
> demand paging, where pages are swapped out to disk and transparently loaded
> back into memory in the page fault handler. It would be annoying if the
> debugger always breaks on such a case.
>
> If you want to break on a page fault, just add a breakpoint on your page
> fault handler.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/642#issuecomment-512152198


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
Have you tried looking at the disassembly to find out which instruction causes this? Just do an `objdump -d` of your kernel binary (in `target/your-target-triple/debug/your-binary-name`) and then grep (with a few lines of context) for the address (without the `0x` prefix) that is reported in the exception stack frame.
