### ISSUE TITLE
How to use embedded assembly code in Rust without eternal libraries

### ISSUE THREAD

**Issue by Hyijun** [phil-opp/blog_os#645]
I need to do some low-level operations to better deal with exceptions and interruptions. However, I don’t know how to emb assembly code. I tried to look it up in external library "x86_64", yet no use. If Rust doesn’t provide such method to emb assembly code, is there any other ways to do it?

**Comment by phil-opp** [comment]
Inline assembly is possible through the unstable `asm!` macro. See https://doc.rust-lang.org/unstable-book/language-features/asm.html
