### ISSUE TITLE
Reading from AHCI disks

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#656]
Will we ever be covering how to read from HDDs? This involves going through PCI enumeration but an OS is pretty useless without such support. I'm trying to learn how to get AHCI working via the OSDev wiki (its currently down, so using https://173.255.206.39 to access it) but still am unsure how (in Rust) I'd send FIS packets to the device. My code (currently) is at https://github.com/ethindp/kernel/blob/master/src/drivers/storage/ahci.rs.

**Comment by phil-opp** [comment]
Sorry for not replying to this!

> Will we ever be covering how to read from HDDs?

Maybe someday. However, there are other topics that I want to cover first.
