### ISSUE TITLE
(Testing) Post 4 - invalid use statement within 'main.rs'

### ISSUE THREAD

**Issue by ciehanski** [phil-opp/blog_os#657]
The following line produces an error during compilation:
https://github.com/phil-opp/blog_os/blob/d3e4c55fc5a8a7bff16badbdae16a15b6f67ad79/src/main.rs#L7

Error: 
```rust
error[E0432]: unresolved import `blog_os`
 --> src/main.rs:7:5
  |
7 | use blog_os::println;
  |     ^^^^^^^ use of undeclared type or module `blog_os`
```

In order to fix this compilation error it must be changed to:
```rust
use blog_os::{println};
```

**Comment by ciehanski** [comment]
lib.rs must also explicitly link all dependencies or compilation also fails (at least in my experience):
```rust
#[macro_use]
extern crate lazy_static;
extern crate spin;
extern crate uart_16550;
extern crate volatile;
extern crate x86_64;
```

**Comment by AntoineSebert** [comment]
Concerning your first problem, `use blog_os::{println};` is strictly equivalent to `use blog_os::println;`, so your problem might come from somewhere else.
Regarding your second problem, the explicit link of the dependencies is not required.

What is the version of your compiler ?
Mine is *1.38.0-nightly (60960a260 2019-08-12)*.

**Comment by ciehanski** [comment]
That was my assumption as well, but for some reason it could not find the reference to `println`. Just thought I would post in case anyone else ran into issues and were looking for a resolution. Similar case with my second issue as well, I was under the assumption that explicit links were _not_ required, but for some reason compilation fails without it. Only the minor changes I stated above supplied everything needed by the compiler.  

I'm running _rustc 1.39.0-nightly (521d78407 2019-08-25)_ which may explain the discrepancies here.

**Comment by phil-opp** [comment]
@ciehanski Do these errors also happen when building this repository, e.g. the `post-04` branch? We regularly verify that the repository builds with the latest nightly using continuous integration and I did not see this error for any nightlies.

**Comment by ciehanski** [comment]
@phil-opp your branch compiles and runs just fine as expected, no clue why I was having issues with my version. I'll go ahead and close this issue. Hopefully, if someone else gets stuck as I was, they can be referred here.

Thanks for a wondering blog!

**Comment by phil-opp** [comment]
@ciehanski Thanks for the update! Do you have your code online somewhere? Maybe we can understand what was happening here.
