### ISSUE TITLE
Transparent background color in images cause trouble on black background

### ISSUE THREAD

**Issue by oyagci** [phil-opp/blog_os#676]
Hi. I noticed that images have a transparent background.

This makes it hard to read them when we set a black background when there is black text on the image.

I think it would be much better to keep a white background on images.

What do you think?

**Comment by phil-opp** [comment]
Makes sense! I will use a white background for future images and try to convert the existing ones when I have the time.

**Comment by AntoineSebert** [comment]
I think the transparent background can be preserved if the text color is changed to a neutral color, such as `(127, 127, 127)`.
With the human eye accentuating the contrasts, it will appear closer to white on dark backgrounds, and closer to black on bright backgrounds, making it readable in both situations.

I have enclosed demo screenshots with the `color` attribute for the `<body>` tag set to `(127, 127, 127)`, with the background color set to `(0, 0, 0)` for one and `(255, 255, 255)` for the other.

![Screenshot_2019-10-19 Introduction to Paging Writing an OS in Rust(1)](https://user-images.githubusercontent.com/14963156/67143236-a1b51d80-f269-11e9-9d64-2a8b0026686b.png)
![Screenshot_2019-10-19 Introduction to Paging Writing an OS in Rust](https://user-images.githubusercontent.com/14963156/67143237-a24db400-f269-11e9-9a7d-0677c95d1dbb.png)

As a matter of personal preferences, I would say that `(127, 127, 127)/(255, 255, 255)` and `(127, 127, 127)/(0, 0, 0)` are even more comfortable to read than `(0, 0, 0)/(255, 255, 255)` and `(255, 255, 255)/(0, 0, 0)`.

I can do the conversion for the existing images if you provide me with the files.

**Comment by phil-opp** [comment]
@oyagci I'm very short on time at the moment, so I don't think that I'll be able to convert the existing SVGs soon. However, if you change the background color by editing CSS, you could just add `img { background-color: white; }` to fix the readability issue. Does this work for you?

**Comment by oyagci** [comment]
@phil-opp I didn't know this was possible. It works great!

**Comment by phil-opp** [comment]
Great!
