### ISSUE TITLE
Separate the VGA text library into a crate ?

### ISSUE THREAD

**Issue by stuaxo** [phil-opp/blog_os#681]
I was having a look at [rusty-dos](https://github.com/Serentty/rusty-dos/issues) and it looks like  the VGA text mode code here, would be handy for writing a DOS app based on it.

Is it worth separating it into it's own crate ?

**Comment by stuaxo** [comment]
Closing for now, as I probably need to learn a bit more rust + play with the code before working out if it's a good question.

**Comment by AntoineSebert** [comment]
Well since the point of this blog is to teach people ho to make a simple OS of their own, they could not learn to use VGA anymore if it is supplied by a ready-to-use crate, even if it would be the logical choice in another context :)
Have a nice day !

**Comment by stuaxo** [comment]
Thanks, that expresses it better... think I was on the way to realising this :)
