### ISSUE TITLE
GDB configuration failures

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#683]
So, I don't know what I'm doing wrong in my OS but following the GDB guide that you provided and following the guide on OSDev Wiki both failed. If I load my kernel into GDB and run qemu with -s -S, then set a hardware-assisted breakpoint (or even a normal one) using both function names and file:line numbers, qemu completely ignores the breakpoint as though it weren't even there. It makes debugging literally impossible. I'm trying to debug this strange page fault, but since GDB is being ignored, I can't even catch the page fault before it crashes.
This is my entire gdb session:
```
GNU gdb (GDB) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from kernel...done.
(gdb) target remote :1234
Remote debugging using :1234
0x000000000000fff0 in ?? ()
(gdb) hbreak kernel::drivers::storage::ahci::ata_read
Hardware assisted breakpoint 1 at 0x21b840: file src\drivers\storage/ahci.rs, line 1123.
(gdb) c
Continuing.
[Inferior 1 (process 1) exited normally]
(gdb) quit
```
Of course, the process didn't really exit normally, instead crashig with this:
```
Page fault: CAUSED_BY_WRITE
Caused by write to memory address VirtAddr(0x401000)
Stack frame: InterruptStackFrame {
    instruction_pointer: VirtAddr(0x24c4c0),
    code_segment: 8,
    cpu_flags: 0x206,
    stack_pointer: VirtAddr(0x100001feef8),
    stack_segment: 0,
}
Registers:
RAX = 100001FED80       RBX = 6872
RCX = 6872      RDX = 23BCA3
RSI = 0 RDI = 100001FED80
RSP = 100001FE258       RBP = 605A
R8 = 0  R9 = 1
R10 = 100001FEC18       R11 = 248A40
R12 = 100200000 R13 = 6872
R14 = 10000000000       R15 = 18000000000
RFLAGS = 16     CR0 = 80010613
CR2 = 401000    CR3 = 1000
CR4 = 620       CR8 = 0
EFER = 0                8       DS = 10
SS = 0  ES = 10
FS = 0  GS= 0
FSBASE = 0      GSBASE = 0                0
```
And I know, I need to allocate memory for addresses like this; I'm trying to figure out where its going wrong in the code that does call the allocator. What am I doing wrong?

**Comment by 64** [comment]
How do you know the breakpoint is being reached in the first place? I have experienced buggyness with GDB + QEMU breakpoints as well, but using hardware assistance seemed to solve the problems. If all else fails I'd try using bochs which shouldn't have any such issues.
