### ISSUE TITLE
Peculiar page fault after all kernel init sequences are finished

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#684]
Whenever my kernel finishes its initialization tasks and says "kernel init done!" it page faults for no reason at all. In debug mode, it page faults with a "page not present" error, with the caused_by_write bit clear and the CR2 register pointing to address 60BC20h and in release mode it page faults with a protection violation at address 200244h. At first I thought this was because of SSE, so I commented that out. Then I learned about the unique workaround (with the asm at the start of a page fault handler) and that solved the page fault in my UI. But this one is different.
My Text UI has been disabled (it didn't do anything useful) and now the system just page faults for no reason. Attempting to analyze the stack interrupt frame and provide more information (i.e. the code segment) causes two more page faults (but no double or triple faults). In that case, the sequence goes:
```
Page fault: error code here
Possibly caused by {read|write} {to|from} memory address {addr}
Page fault: error code here
Possibly caused by {read|write} {to|from} memory address {addr}
Page fault: error code here
Possibly caused by {read|write} {to|from} memory address {addr}
{extra page fault info}
```
I've never seen this kind of CPU execution before; I thought that if an ISR executed while another ISR was being executed it was a double fault, and one more would reset the processor.
If I re-enable SSE, it then throws an invalid opcode exception. Here's the information for that, though I doubt it'll be very useful (plus all kernel boot output):
```
Loading kernel
Enabling SSE
SSE enabled
Loading GDT
Loading IDT
Initializing chained PICs
Enabling interrupts
Configuring RTC
Starting PCI scan
Done
KBD: initializing
KBD: initiating self test
KBD: identifying keyboard
KBD: initialization complete
HDA: Interrupt pin 1h, interrupt line Bh
KBD: self test OK
HDA: init: resetting HDA controller
KBD: detected multifunction PS/2 keyboard with translation
HDA: init: reset complete
HDA: init: configuring HDA controller
HDA: init: corb: configuring
HDA: init: corb: setting corb size max to 256 entries
HDA: init: corb: allocating corb at addr E834C9140C00h
HDA: init: corb: clearing corb WP
HDA: init: corb: resetting corb RP
HDA: init: corb: configuration complete
HDA: init: rirb: configuring
HDA: init: rirb: setting rirb size max to 256 entries
HDA: init: rirb: allocating rirb at addr FFEC2DEA6280h
HDA: init: rirb: configuration complete
HDA: init: starting corb and rirb
AHCI: found AHCI-capable device with vendor 8086 and device 2922
AHCI: detected base address for AHCI driver: FEBF5000
AHCI: Inserting device at position 0
AHCI: Device scan: dbg: HbaMem {cap: C0141F05, ghc: 80000000, is: 0, pi: 3F, vs: 10000, ccc_ctl: 0, ccc_pts: 0, em_loc: 0, em_ctl: 0, cap2: 0, bohc: 0}
AHCI: Port 0: SATA device found
AHCI: cnt = 1h, buf = 1000000h
AHCI: using cmd slot 0h
AHCI: set CFL to 5h
AHCI: set W bit to 0h
AHCI: set PRDTL to 1h
AHCI: PRDT 0: set DBA to 1000000h and DBAU to 0h
AHCI: PRDT 0: set DBC to 1FFh
AHCI: PRDT 0: set i bit
AHCI: cmdfis: set fis type to 27h
AHCI: cmdfis: set C bit
AHCI: cmdfis: set command to 25h
AHCI: cmdfis: LBAs 0-2: 0h, 0h, 0h
AHCI: cmdfis: device = 40, LBAs 3-5: 0h, 0h, 0h
AHCI: cmdfis: countl = 1h, counth = 0h
AHCI: port: ci = 0h
AHCI: error: device does not appear to be bootable
Fatal error: panicked at 'Cannot continue: invalid opcode!
Stack:
InterruptStackFrame { instruction_pointer: VirtAddr(0x20a000), code_segment: 8, cpu_flags: 0x202, stack_pointer: VirtAddr(0x10000201ab0), stack_segment: 0 }
Registers:
RAX = 10000201950       RBX = 6872
RCX = 6872      RDX = 2
RSI = 254268    RDI = 10000201950
RSP = 100002016D0       RBP = 605A
R8 = 0  R9 = 2
R10 = FFFFFFFFFFFFFFFE  R11 = 25FA48
R12 = 100200000 R13 = 6872
R14 = 10000000000       R15 = 18000000000
RFLAGS = 2      CR0 = 80010613
CR2 = 0 CR3 = 1000
CR4 = 620       CR8 = 0
EFER = D00
Segments:
CS = 8  DS = 10
SS = 0  ES = 10
FS = 0  GS= 0
FSBASE = 0      GSBASE = 0
KERNELGSBASE = 0
', src\interrupts.rs:226:5
```
The debugging log is quite long, but its available over at https://ethindp.keybase.pub/gdblog.txt.
Does anyone know why this is happening? My kernel code is over at https://github.com/ethindp/kernel.

**Comment by GuillaumeDIDIER** [comment]
If you are referring to my hack involving push rax, be aware that it messes up the access to the arguments. I have posted an updated hack that includes some more pointer arithmetic. The real fix would probably need someone to dive again in LLVM x86-interrupt calling convention (which sadly seems to be rather tacky and brittle right now)

Otherwise a bit of debugging advice:
This kind of bug may require you to delve into the gory details of assembly code and stacks, don't be afraid of it.
If you break at the first instruction of pf_handler and inspect the stack itself, you should be able to immediately extract the RIP of the fault, along with the error code, which can help you diagnose if something ugly inside the interrupt handler.

It is however quite possible that the issue comes from my hack that fixed the alignment but pulled the rug from under the compiler, resulting in bogus data afterwards when reading the parameters.

**Comment by GuillaumeDIDIER** [comment]
Also I have found that bochs could be very helpful thanks to its integrated debugger that can give out CPU state that gdb does not.

**Comment by ethindp** [comment]
Yeah, I gathered that the calling convention was brittle after finding
that a hack was necessary at all. I can understand why though -- LLVM
is doing something that's never been done before (I don't think
anyway). The strange thing is that after I broke my AHCI driver even
more and it stopped printing its debugging output about reading
sectors the page fault immediately vanished. So I'm just now confused
on how it could've happened anyway, especially given that it was page
faulting *after* printkln!() was invoked.

On 11/4/19, GuillaumeDIDIER <notifications@github.com> wrote:
> Also I have found that bochs could be very helpful thanks to its integrated
> debugger that can give out CPU state that gdb does not.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/684#issuecomment-549351350


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
I assume this issue isn't solved yet? Then we should probably leave this issue open or open a new one about the SSE bugs with the `x86-interrupt` calling convention in LLVM. 

I didn't have the time to look at this issue since my comment in https://github.com/phil-opp/blog_os/issues/449#issuecomment-558219902 unfortunately, but I plan to get it fixed eventually.

**Comment by ethindp** [comment]
I haven't encountered it since I managed to fix it, but I presume
that, should I print enough strings, I'll encounter that same page
fault again.

On 1/5/20, Philipp Oppermann <notifications@github.com> wrote:
> I assume this issue isn't solved yet? Then we should probably leave this
> issue open or open a new one about the SSE bugs with the `x86-interrupt`
> calling convention in LLVM.
>
> I didn't have the time to look at this issue since my comment in
> https://github.com/phil-opp/blog_os/issues/449#issuecomment-558219902
> unfortunately, but I plan to get it fixed eventually.
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/684#issuecomment-570935001


-- 
Signed,
Ethin D. Probst

**Comment by ethindp** [comment]
Reopening this issue because I'm now experiencing this same page fault at supposed address 0. I've temporarily disabled my AHCI driver in favor of ATA for now. Port IO works... sort of. Here's how the page fault happens:
```rust
printkln!("ATA: identifying drive 0");
unsafe {
outb(0xA0, DRIVESEL); // select drive 0 on IDE bus
// Set LBA low, mid and high to 0 for identify device command
outb(0, LBAL);
outb(0, LBAM);
outb(0, LBAH);
outb(ATACommand::IdentifyDevice as u8, COMMAND); // page fault occurs here
```
My ATA driver consists of enumerations for ATA commands (write buffer, write stream ext, ...). The system is page faulting either in the call itself or in the type cast. The thing is, I don't ever recall enums being heap allocated. Hell, I don't ever recall enums taking up stack or heap memory butbeing directly embedded in the code. The LBAL andsuch are just constants,but I don't want to go around defining everything as constants to avoid this problem. Increasing the heap to 8 MB also didn't help at all.
Originally I thought it might be my kernel stack size. I had increased the number of pages allocated to it to 2048, but I just removed the stack-related configuration from Cargo.toml and it still page faults. So now I'm just very confused and unsure how to continue. What's so odd about this is that this happens when using Port IO in this case (though the same page fault has happened with other things). Port IO doesn't touch memory pages, at least from what I know, nor does it need any to function. What do you guys recommend?

**Comment by ethindp** [comment]
Update: the page fault appears to come from the outb() itself, not the conversion. Now I'm definitely confused.

**Comment by ethindp** [comment]
I've solved this issue.
