### ISSUE TITLE
Dynamic driver registration

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#696]
I would like to divide my kernel up into a feature-based architecture, equivalent to something like what Linux does. Right now I can't read data from disk yet so the full dynamic modules system is out for now. However, I would like to try something different. Here's what I'd like to do.
The programming language [go](www.golang.org) has a special function that you can define, called init, that is automatically called before main. I would like to create something similar - a function that is called when a driver wants to register itself. The driver would provide the PCI data that it accepts (i.e. class, subclass, program interface). It would also provide a function that the kernel could call to dynamically initialize drivers with the given PCI information as it scans the PCI subsystem.
The feature-based architecture would be trivial to implement. However, I am not so sure about the function-based registration system. Is something like this possible in Rust at this time?

**Comment by phil-opp** [comment]
You could use e.g. a system call to let the driver register itself.

> However, I am not so sure about the function-based registration system. Is something like this possible in Rust at this time?

You could use [trait objects](https://doc.rust-lang.org/book/ch17-02-trait-objects.html), which are dispatched at runtime.

**Comment by ethindp** [comment]
I haven't actually added syscalls yet, so the first suggestion is out.
The second idea is a good one, but I don't know what drivers may be
registered in the list (perhaps some failed to register themselves,
for example). I found the init crate
(https://github.com/mehcode/init-rs), but Idon't know if that works in
no-std environments -- I'll look into that.

On 12/3/19, Philipp Oppermann <notifications@github.com> wrote:
> You could use e.g. a system call to let the driver register itself.
>
>> However, I am not so sure about the function-based registration system. Is
>> something like this possible in Rust at this time?
>
> You could use [trait
> objects](https://doc.rust-lang.org/book/ch17-02-trait-objects.html), which
> are dispatched at runtime.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/696#issuecomment-561129739


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
I don't understand how an before-main `init` function would solve your problem. What can you do in the init function that you can't do in `main`?

**Comment by ethindp** [comment]
I am looking to automatically add driver information (i.e. PCI class,
subclass, ...) so I can initialize them while scanning for devices.
But I want to do this in suc a way that I don't need to call any of
those functions manually.

On 12/12/19, Philipp Oppermann <notifications@github.com> wrote:
> I don't understand how an before-main `init` function would solve your
> problem. What can you do in the init function that you can't do in `main`?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/696#issuecomment-564977278


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
So your kernel scans for devices and then calls the `init` function of drivers with information about PCI etc? What's the difference from calling `main` with this information?

**Comment by ethindp** [comment]
What my kernel does right now is inflexible: if I add a driver (say,
for networking) I then have to manually extend the configuration
routine to call that driver. What I'd like to do is to alter that such
that the drivers will tell the kernel what they support (eg PCI
subclass, class and program interface) without a user then needing to
modify any other part of the kernel other than their own driver. As an
example, right now if I add a new driver, I need to go into the kernel
init() routine and add that driver to the end of that function. I'm
working on a more flexible approach (especially to PCI device
discovery) but I'd like to make it possible for drivers to specify,
before the PCI scan starts, information that the kernel requires to
start the initialization sequence of that driver -- without extending
any initialization routines, but through an init() function that is
called before main that just adds entries to a statically allocated
array. Go has something like this -- and I'd like to replicate it at
the kernel level if possible.

On 12/13/19, Philipp Oppermann <notifications@github.com> wrote:
> So your kernel scans for devices and then calls the `init` function of
> drivers with information about PCI etc? What's the difference from calling
> `main` with this information?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/696#issuecomment-565403067


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
Just to clarify: You mean an `init` function for each of your drivers (that each add themselves to the arrary) or an `init` function for your kernel (that looks for available drivers and adds them all)? In case you mean the latter: This could be done by using a [cargo build script](https://doc.rust-lang.org/cargo/reference/build-scripts.html), which runs before your kernel is compiled. It could e.g. enumerate all the files in a `drivers` directory and create an array from them, which you can then include when compiling your crate (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#case-study-code-generation).

**Comment by ethindp** [comment]
Sorry for being so late on this issue, I had completely forgotten about it. :) The solution that your proposing sounds perfect. It would also add static checking of whether a driver conforms to the driver interface via the compiler. Thanks! :)

**Comment by phil-opp** [comment]
Great to hear! You're welcome.
