### ISSUE TITLE
Could use a name other than "blog_os"

### ISSUE THREAD

**Issue by bringhurst** [phil-opp/blog_os#706]
How about "rustix"? :)

**Comment by phil-opp** [comment]
Thanks for the suggestion! However, there are already a few projects named "rustix": https://github.com/search?q=rustix&type=Repositories

Also, naming is hard. Maybe the name "blog_os" isn't the most creative one, but I think it describes the essence of the project quite well: It is the byproduct from the "Writing an OS in Rust" blog with a focus in teaching (in contrast to a stand-alone project with a different focus). Further, the name is established at this point, so renaming it would only cause unnecessary confusion.

So I think I'll stick with "blog_os", at least for now :).
