### ISSUE TITLE
x86_64 compilation error for memory management

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#710]
I just updated x86_64 to 0.8.2 (the latest stable release) with cargo update. Now I'm getting this error:
```
error[E0053]: method `allocate_frame` has an incompatible type for trait
   --> src/memory.rs:131:5
    |
131 |     fn allocate_frame(&mut self) -> Option<PhysFrame> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `x86_64::structures::paging::frame_alloc::UnusedPhysFrame`, found struct `x86_64::structures::paging::frame::PhysFrame`
    |
    = note: expected fn pointer `fn(&mut memory::GlobalFrameAllocator) -> core::option::Option<x86_64::structures::paging::frame_alloc::UnusedPhysFrame>`
               found fn pointer `fn(&mut memory::GlobalFrameAllocator) -> core::option::Option<x86_64::structures::paging::frame::PhysFrame>`
```
Wat do I need to change my memory management code to? Do I just change that function to use UnusedPhysFrame and all will continue to work as before, or do I have to some in depth code surgery?

**Comment by phil-opp** [comment]
See the [Changelog of `x86_64`](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md). The change that causes this error is likely:

> **Breaking**: Add new UnsafePhysFrame type and use it in Mapper::map_to ([#89](https://github.com/rust-osdev/x86_64/pull/89))

To fix this, you need to use the new `UnusedPhysFrame` type. See the diff for the blog: https://github.com/phil-opp/blog_os/pull/703/files

**Comment by ethindp** [comment]
OK, I think I fixed it. I'm now getting a page fault at memory address
0, which is odd. It happens just after my PCI scan starts when I go to
add a device. WhenI acquire the mutex lock, it page faults. The source
appears to be the spin crate, but I don't know why that would be
(unless they've changed something over there). My PCI code is at
https://github.com/ethindp/kernel/blob/master/src/pci.rs. I can't
really test memory code until I fix this #pg.

On 1/3/20, Philipp Oppermann <notifications@github.com> wrote:
> See the [Changelog of
> `x86_64`](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md).
> The change that causes this error is likely:
>
>> **Breaking**: Add new UnsafePhysFrame type and use it in Mapper::map_to
>> ([#89](https://github.com/rust-osdev/x86_64/pull/89))
>
> To fix this, you need to use the new `UnusedPhysFrame` type. See the diff
> for the blog: https://github.com/phil-opp/blog_os/pull/703/files
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/710#issuecomment-570532468


-- 
Signed,
Ethin D. Probst

**Comment by ethindp** [comment]
Fixed the problem. Thanks for the help :)!

**Comment by phil-opp** [comment]
Great, thanks for the update!
