### ISSUE TITLE
Possible Typo's: Freestanding Rust Binary

### ISSUE THREAD

**Issue by fkrunic** [phil-opp/blog_os#717]
These may be unintended typos in `A Freestanding Rust Binary`: 

Original: "... the entry point should **e.g.** invoke the exit system ..."
Revised:  "... the entry point should invoke the exit system ..."

Original: "So **it probably** for any real use of such a binary, more steps are required."
Revised: "So for any real use of such a binary, more steps are required."

The content is great - keep it up!

**Comment by phil-opp** [comment]
Thanks for reporting!

> Original: "... the entry point should **e.g.** invoke the exit system ..."
> Revised: "... the entry point should invoke the exit system ..."

I wanted to say that invoking the `exit` system call is one option, but that there are also other options (such as and endless loop). Without the `e.g.`, it sounds like the entry point must always invoke the system call, which is not true.



> Original: "So **it probably** for any real use of such a binary, more steps are required."
> Revised: "So for any real use of such a binary, more steps are required."

Good catch! Seems like an editing error introduced in https://github.com/phil-opp/blog_os/commit/0b9ca847356c3f932e038d3b32d5e85a6e53e971. I pushed 7070bb608dcb1709629c49667d689a6993b9ecf2 to fix it.
