### ISSUE TITLE
Outdated info in Introduction to Paging

### ISSUE THREAD

**Issue by JochenLutz** [phil-opp/blog_os#730]
In section Paging on x86_64:

> There are plans to extend the address size to 57 bits through a 5-level page table, but no processor that supports this feature exists yet.

But according to the Wikipedia article (Intel 5-level paging)[https://en.wikipedia.org/wiki/Intel_5-level_paging] linked in this sentence, the Intel Ice Lake introduced in September 2019 implements 5-level paging.

**Comment by phil-opp** [comment]
Thanks for reporting! I opened #732 to fix this.
