### ISSUE TITLE
Keep the link << All posts

### ISSUE THREAD

**Issue by Menschenkindlein** [phil-opp/blog_os#731]
Currently, the link to the main page is hidden after you scroll down. It is a bit annoying when you want to recheck something in the previous posts and cannot just open the main page in a new tab without losing the progress in the current one.

While writing this, I realized that there are at least three ways to do it: back button, duplicate tab, and bookmarks. So, posting this issue solely to inform you that such a misunderstanding may take place.

**Comment by phil-opp** [comment]
I pushed an update in e2ea963d5d8dc653c7e67cb4bd4a17a65116aac8 that should keep the link visible at all times. Does it work for you?

**Comment by Menschenkindlein** [comment]
Great! Thanks! And thank you for the whole series. Can't wait for the new posts!

**Comment by phil-opp** [comment]
I'm working on the next post right now :).
