### ISSUE TITLE
layout.size and layout.align - both methods not found

### ISSUE THREAD

**Issue by tcaudrey** [phil-opp/blog_os#741]
Hi - thanks for the really informative series - awesome work - thanks!!!

However (there had to be a however...)

when building post 11 allocator/linked_list.rs, I am getting these errors - both from my repository, and the same when I cloned yours:
```
error[E0599]: no method named `size` found for type `core::result::Result<core::alloc::Layout, core::alloc::LayoutErr>` in the current scope
   --> src/allocator/linked_list.rs:116:27
    |
116 |         let size = layout.size().max(mem::size_of::<ListNode>());
    |                           ^^^^ method not found in `core::result::Result<core::alloc::Layout, core::alloc::LayoutErr>`

error[E0599]: no method named `align` found for type `core::result::Result<core::alloc::Layout, core::alloc::LayoutErr>` in the current scope
   --> src/allocator/linked_list.rs:117:23
    |
117 |         (size, layout.align())
    |                       ^^^^^ method not found in `core::result::Result<core::alloc::Layout, core::alloc::LayoutErr>`

error: aborting due to 2 previous errors
```
I had another error yesterday where linked_list_allocator 0.6.6 broke things, so I had to explicitly specify version 0.6.5 to get things to compile, but I'm a bit lost on this one...

As I said I get the same errors with your code and mine...

hope you have some idea what might be going wrong?

Cheers,

Tim.

**Comment by AntoineSebert** [comment]
I think I had the same problem last week.
As @phil-opp pointed it out to me, the nightly is unstable prone to changes.
Try to update your toolchain to see if it solves the problem.
The command for that is `rustup update`, or something like similar.

Hope it helps !

**Comment by tcaudrey** [comment]
@AntoineSebert - thanks for the tip, I thought I had already tried this, however this morning, the previous errors are gone, to be replaced with this:
```
error[E0432]: unresolved import `alloc::alloc::Alloc`
  --> /home/timc/.cargo/registry/src/github.com-1ecc6299db9ec823/linked_list_allocator-0.6.4/src/lib.rs:14:20
   |
14 | use alloc::alloc::{Alloc, AllocErr, Layout};
   |                    ^^^^^
   |                    |
   |                    no `Alloc` in `alloc`
   |                    help: a similar name exists in the module: `alloc`

error: aborting due to previous error
```
I get this with my own and @phil-opp   code (as before)...

Any more ideas?

**Comment by bjorn3** [comment]
`Alloc` recently got renamed to `AllocRef`.

**Comment by tcaudrey** [comment]
OK - I seem to have fixed it - I put this in my Cargo.toml:

`linked_list_allocator = "=0.6.6"`

(even though linked_list_allocator 0.6.6 was giving errors a few days ago)...
and now the code compiles...

**Comment by tcaudrey** [comment]
closing

**Comment by tcaudrey** [comment]
issue was "fixed"

**Comment by phil-opp** [comment]
@tcaudrey Good to hear that you got it working! The breakage in this case was caused directly by Rust, so there was no way to avoid it in the libraries unfortunately.
