### ISSUE TITLE
Weird UB and page faults when not running in release mode

### ISSUE THREAD

**Issue by vgarleanu** [phil-opp/blog_os#743]
Heya, I've been toying around with my own kernel based on blog_os (https://gitlab.com/vgarleanu/vallicks) and for a good while I experienced really weird almost random page faults whenever boxing closures/data or pushing elements to vectors/hashmaps. These issues seem to be present only when running in debug mode and when running in release mode they magically go away.

Anyone has any idea as to why this is happening? I suspect a faulty codegen somewhere.

**Comment by 64** [comment]
Interesting, can you provide some more information about the page faults? What instruction is faulting?

**Comment by vgarleanu** [comment]
Its a bit hard to catch the bug happening as it literally pagefaults in random pages at random times, sometimes it doesnt even happen and the kernel runs fine. Ill try to track it down a bit more and will post and update.

**Comment by phil-opp** [comment]
@vgarleanu Do you think this is/was related to #746?

**Comment by vgarleanu** [comment]
I wish. #746 was happening in release mode too, and when i was debugging this issue earlier i disabled the scheduler completely.

**Comment by vgarleanu** [comment]
Ok it gets a bit weird. I was questioning what the differences between blog_os and my fork are, and its the PIT. Ive made the PIT tick faster. Disabling the PIT in debug mode fixes the weird page faults. I have no clue whatsoever as to why this is the case.

**Comment by vgarleanu** [comment]
Ill be closing this issue as its a bit unrelated to blog_os, and at the same time i can avoid this bug by only enabling the PIT to run at high frequencies in release mode binaries.

**Comment by bjorn3** [comment]
Is it possible that a PIT interrupt fired before the last one was completely handled?

**Comment by vgarleanu** [comment]
Nope, ive actually found the cause, ill open a new issue as this is related to this project.

**Comment by phil-opp** [comment]
@vgarleanu I just tried to debug your issue based on commit 6c279afe82c04dde5faaf44e544de37eeaf5bc01 of your repo. I think that this is probably related to the thread switching code and most probably this FIXME:

```rust
// FIXME: For some reason a context switch fails to restore %rax, causing lock xadd
//        %rcx,0x10(%rax) to cause a double fault
thread::sleep(1);//thread::sleep(1); // sleep for 10 milis
```

If a thread::sleep "fixes" things, it's likely a time-related bug, so it makes sense that you see it in debug mode but not release mode (debug mode is slower, so 10ms is relatively shorter).

I try to get to the bottom of this
