### ISSUE TITLE
Segfault in test runner function

### ISSUE THREAD

**Issue by archerface** [phil-opp/blog_os#744]
As a disclaimer: I am new to Rust.

I am currently using `rustc 1.43.0-nightly (442ae7f04 2020-02-06)` for rustc.

I appear to have a segfault around my `test_runner` function. It segfaults when I run `cargo xtest` but not when I run `cargo bootimage` and run the given executable in Qemu.

Did I miss something? Is something about my version of rustc? Or is it something else entirely?

Any help or tips are greatly appreciated!

```rust
#![no_std]
#![no_main]
#![feature(custom_test_frameworks)]
#![test_runner(crate::test_runner)]
#![reexport_test_harness_main = "test_main"]

use core::panic::PanicInfo;

mod vga_buffer;

#[cfg(test)]
fn test_runner(tests: &[&dyn Fn()]) {
    println!("Running {} tests", tests.len());
    for test in tests {
        test();
    }
}

#[no_mangle]
pub extern "C" fn _start() -> ! {
    println!("Hello World{}", "!");

	#[cfg(test)]
	test_main();

    loop {}
}

#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    println!("{}", info);
    loop {}
}
```

**Comment by phil-opp** [comment]
Did you add a `.cargo/config` file and specified bootimage as runner there? Otherwise, `cargo xtest` tries to execute your kernel as a normal user-level program in your host OS, which commonly causes a segfault.

**Comment by archerface** [comment]
@phil-opp Ah that was it. I did miss that. Does make sense that that the code would segfault when attempting to run on my host OS. Thanks for the assistance. 
Also thank you for this blog. It is really cool and I am having a lot of fun working through it.

**Comment by phil-opp** [comment]
Great to hear that, thanks!
