### ISSUE TITLE
Invalid register in context_switch will cause a bunch of UB with RBP never being pushed onto the stack

### ISSUE THREAD

**Issue by vgarleanu** [phil-opp/blog_os#746]
Theres a small spelling mistake at https://github.com/phil-opp/blog_os/blob/post-12-wip/src/multitasking/context_switch.rs#L53 where `rbp` is spelled as `rpb`. This will cause weird UB sometimes.

**Comment by bjorn3** [comment]
Why is that even allowed by LLVM without crash?

**Comment by vgarleanu** [comment]
No clue, i expected something like this to not compile at all, or at least throw a SIGILL. Such a obvious thing took quite a while to track down haha

**Comment by phil-opp** [comment]
Oh wow, good catch!

> Why is that even allowed by LLVM without crash?

That's a very good question! I can't wait for https://github.com/rust-lang/rfcs/pull/2850, which will hopefully fix such problems.

**Comment by phil-opp** [comment]
> Such a obvious thing took quite a while to track down haha

I can imagine that! Thanks a lot for debugging and reporting this!

I fixed the code in https://github.com/phil-opp/blog_os/commit/3fc7bf6aa1fa4387cef7969ab4fd071c1e1731b3.
