### ISSUE TITLE
disable-redzone flag in the target profile never gets passed to rustc

### ISSUE THREAD

**Issue by vgarleanu** [phil-opp/blog_os#753]
During the development of my kernel I've encountered several issues related to bogus memory access causing random page faults. The issue is outlined here: #743.

After a bit of debugging I have started inspecting all the verbose cargo logs and noticed that the `-Cno-redzone` flag never gets passed to rustc even tho the `disable-redzone` option was marked as true in my cargo profile.

I manually added the `-Cno-redzone=true` flag to the `.cargo/config` file under the `rustflags` attribute which seems to fix my issue as well as #743.
 
Could someone else confirm that this is the case? There may be a invariant on my system but I am unsure.

**Comment by phil-opp** [comment]
The target specification is handled directly by `rustc`, not by cargo. So it's expected that cargo does not pass the `no-redzone` flag. The relevant code in `rustc` is <https://github.com/rust-lang/rust/blob/a29424a2265411dda7d7446516ac5fd7499e2b55/src/librustc_codegen_llvm/declare.rs#L45-L47>: When no option is given, the value of the `disable_redzone` field in the target specification is used.

The question is: Why does adding the flag fix your issue? Maybe you have a typo in your target configuration?

**Comment by phil-opp** [comment]
To try whether you have a typo, execute:

```
rustc -Z unstable-options --print target-spec-json --target your-target-spec.json
```

You should see `"disable-redzone": true`  in the output.

**Comment by vgarleanu** [comment]
I've run the command specified and `"disable-redzone": true` is indeed in the output, however I do not understand why I have to manually add it as a extra `rustflag` manually. I've also tested this out on a completely separate system and its the same case. I'll shortly try setting up the PIT on a exact copy of blog_os and see if the same issue pops up, maybe my configuration is indeed off.

**Comment by phil-opp** [comment]
>  I do not understand why I have to manually add it as a extra `rustflag` manually.

You should not have to do this. If this really fixes things, there is some bug in `rustc` itself. One way to check this could be to compare the executables with and without the extra rustflag. When the target option works correctly, both files should be identical.

> I'll shortly try setting up the PIT on a exact copy of blog_os and see if the same issue pops up

This would be very helpful! I'm able to reproduce the issues with your project and tried to debug it (see #743), but I can't find the problem either. My guess is that it's related to the threading code. I don't have the time to dig further, so a minimal example that reproduces the issue would be very helpful!

**Comment by vgarleanu** [comment]
Thanks for all the help phil, it seems that after a `rustup update`, removing the `Cargo.lock` and running `cargo clean` seems to fix and make the issue completely go away. I'm not really sure what happened here. I'll be closing the issue as it is now fixed.

**Comment by phil-opp** [comment]
Hmm, I'm able to reproduce it by passing `-d int` to QEMU. But I'm using an older version of your project.

I still think that it's worth understanding this issue as it likely indicates some fundamental bug. So let me know if it comes up again !

**Comment by vgarleanu** [comment]
@phil-opp I suspect the issue is probably a caching bug with cargo. In a earlier version of my project there was a spelling mistake and `"disable-redzone"` was spelled as `"disabled-redzone"`. This was fixed as soon as I noticed it but I guess the issue persisted anyway until I force cleaned all the project files.

**Comment by phil-opp** [comment]
Ah, that could be the reason. Albeit I'm not sure why cargo did not recompile it properly… Either way, let's hope that everything continues to work.

**Comment by bjorn3** [comment]
I don't think cargo cares about the content of the target json. Maybe open an issue?

**Comment by vgarleanu** [comment]
Ill try to reproduce the issue again. If cargo indeed doesn't care about the contents Ill open a issue. Thanks a lot for all the help guys!
