### ISSUE TITLE
Triple fault when trying to boot kernel in Qemu; Dsound failures (possibly Windows only)

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#770]
Using qemu 4.2.0 (v4.2.0-11797-g2890edc853-dirty). Whenever I try and use `cargo xrun`, I get two things: first, dsound warnings:
```
dsound: Could not lock playback buffer
dsound: Reason: An invalid parameter was passed to the returning function
dsound: Failed to lock buffer
```
And qemu almost immediately terminates. The log says:
```
ILLOPC: 000000000000c2e4: c4 e2 e9
check_exception old: 0xffffffff new 0x6
     0: v=06 e=0000 i=0 cpl=0 IP=0008:000000000000c2e4 pc=000000000000c2e4 SP=0000:0000000000007afa env->regs[R_EAX]=0000000000000006
RAX=0000000000000006 RBX=0000000000000000 RCX=00000000c0000080 RDX=00000000000000c0
RSI=0000000000000034 RDI=0000000000007b12 RBP=0000000000000006 RSP=0000000000007afa
R8 =0000000000000000 R9 =0000000000000000 R10=0000000000000000 R11=0000000000000000
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=000000000000c2e4 RFL=00000087 [--S--PC] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0000 0000000000000000 00000000 00000000
DS =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
GS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000000000810b 0000001a
IDT=     0000000000000000 00000000
CR0=80000011 CR2=0000000000000000 CR3=0000000000001000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000040 CCD=ffffffffffffffc0 CCO=SUBB    
EFER=0000000000000500
check_exception old: 0xffffffff new 0xd
     1: v=0d e=0062 i=0 cpl=0 IP=0008:000000000000c2e4 pc=000000000000c2e4 SP=0000:0000000000007afa env->regs[R_EAX]=0000000000000006
RAX=0000000000000006 RBX=0000000000000000 RCX=00000000c0000080 RDX=00000000000000c0
RSI=0000000000000034 RDI=0000000000007b12 RBP=0000000000000006 RSP=0000000000007afa
R8 =0000000000000000 R9 =0000000000000000 R10=0000000000000000 R11=0000000000000000
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=000000000000c2e4 RFL=00000087 [--S--PC] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0000 0000000000000000 00000000 00000000
DS =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
GS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000000000810b 0000001a
IDT=     0000000000000000 00000000
CR0=80000011 CR2=0000000000000000 CR3=0000000000001000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000040 CCD=ffffffffffffffc0 CCO=SUBB    
EFER=0000000000000500
check_exception old: 0xd new 0xd
     2: v=08 e=0000 i=0 cpl=0 IP=0008:000000000000c2e4 pc=000000000000c2e4 SP=0000:0000000000007afa env->regs[R_EAX]=0000000000000006
RAX=0000000000000006 RBX=0000000000000000 RCX=00000000c0000080 RDX=00000000000000c0
RSI=0000000000000034 RDI=0000000000007b12 RBP=0000000000000006 RSP=0000000000007afa
R8 =0000000000000000 R9 =0000000000000000 R10=0000000000000000 R11=0000000000000000
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=000000000000c2e4 RFL=00000087 [--S--PC] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0000 0000000000000000 00000000 00000000
DS =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
GS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000000000810b 0000001a
IDT=     0000000000000000 00000000
CR0=80000011 CR2=0000000000000000 CR3=0000000000001000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000040 CCD=ffffffffffffffc0 CCO=SUBB    
EFER=0000000000000500
check_exception old: 0x8 new 0xd
Triple fault
```
If I understand this correctly, the processor hits Invalid Opcode, then two General Protection Faults, then Double Fault, then triple fault. If CR2 is to be believed, these occur at memory address 0000000000000000h. If I understand the bitmask for CR0 correctly (10000000000000000000000000010001), then: (1) the processor is in protected mode, (2) bit 27 is set (rsvd), (3) paging is enabled, and (4) VME is active. This implies that the bootloader has already begun initialization of the system but has not entered long mode. I'm not sure what else I can get from this information, nor am I sure what's even causing this. I use RDRAND in my kernel, and have enabled the `rdrnd` and `rdseed` features in the target manifest, but this happens, apparently, before my kernel has even begun execution. Does anyone have any idea on what could be causing this?
I'm also not sure of how to fix the DSound errors. This behavior -- the failure to boot, and dsound -- has never happened on Qemu before for me.
Edit: I should note that I haven't tried this on Linux yet.

**Comment by phil-opp** [comment]
Have you tried other QEMU versions as well? This would help finding out whether this is a QEMU bug or a problem in your code.

**Comment by ethindp** [comment]
I just tried it with version 3.0.92 (v3.1.0-rc2-11731-ge7dfdcb196-dirty). The log has similar output:
```
ILLOPC: 000000000000c2e4: c4 e2 e9
check_exception old: 0xffffffff new 0x6
     0: v=06 e=0000 i=0 cpl=0 IP=0008:000000000000c2e4 pc=000000000000c2e4 SP=0000:0000000000007afa env->regs[R_EAX]=0000000000000006
RAX=0000000000000006 RBX=0000000000000000 RCX=00000000c0000080 RDX=00000000000000c0
RSI=0000000000000034 RDI=0000000000007b12 RBP=0000000000000006 RSP=0000000000007afa
R8 =0000000000000000 R9 =0000000000000000 R10=0000000000000000 R11=0000000000000000
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=000000000000c2e4 RFL=00000087 [--S--PC] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0000 0000000000000000 00000000 00000000
DS =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
GS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000000000810b 0000001a
IDT=     0000000000000000 00000000
CR0=80000011 CR2=0000000000000000 CR3=0000000000001000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000040 CCD=ffffffffffffffc0 CCO=SUBB    
EFER=0000000000000500
check_exception old: 0xffffffff new 0xd
     1: v=0d e=0062 i=0 cpl=0 IP=0008:000000000000c2e4 pc=000000000000c2e4 SP=0000:0000000000007afa env->regs[R_EAX]=0000000000000006
RAX=0000000000000006 RBX=0000000000000000 RCX=00000000c0000080 RDX=00000000000000c0
RSI=0000000000000034 RDI=0000000000007b12 RBP=0000000000000006 RSP=0000000000007afa
R8 =0000000000000000 R9 =0000000000000000 R10=0000000000000000 R11=0000000000000000
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=000000000000c2e4 RFL=00000087 [--S--PC] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0000 0000000000000000 00000000 00000000
DS =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
GS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000000000810b 0000001a
IDT=     0000000000000000 00000000
CR0=80000011 CR2=0000000000000000 CR3=0000000000001000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000040 CCD=ffffffffffffffc0 CCO=SUBB    
EFER=0000000000000500
check_exception old: 0xd new 0xd
     2: v=08 e=0000 i=0 cpl=0 IP=0008:000000000000c2e4 pc=000000000000c2e4 SP=0000:0000000000007afa env->regs[R_EAX]=0000000000000006
RAX=0000000000000006 RBX=0000000000000000 RCX=00000000c0000080 RDX=00000000000000c0
RSI=0000000000000034 RDI=0000000000007b12 RBP=0000000000000006 RSP=0000000000007afa
R8 =0000000000000000 R9 =0000000000000000 R10=0000000000000000 R11=0000000000000000
R12=0000000000000000 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=000000000000c2e4 RFL=00000087 [--S--PC] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0000 0000000000000000 00000000 00000000
DS =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
GS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000000000810b 0000001a
IDT=     0000000000000000 00000000
CR0=80000011 CR2=0000000000000000 CR3=0000000000001000 CR4=00000020
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=0000000000000040 CCD=ffffffffffffffc0 CCO=SUBB    
EFER=0000000000000500
check_exception old: 0x8 new 0xd
Triple fault
```
I have no idea right now what's causing this. My initialization code for my kernel starts off like so:
```rust
fn kmain(boot_info: &'static BootInfo) -> ! {
    if RdRand::new().is_none() {
        printkln!("Error: rdrand is not supported on this system, but rdrand is required");
        kernel::idle_forever();
    }
    printkln!("Loading kernel");
    let rdrand = RdRand::new().unwrap();
    let mut start_addr: u64 = rdrand.get_u64().unwrap();
    for region in boot_info.memory_map.iter().cycle() {
        if region.region_type == MemoryRegionType::Usable
            && (start_addr < region.range.start_addr()
                || start_addr > region.range.end_addr()
                || (start_addr + 8 * 1_048_576) > region.range.end_addr())
        {
            start_addr = rdrand.get_u64().unwrap();
            continue;
        } else if region.region_type == MemoryRegionType::Usable
            && (start_addr >= region.range.start_addr()
                || (start_addr + 8 * 1_048_576) < region.range.end_addr())
        {
            break;
        }
    }
    let mut end_addr = start_addr + 8 * 1_048_576;
    while ((end_addr - start_addr) % 32768) != 0 {
        end_addr -= 1;
    }
    kernel::memory::init(
        boot_info.physical_memory_offset,
        &boot_info.memory_map,
        start_addr,
    );
    unsafe {
        ALLOCATOR
            .lock()
            .init(start_addr as usize, (end_addr - start_addr) as usize);
    }
    kernel::init();
    kernel::idle_forever();
}
```
I altered my memory manager -- but if that was the problem, my kernel would've printed 'Loading kernel' and then died, which isn't what's happening here -- nothing is being displayed on the serial port at all. When debugging my code with GDB, I set a HW breakpoint for line 32 of main.rs -- which is the conditional check for rdrand. When I tell GDB to continue, it runs for a moment then immediately terminates normally (according to GDB anyway). So this proves that this is not the fault of my code whatsoever.

**Comment by phil-opp** [comment]
Sounds like it is a problem with your code then. I'm happy to take a look at it if you have it somewhere online.

**Comment by ethindp** [comment]
According to GDB, its not. But my code is available at
https://github.com/ethindp/kernel

On 3/31/20, Philipp Oppermann <notifications@github.com> wrote:
> Sounds like it is a problem with your code then. I'm happy to take a look at
> it if you have it somewhere online.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/770#issuecomment-606554169


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
Thanks for the link! I'm able to reproduce the error and you're correct that the error occurs in the bootloader. The problems seems to be the `rustflags = ["-C", "target-cpu=native"]` key in your `.cargo/config` file. Without it, your project boots fine. It still triple faults, but this time inside your kernel (it seems like the reason is that an non-canoncial memory address is dereferenced).

The problem is that `build.rustflags` currently applies to _all_ compiler invocations, including the bootloader build. This means that the first stages on the bootloader use special instructions of your CPU that are not available yet, likely because they are not enabled yet or not supported by QEMU.

I opened https://github.com/rust-osdev/bootimage/pull/51 to ensure that no `build.rustflags` key is applied to the bootloader build.

**Comment by ethindp** [comment]
Thanks!

On 4/1/20, Philipp Oppermann <notifications@github.com> wrote:
> Closed #770 via rust-osdev/bootimage#51.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/770#event-3187715396


-- 
Signed,
Ethin D. Probst

**Comment by ethindp** [comment]
OK, so still hitting this issue. The triple fault occurs when the system is printing "Loading kernel" for some reason, or at least GDB is pointing me there. I can't tell any more than that -- stepping into the code yields a lot of libcore code that I don't understand. The VGA driver seems to be causing it, though I'm not sure precisely what (it seems like its the serial port, though I don't know how that couldbe the cause).

**Comment by phil-opp** [comment]
I just tried to debug your project. It seems like the error occurs in your kernel now. For example, it no longer triple faults when I put a `loop{}` at the start of your kmain.

Debugging your project was very difficult because I did not get any output for kprintln or panic. Therefore I can only take a guess: You don't want `target-cpu=native` for your kernel because this builds a kernel for your host CPU, even though you run it on a emutlated CPU in QEMU. I'm also not sure about the use of SSE instructions and the large number of features that you enable in your target JSON.

Without ``target-cpu=native` and the `feature` list from the blog, your project runs fine for me. It errors that rdrand is not available though, but it no longer triple faults.

**Comment by ethindp** [comment]
Thanks, that worked.

On 4/7/20, Philipp Oppermann <notifications@github.com> wrote:
> I just tried to debug your project. It seems like the error occurs in your
> kernel now. For example, it no longer triple faults when I put a `loop{}` at
> the start of your kmain.
>
> Debugging your project was very difficult because I did not get any output
> for kprintln or panic. Therefore I can only take a guess: You don't want
> `target-cpu=native` for your kernel because this builds a kernel for your
> host CPU, even though you run it on a emutlated CPU in QEMU. I'm also not
> sure about the use of SSE instructions and the large number of features that
> you enable in your target JSON.
>
> Without ``target-cpu=native` and the `feature` list from the blog, your
> project runs fine for me. It errors that rdrand is not available though, but
> it no longer triple faults.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/770#issuecomment-610293606


-- 
Signed,
Ethin D. Probst
