### ISSUE TITLE
Broken link on https://os.phil-opp.com/async-await/

### ISSUE THREAD

**Issue by gabriel-fallen** [phil-opp/blog_os#776]
A "projections and structural pinning" link (before the [Executors and Wakers](https://os.phil-opp.com/async-await/#executors-and-wakers)) points to `file:///home/philipp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/doc/rust/html/std/pin/index.html#projections-and-structural-pinning`.

**Comment by phil-opp** [comment]
Whoops, seems like I linked to my local docs. Fixed in 0512a65c4247f85fa772a68c3800a6c69402cb57, thanks for reporting!
