### ISSUE TITLE
Community?

### ISSUE THREAD

**Issue by deliciouslytyped** [phil-opp/blog_os#790]
Do you have an IRC channel? I've seen some mentions of bugs reported over IRC but havent found anything more.

**Comment by 64** [comment]
There is a Gitter channel: https://gitter.im/phil-opp/blog_os

**Comment by phil-opp** [comment]
There is no IRC channel related to this project, only the gitter channel mentioned by @64 and the comment threads at the bottom of each blog post, which map to GitHub issues.

**Comment by phil-opp** [comment]
This is answered, therefore closing.
