### ISSUE TITLE
Dynamically registering IDT entries?

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#797]
Currently, the IDT data structure requires its lifetime to be static. This causes a major problem -- how do you then modify the IDT later? For example, what would I want to do if I wanted to receive interrupts from a PCI device but I only know the interrupt number when I scan the PCI bus?
I ask because this is something I'd like to do. Is there a way I can modify the IDT safely without having to resort to ASM?

**Comment by phil-opp** [comment]
Good question! I'm not sure what's the best solution for this. Maybe using atomics for the IDT entries could work, but we should check the x86 reference manual whether something like this is allowed. It could help to look at how other projects solve this problem (e.g. the Linux kernel).

**Comment by ethindp** [comment]
The Intel manuals, volume 3A, section 6.11, says:
```
The LIDT (load IDT register) and SIDT (store IDT register) instructions load and store the contents of the IDTR register, respectively. The LIDT instruction loads the IDTR register with the base address and limit held in a memory operand. This instruction can be executed only when the CPL is 0. It normally is used by the initialization code of an operating system when creating an IDT. An operating system also may use it to change from one IDT to another.
The SIDT instruction copies the base and limit value stored in IDTR to memory. This instruction can be executed at any privilege level.
```
The AMD 64 manuals, volume 2, section 4.6.5, say:
```
The final type of descriptor table is the interrupt descriptor table (IDT). Multiple IDTs can be maintained by system software. System software selects a specific IDT by loading the interrupt descriptor table register (IDTR) with a pointer to the IDT. As with the GDT and LDT, system software can store the IDT anywhere in memory and should protect the segment containing the IDT from non-privileged software.
```
Does this help?

**Comment by phil-opp** [comment]
The question is whether it's allowed to modify the IDT at runtime without reloading it. I can't really find any information about that.

**Comment by ethindp** [comment]
I can't either. I don't mind reloading it on every major set of IDT
changes, I just need some way of doing so. Right now the IDT is marked
entirely as static so I can't put it in a mutex and modify it that
way.

On 4/24/20, Philipp Oppermann <notifications@github.com> wrote:
> The question is whether it's allowed to modify the IDT at runtime without
> reloading it. I can't really find any information about that.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/797#issuecomment-619097976


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
There is a `load_unsafe` method now that accepts any lifetime: https://github.com/rust-osdev/x86_64/pull/137

An alternative solution could be to set all IDT entries to some kind of default handler that performs dynamic dispatch based on the interrupt number

**Comment by ethindp** [comment]
Now that's a nice idea. An interrupt chain, maybe?

On 4/24/20, Philipp Oppermann <notifications@github.com> wrote:
> There is a `load_unsafe` method now that accepts any lifetime:
> https://github.com/rust-osdev/x86_64/pull/137
>
> An alternative solution could be to set all IDT entries to some kind of
> default handler that performs dynamic dispatch based on the interrupt
> number
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/797#issuecomment-619113396


-- 
Signed,
Ethin D. Probst

**Comment by ethindp** [comment]
I started a topic on the OSDev forum: https://forum.osdev.org/viewtopic.php?f=1&t=36715. Does that help? Feel free to post there if you like.

**Comment by phil-opp** [comment]
The problem with changing the entries of an existing IDT is that we would need UnsafeCell and unsafe for that. We can't really use atomics because there is no AtomicU128 type afaik.

I think the most promising option is to define wrapper functions that call a default handler with the interrupt number. Maybe we can add a convenience function to this crate that sets up the wrapper functions for you.

**Comment by ethindp** [comment]
Why must we use u128s? Can we just use u64s and then pad the remaining
bytes with zeros? There are only 256 interrupt vectors; a u128 seems
overkill for that.

On 4/29/20, Philipp Oppermann <notifications@github.com> wrote:
> The problem with changing the entries of an existing IDT is that we would
> need UnsafeCell and unsafe for that. We can't really use atomics because
> there is no AtomicU128 type afaik.
>
> I think the most promising option is to define wrapper functions that call a
> default handler with the interrupt number. Maybe we can add a convenience
> function to this crate that sets up the wrapper functions for you.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/797#issuecomment-621189958


-- 
Signed,
Ethin D. Probst

**Comment by bjorn3** [comment]
An idt entry is 128bit. You need to atomically write the full 128bit entry to avoid problems.

**Comment by ethindp** [comment]
I think I've found a way of successfully solving this problem (maybe...). We'll see how it goes.

**Comment by phil-opp** [comment]
Please report back if you have found a good solution!
