### ISSUE TITLE
Strange qemu crashes/triple faults

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#798]
So, my kernel is still triple faulting and I can't figure out why. The process is terminating for some odd reason (I can't even debug the crash because it immediately exits, and I imagine that I wouldn't be able to do that even if I didn't have -no-reboot on). The logs show:
```
check_exception old: 0xffffffff new 0xe
     0: v=0e e=0002 i=0 cpl=0 IP=0008:0000000000241626 pc=0000000000241626 SP=0000:00000100000019d0 CR2=0000010000001a70
RAX=00000000002032ca RBX=0000000000006872 RCX=0000100000000000 RDX=0000100000000000
RSI=0000010000000000 RDI=0000018000000000 RBP=0000000000006042 RSP=00000100000019d0
R8 =0000000000000000 R9 =0000000000000002 R10=fffffffffffffffe R11=0000000000259062
R12=0000000140200000 R13=0000000000006872 R14=0000010000000000 R15=0000018000000000
RIP=0000000000241626 RFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0000 0000000000000000 00000000 00000000
DS =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
GS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000000000810b 0000001a
IDT=     0000000000000000 00000000
CR0=80010613 CR2=0000010000001a70 CR3=0000000000001000 CR4=00000620
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=00000000002001a8 CCD=00000100000019d0 CCO=SUBQ    
EFER=0000000000000d00
check_exception old: 0xe new 0xd
     1: v=08 e=0000 i=0 cpl=0 IP=0008:0000000000241626 pc=0000000000241626 SP=0000:00000100000019d0 env->regs[R_EAX]=00000000002032ca
RAX=00000000002032ca RBX=0000000000006872 RCX=0000100000000000 RDX=0000100000000000
RSI=0000010000000000 RDI=0000018000000000 RBP=0000000000006042 RSP=00000100000019d0
R8 =0000000000000000 R9 =0000000000000002 R10=fffffffffffffffe R11=0000000000259062
R12=0000000140200000 R13=0000000000006872 R14=0000010000000000 R15=0000018000000000
RIP=0000000000241626 RFL=00000002 [-------] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 0000000000000000 00000000 00209a00 DPL=0 CS64 [-R-]
SS =0000 0000000000000000 00000000 00000000
DS =0010 0000000000000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
GS =0000 0000000000000000 0000ffff 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0000 0000000000000000 0000ffff 00008b00 DPL=0 TSS64-busy
GDT=     000000000000810b 0000001a
IDT=     0000000000000000 00000000
CR0=80010613 CR2=0000010000001a70 CR3=0000000000001000 CR4=00000620
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
CCS=00000000002001a8 CCD=00000100000019d0 CCO=SUBQ    
EFER=0000000000000d00
check_exception old: 0x8 new 0xd
Triple fault
```
My kmain function has been reordered a bit; the memory manager is initialized first so that I can initialize the APIC -- which I'm working on adding. GDB shows:
```
(gdb) target remote :1234
Remote debugging using :1234
0x000000000000fff0 in ?? ()
(gdb) hb main.rs:43
Hardware assisted breakpoint 2 at 0x2076c6: file src\main.rs, line 43.
(gdb) c
Continuing.

Breakpoint 1, kernel::kmain::hf01eb38a4069227d (boot_info=0x10000000000) at src\main.rs:37
37          printkln!("Loading kernel");
(gdb) c
Continuing.

Breakpoint 2, kernel::kmain::hf01eb38a4069227d (boot_info=0x10000000000) at src\main.rs:43
43              kernel::memory::init(
(gdb) step
[Inferior 1 (process 1) exited normally]
```
I'm not quite sure why this is happening. I've committed my changes -- all of them are in the latest commit. I'm invoking QEMU like:
```
qemu-system-x86_64 -drive format=raw,file=target\x86_64-kernel-none\debug\bootimage-kernel.bin -serial stdio -no-reboot -hdb disk.img -s -m 4G -machine type=pc,kernel_irqchip=on,vmport=on,igd-passthru=on,nvdimm=on -accel tcg,thread=multi -usb -rtc base=utc,clock=host -audiodev driver=none,id=sound -cpu EPYC-v2,+apic,+acpi,+aes -smp cpus=8 -D run.log -d int,cpu_reset,guest_errors
```
Link to the repo is https://github.com/ethindp/kernel
Also, qemu does throw a lot of warnings because of this (not sure why). I've attached them in a file. I'm not sure why its throwing these, and I can't run it in HAXM or with WHPX. I've also attached the run log if that's helpful.
[run.log](https://github.com/phil-opp/blog_os/files/4526008/run.log)
[warnings.txt](https://github.com/phil-opp/blog_os/files/4526009/warnings.txt)

**Comment by ethindp** [comment]
Update: so I've managed to track down the problem -- though I have absolutely no idea what's causing it. When the init function in memory.rs is called, GDB reports (when the hardware breakpoint is hit):
```
Breakpoint 1, kernel::memory::init::h4af39683c4e98d56 (
    physical_memory_offset=<error reading variable: Cannot access memory at address 0x10000401ce8>, memory_map=<error reading variable: Cannot access memory at address 0x10000401cf0>,
    start_addr=<error reading variable: Cannot access memory at address 0x10000401cf8>)
    at src/memory.rs:161
161     pub fn init(physical_memory_offset: u64, memory_map: &'static MemoryMap, start_addr: u64) {
```
This is extremely confusing and suggests that part of the kernel is being corrupted or something. I'm using bootloader v. 0.8.9; I can't use the absolute latest version because it won't build and so cargo sees no update when I run `cargo update`. Does anyone have any idea on what's causing these memory errors?

**Comment by LiamTheProgrammer** [comment]
Interesting. In my kernel, I get a GP fault whenever I try to access memory beyond 0x13FFF. Is this the case in your kernel? Try testing access to address 0x13FFF with a breakpoint and then 0x14000, and see if it works. If not, then my issue might be of the same origin. I have tried to clear the WP bit in CR0, but it doesn't seem to affect my access to the default pages. 

I can confirm that paging is enabled by default on my kernel after the bootloader initializes.

The default value of CR0 for me in the bootloader was given at a breakpoint that I made (I'm using core and llvm_asm, not the x86_64 crate, but the interrupts work perfectly with fully-featured stack traces). To see if you are, in fact, in a very similar default environment to that of mine, please try the following code that I wrote up for my kernel to test in your kernel, and see if it fails. If not, then we are in semi-similar environments:

```rust
let cr0: usize;
llvm_asm!(
"
movq %cr0, %rax
" : "={rax}"(cr0) : : "rax" : "volatile"
);
assert_eq!(cr0, 0b10000000000000010000000000010001);
```

Further, I would guess that part of your dependencies section in your Cargo.toml would look somewhat like this in the case where this doesn't fail, but I could be wrong:

```toml
bootimage = "some_version_here"
bootloader = "some_version_here"
```

Regardless of this, though, I think this might be able to solve your problem, but I could be wrong:

```rust
lllvm_asm!(
"
movq %cr0, %rax
btrq $$16, %rax
movq %rax, %cr0
" : : : "rax" : "volatile"
);
```

Of course, in the spirit of Rust, unsafe things like this shouldn't have to be done. I hope a safer (and more accurate?) solution exists.

One thing that pops out to me in that triple fault is the state of CR3:

```
CR3=0000000000001000
```

I could be wrong, but from my understanding this implies that the PML4 is at address 0x1000 (if normal long-mode paging is being used, which should be the case when entering long mode)? If someone could clarify this, this would be quite useful. For further understanding, see chapter 5, section 3 of https://www.amd.com/system/files/TechDocs/24593.pdf and the page https://wiki.osdev.org/Long_Mode.

If you have any questions, please let me know, and I will try my best to help.

**Comment by ethindp** [comment]
I've managed to fix this (I had to split interrupts into a two stage initialization sequence). Now I'm running into a different error -- see Issue issue #815.
