### ISSUE TITLE
Use of asm! compiler warning for bootloader

### ISSUE THREAD

**Issue by ninjasource** [phil-opp/blog_os#800]
Hi, thank you for your superb series. 

I have been following the Testing post https://os.phil-opp.com/testing/ and am getting a compiler warning ```warning: use of deprecated item 'asm': the syntax of asm! will change soon, use llvm_asm! to avoid breakage``` on the bootloader dependency (bootloader-0.8.9). I see that this has been fixed in newer versions of the bootloader-0.9.x. However, updating to bootloader-0.9.2 results in a compilation error ```error[E0461]: couldn't find crate `core` with expected target triple x86_64-bootloader-1500151150070471549```. Is there a way to disable the warning as having ```#![allow(deprecated)]``` in main.rs does not work I assume because the warning originates from the compilation of bootloader itself. This warning appears 6 times and adds quite a bit of noise to the test results. 

Thanks again,
David

**Comment by bjorn3** [comment]
Try updating the `x86_64` crate to `v0.10.2` or later. (https://github.com/rust-osdev/x86_64/pull/151)

**Comment by bjorn3** [comment]
> However, updating to bootloader-0.9.2 results in a compilation error error[E0461]: couldn't find crate `core` with expected target triple x86_64-bootloader-1500151150070471549.

Does `cargo clean` solve this?

**Comment by ninjasource** [comment]
Yes that solved it, thank you so much!

**Comment by phil-opp** [comment]
Sorry for the hassle! I will update the blog to the newest bootloader when I have some spare time.

The error that occured after updating the bootloader is a known issue. We're currently working on a rewrite of the bootloader that – among other things – will switch from `cargo-xbuild` to cargo's own `-Z build-std` flag. This should fix that issue.
