### ISSUE TITLE
A ton of QEMU warnings, then QEMU terminates

### ISSUE THREAD

**Issue by ethindp** [phil-opp/blog_os#803]
I have no idea what's causing this. I'm launching QEMU with:
```
qemu-system-x86_64 -drive format=raw,file=target\x86_64-kernel-none\debug\bootimage-kernel.bin -serial stdio -no-reboot -hdb disk.img -s -m 4G -usb -rtc base=utc,clock=host -audiodev driver=none,id=sound -cpu EPYC-v2,+apic,+acpi -smp cpus=8
```
I used to run it with +aes on there as well, but I thought that was the problem. However, its not. Qemu still gives the below warnings, then immediately terminates; there is no reason that I can find (even with GDB) that explains this problem. The warnings follow:
```
warning: GdkPixbuf: Cannot open pixbuf loader module file 'C:\Users\ethin\scoop\apps\qemu\current\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > C:\Users\ethin\scoop\apps\qemu\current\lib\gdk-pixbuf-2.0\2.10.0\loaders.cache
to make things work again for the time being.
```
This warning I don't worry too much about. I think the warnings that follow hint to the problem (though I have no idea why its bringing them up now). They state that TCG doesn't support a ton of CPUID features; the features that it supposedly doesn't support are FMA, AVX, F16C, AVX2, RDSEED, SHA-NI, FXSR-opt, Misaligned SSE, 3D Now! prefetch, OS Visible Workaround, Topology Extensions, IBPB, NRIP-save, and XSAVEC. Is there any reason that TCG wouldn't support these features, or why they're being requested? I'm not asking for these features in my kernels target JSON, and to my knowledge none of the crates I'm using requires them. Even so, I can't imagine why this would be causing my kernel to triple fault unexpectedly.

**Comment by phil-opp** [comment]
This issue seems to be very QEMU-specific, so I would recommend to try reinstalling QEMU following the suggestion mentioned in the error message. If it persists, it might make sense to report the issue on the [QEMU bugtracker](https://bugs.launchpad.net/qemu/) if it persists or use one of the other [QEMU support channels](https://www.qemu.org/support/) (e.g. IRC).
