### ISSUE TITLE
write! macro doesn't work on VGA Text Mode tutorial

### ISSUE THREAD

**Issue by thorlucas** [phil-opp/blog_os#824]
On the [VGA Text Mode tutorial](https://os.phil-opp.com/vga-text-mode/), we implement `fmt::Write` by implementing `write_str`. The article claims that then the `write!` macro will work.

However, when compiling, we get this:

```
method `write_fmt` not found for this
```

So we actually need to implement `write_fmt`. I'm unsure of how to implement this without using the `format!` macro.

**Comment by phil-opp** [comment]
Did you import the `fmt::Write` trait? Trait methods are only callable when the trait is imported, so this might be the problem. To import the trait, add the following at the top of the file or at the top of the body of the `print_something` function:

```rust
use core::fmt::Write;
```

**Comment by thorlucas** [comment]
It works! I must have missed that. Thanks,

**Comment by phil-opp** [comment]
Good to hear that!
