### ISSUE TITLE
source code for the old tutorials

### ISSUE THREAD

**Issue by caelwithcats** [phil-opp/blog_os#874]
I am following the first edition tutorial, Entering Long Mode, I want to have a look at the source code but the only code I can find on this repo is the new tutorials. I wonder if you have the source code for the old tutorials.

Thanks for the great tutorials :heart:

**Comment by phil-opp** [comment]
The source code for the first edition posts is available through git tags named `first_edition_post_x` where `x` is the post number. See the [Readme section on the first edition](https://github.com/phil-opp/blog_os#first-edition-posts) for source code links for all posts. Keep in mind that this code hasn't been updated for a long time, so it might no longer work.

**Comment by caelwithcats** [comment]
@phil-opp thanks
