### ISSUE TITLE
GDB Debugging

### ISSUE THREAD

**Issue by Luis-Hebendanz** [phil-opp/blog_os#876]
Hello,

I am currently trying to get gdb + qemu to work. My current setup is:
```
$ qemu-kvm -drive format=raw,file=target/x86_64-os/debug/bootimage-svm_kernel.bin -nographic -s -S
$ rust-gdb target/x86_64-os/debug/svm_kernel -ex "target remote:1234"
```

The symbols are getting read correctly and the memory locations are also working. However breakpoints do not work. 
I know now why but I don't have an idea how to fix it. If you set breakpoints these breakpoints get overridden by the bootloader loading the kernel code into memory. Do you have an idea how to fix this @phil-opp?

**Comment by phil-opp** [comment]
Are you setting breakpoints on function names or via the file+line syntax? The latter normally works fine for me.

**Comment by Luis-Hebendanz** [comment]
Hmm I tried both and neither works for me:
```gdb
(gdb) b src/main.rs:75
(gdb) b svm_kernel::kernel_main
```

**Comment by phil-opp** [comment]
Hmm, then maybe this is related to the GDB/QEMU versions. I'm using:

```
> qemu-system-x86_64 --version
QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.7)

> gdb-multiarch --version
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
```

**Comment by Luis-Hebendanz** [comment]
I tried gdb 9.2 but sadly that isn't the problem. Do you use the bootloader as a crate in your project or have you it inlined into the kernel?
If you start gdb and connect to qemu does gdb show you the bootloader source code or does it point to a blank code page filled with 0 (in asm `add    BYTE PTR [rax], al`) ?
Because for me it's the second one

**Comment by phil-opp** [comment]
I just tried it again on the `post-12` branch and it worked without problems. Here is what I did in detail:

Run `cargo run -- -s -S`. In another terminal window, run `gdb-multiarch` (no arguments). Then, enter the following commands in the GDB prompt:

```
(gdb) file target/x86_64-blog_os/debug/blog_os
Reading symbols from target/x86_64-blog_os/debug/blog_os...
(gdb) tar ext :1234
Remote debugging using :1234
0x000000000000fff0 in ?? ()
(gdb) b kernel_main
Breakpoint 1 at 0x20a58d: file src/main.rs, line 21.
(gdb) c
Continuing.

Breakpoint 1, blog_os::kernel_main (boot_info=0x10000000000) at src/main.rs:21
21	    println!("Hello World{}", "!");
(gdb) 
```

**Comment by phil-opp** [comment]
> Thanks for your help btw., your blog is super awesome :-)

Thank you, I'm glad that you like it :)

**Comment by robert-w-gries** [comment]
I just got GDB working following this [old post](https://os.phil-opp.com/set-up-gdb/), but it seems you two are using a different set of instructions? I'm happy to try reproducing/testing gdb for my kernel too if @Luis-Hebendanz is still having issues

**Comment by phil-opp** [comment]
@robert-w-gries The problem described in the "The annoying issue" section of this post does no longer happen for me. The native `gdb-multiarch`/`rust-gdb` work fine for me.

@Luis-Hebendanz I also tried running QEMU with `--nographic` and using `rust-gdb` instead of `gdb-multiarch` and the steps I mentioned above still work for me. I also tried the `post-02` branch and it also works when I set the breakpoint on `_start` (the `kernel_main` function does not exist yet at this point).

**Comment by Luis-Hebendanz** [comment]
Hmm I see, I will clone your sample repo and then diff it with my implementation till I got the error ^^

**Comment by Luis-Hebendanz** [comment]
Ah I found the culprit, I use qemu-kvm instead  of qemu-system-x86_64 then gdb can't set breakpoints! I wonder why? Can somebody reproduce this?

**Comment by ethindp** [comment]
Try hardware breakpoints (hb instead of b). Perhaps that'll fix things.

On 10/31/20, Luis Hebendanz <notifications@github.com> wrote:
> Ah I found the culprit, I use qemu-kvm instead  of qemu-system-x86_64 then
> gdb can't set breakpoints! I wonder why? Can somebody reproduce this?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/876#issuecomment-719989352


-- 
Signed,
Ethin D. Probst

**Comment by Luis-Hebendanz** [comment]
@ethindp That's it! Thank you so much!
