### ISSUE TITLE
Show other translations on posts sidebar

### ISSUE THREAD

**Issue by hamidrezakp** [phil-opp/blog_os#879]
Hello,
Currently the posts that have translations, their sidebar `other languages` section is `hidden`; why is that?

I think the correct way is to show all of other translations available for a post so users can use translations.

**Comment by phil-opp** [comment]
We use javascript to display only the languages that the user enabled in their browser:

https://github.com/phil-opp/blog_os/blob/307916d1fe81b5c4a9ef0d4d0f5dcbba74e31a1c/blog/static/js/main.js#L67-L79

**Comment by hamidrezakp** [comment]
Oh, that is nice, i didn't know this feature exist in my browse :D.
A lot of people also don't know, maybe we can somehow show available languages.

**Comment by phil-opp** [comment]
Good point! I guess we can just remove that logic and always show all available languages for now, to make the translations more discoverable. If the number of translations grows significantly in the future, we can reintroduce some form of language detection again. 

I opened #880 to implement this.

**Comment by hamidrezakp** [comment]
nice, i will work on it.
