### ISSUE TITLE
The website should have dark mode.

### ISSUE THREAD

**Issue by ergpopler** [phil-opp/blog_os#884]
https://os.phil-opp.com should have a dark mode feature.

I am trying to read it and it is burning my eyes.

**Comment by phil-opp** [comment]
I agree that this is something that would be nice to have. I added this issue to my backlog.

**Comment by mt-rainier** [comment]
@ergpopler , try https://darkreader.org/.

**Comment by ergpopler** [comment]
Generally dark extensions make websites look like shit, this one isn't bad though, thanks.

**Comment by lucsm00** [comment]
What about the Nordic color theme? https://www.nordtheme.com/

**Comment by spy653** [comment]
> Generally dark extensions make websites look like shit, this one isn't bad though, thanks.

Dark Reader is generally considered the best out there, I have major light sensitivity and by fiddling with the settings a bit for different sites it can be practically perfect.

**Comment by hamidrezakp** [comment]
What is status of this issue? do you need any help @phil-opp ?

**Comment by phil-opp** [comment]
I already implemented a basic dark mode for the upcoming third edition. It currently looks like this:

![image](https://user-images.githubusercontent.com/1131315/107119524-67b9c180-6888-11eb-877e-15e981f5c573.png)


I'm not sure yet whether I'll add it to the older editions too, as it would probably require to recreate some graphics.

**Comment by hamidrezakp** [comment]
This is cool, i like it, is there any switch to turn it on or off?
yeah we need to use different graphics for dark mode.

**Comment by phil-opp** [comment]
Yes, there's a switch to toggle between dark and light mode, a little moon/sun icon in the lower left corner of the page. By default, it uses the theme you set as preference in your OS settings.

**Comment by workingJ** [comment]
Hi, i would like to create the needed images for the dark mode.
For what i have seen, the ones that are needed to be changed are all svg's.
I tried out white background strokes for the text and arrows but it does not look grate.
So, shall i create for every image a dark version?

**Comment by phil-opp** [comment]
@workingJ Thanks a lot for the offer! However, I don't think that it makes sense to start this work yet. We should first merge the dark mode support, then we can gradually improve the images that don't look good. Ideally, we find a way to use the same images for both the light and dark mode, e.g. by using CSS styling. Unfortunately, I'm relatively busy right now, but I try to look into this soon!

**Comment by workingJ** [comment]
@phil-opp Ok, i am still around if you want help in this matter.
