### ISSUE TITLE
Persian translation of chapters Interrupts and Memory Managements

### ISSUE THREAD

**Issue by hamidrezakp** [phil-opp/blog_os#902]
Me and @MHBahrampour are working on translations of chapters `Interrupts` and `Memory Managements`.
the `Interrupts` chapter is almost done and will be soon a PR.
So anyone interested in helping, let me know so you don't do any duplicate.

**Comment by hamidrezakp** [comment]
Translation of chapter interrupts is done in #904.
Thanks to @MHBahrampour for helping in translations.

**Comment by hamidrezakp** [comment]
Translation of post-08 is done in #913.

**Comment by hecatia-elegua** [comment]
done / #908 will handle the rest
