### ISSUE TITLE
Double fault in post-08 branch code

### ISSUE THREAD

**Issue by hamidrezakp** [phil-opp/blog_os#923]
Hi,
There is a problem in post-08 code.
Instead of printing following:
```
Level 4 page table at: PhysAddr(0x1000)
```
This will get printed:
```
panicked at `EXEPTION: DOUBLE FAULT
InterruptStackFrame {

```

**Comment by phil-opp** [comment]
I just tried the `post-08` code again and it works as expected for me:

![image](https://user-images.githubusercontent.com/1131315/107022456-b3e00580-67a5-11eb-88ba-47543d7cc3bd.png)

Are you running the `post-08` branch without modifications? Which Rust and QEMU versions do you use?

**Comment by hamidrezakp** [comment]
Oh, strange.
Here is my versions:
QEMU: 5.2.0
Rust: 1.51.0-nightly

I just updated with `rustup update` and did a `cargo update` and cloned the branch but it was like before and same error.

**Comment by phil-opp** [comment]
That's strange. I'm using QEMU 5.0.0, maybe that's the reason for the different behavior.

**Comment by hamidrezakp** [comment]
Ok, I have done some tests here are results:
On a fresh install Alpine linux: It Works!
- Rust: 1.52.0-nightly
- QEMU: 5.2.0

I have the same versions on my Archlinux.
The strange thing is the boot image file that i have build in Alpine linux differs from what i have build in Archlinux and when i run the Alpine one in Archlinux, it works!.

So the problem is not with qemu, maybe some of my tools are old, do you have any idea to look after what?
also, my `bootimage` tool is the same version on both systems.

**Comment by hamidrezakp** [comment]
I checked their hex and they are two different files.

**Comment by phil-opp** [comment]
Could you post your exact nightly versions, e.g. the full output of `rustc --version`? There are multiple 1.52.0-nightly releases, so the part in parentheses (e.g. `(a73c2e555 2021-02-06)`) is important as well.

**Comment by hamidrezakp** [comment]
Sure. here it is:
The system that does *not* work: rustc 1.52.0 (9778068cb 2021-02-07)
The system that does work: rustc 1.52.0-nightly (a73c2e555 2021-02-06)

**Comment by phil-opp** [comment]
Hmm, both versions are very recent, so I don't think that this is the problem. Are you sure that you're running the `post-xx` branch of blog_os without modifications?

**Comment by hamidrezakp** [comment]
Yeah, every time i will clone the repo and checkout the branch.

**Comment by hamidrezakp** [comment]
I have found the problem 🤣 . Sorry for taking your time.
It was an environment variable that made the build wrong.
`RUSTFLAGS="-C target-cpu=native"` in my `~/.pam_environment`

I did `rustup self uninstall` and installed again all of rust and cargo tools and checked all environment and config files to find this problem.
So i will close the issue.

**Comment by phil-opp** [comment]
Thanks for the update!
