### ISSUE TITLE
Not working in cargo build

### ISSUE THREAD

**Issue by JakubGawron23** [phil-opp/blog_os#924]
Hello. I wanted to build this system from branch 12 but after executing the command ```cargo build``` the compiler spat out errors and nothing works. My computer system is Windows 10 insider preview. Thanks in advance for your help.

**Comment by phil-opp** [comment]
Could you post the full error message please?

**Comment by JakubGawron23** [comment]
> Could you post the full error message please?

yes, but not today because I'm at work

**Comment by phil-opp** [comment]
Thanks!

**Comment by RisuSofos** [comment]
Not sure if this is the answer you are looking for but I hear its a good place to start when you have issues with cargo run.

I recently had an issue where the project would build and run in test mode but not with `cargo run` 
I solved this issue by deleting target/ and re-building the project.

**Comment by JakubGawron23** [comment]
I'm sorry that I was away for so long but I tried to run it on WSL and it was succesful .Now I will try again on Windows

**Comment by JakubGawron23** [comment]
Wow. Today I can run this OS in Windows 10.

**Comment by JakubGawron23** [comment]
Despite the fact that system starts up, I get such warmings. How can this be fixed. Warnings are highlighted in white.
![Zrzut ekranu (58)](https://user-images.githubusercontent.com/76694285/108046143-96802680-7044-11eb-811d-5135ca5b50af.png)

**Comment by phil-opp** [comment]
Great to hear that! 

You can fix the `wake_trait` warning by removing the line from your `lib.rs`. This feature is stable now, so the feature gate is no longer needed.

The other warning originates in the `bootloader` crate. I'll try to fix it soon.
