### ISSUE TITLE
cargo build difference on "cargo build --target thumbv7em-none-eabihf" and cargo build --target x86_64-blog_os.json

### ISSUE THREAD

**Issue by Josh7GAS** [phil-opp/blog_os#925]
Guys I had followed the previous tips and instructions, but I got stuck whit this error when trying to build the code:

Command: cargo build --target x86_64-rust_os.json
Output: cargo build --target x86_64-rust_os.json 
error: cannot produce bin for `rust_os v0.1.0 (/home/josh7gas/github.com/Josh7GAS/Oficina/Rust/Rust_OS/rust_os)` as the target `x86_64-rust_os` does not support these crate types

So I locked over end over, then I've remembered that we could I was able to build the project using "cargo build --target thumbv7em-none-eabihf" and it works.

Output: cargo build --target thumbv7em-none-eabihf
   Compiling compiler_builtins v0.1.39
   Compiling core v0.0.0 (/home/josh7gas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling rustc-std-workspace-core v1.99.0 (/home/josh7gas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
   Compiling rust_os v0.1.0 (/home/josh7gas/github.com/Josh7GAS/Oficina/Rust/Rust_OS/rust_os)
    Finished dev [unoptimized + debuginfo] target(s) in 11.54s

Now my doubt is why it had worked with the last command? and not with the first one, is because is to run on a bare-metal env?

**Comment by ethindp** [comment]
The bootloader crate wasn't built to run on ARM. Unless you use a
different bootloader and a different set of crates for the
architecture, its not going to boot because it contains x86-specific
assembly.
As for why it doesn't build with the first command, make sure that
your build target is in the same directory.

On 2/5/21, Josh7GAS <notifications@github.com> wrote:
> Guys I had followed the previous tips and instructions, but I got stuck whit
> this error when trying to build the code:
>
> Command: cargo build --target x86_64-rust_os.json
> Output: cargo build --target x86_64-rust_os.json
> error: cannot produce bin for `rust_os v0.1.0
> (/home/josh7gas/github.com/Josh7GAS/Oficina/Rust/Rust_OS/rust_os)` as the
> target `x86_64-rust_os` does not support these crate types
>
> So I locked over end over, then I've remembered that we could I was able to
> build the project using "cargo build --target thumbv7em-none-eabihf" and it
> works.
>
> Output: cargo build --target thumbv7em-none-eabihf
>    Compiling compiler_builtins v0.1.39
>    Compiling core v0.0.0
> (/home/josh7gas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
>    Compiling rustc-std-workspace-core v1.99.0
> (/home/josh7gas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)
>    Compiling rust_os v0.1.0
> (/home/josh7gas/github.com/Josh7GAS/Oficina/Rust/Rust_OS/rust_os)
>     Finished dev [unoptimized + debuginfo] target(s) in 11.54s
>
> Now my doubt is why it had worked with the last command? and not with the
> first one, is because is to run on a bare-metal env?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/925


-- 
Signed,
Ethin D. Probst

**Comment by phil-opp** [comment]
@Josh7GAS You're likely missing the `"executables": true` key in your custom `x86_64-rust-os` target.

**Comment by Josh7GAS** [comment]
> The bootloader crate wasn't built to run on ARM. Unless you use a different bootloader and a different set of crates for the architecture, its not going to boot because it contains x86-specific assembly. As for why it doesn't build with the first command, make sure that your build target is in the same directory.
> […](#)
> On 2/5/21, Josh7GAS ***@***.***> wrote: Guys I had followed the previous tips and instructions, but I got stuck whit this error when trying to build the code: Command: cargo build --target x86_64-rust_os.json Output: cargo build --target x86_64-rust_os.json error: cannot produce bin for `rust_os v0.1.0 (/home/josh7gas/github.com/Josh7GAS/Oficina/Rust/Rust_OS/rust_os)` as the target `x86_64-rust_os` does not support these crate types So I locked over end over, then I've remembered that we could I was able to build the project using "cargo build --target thumbv7em-none-eabihf" and it works. Output: cargo build --target thumbv7em-none-eabihf Compiling compiler_builtins v0.1.39 Compiling core v0.0.0 (/home/josh7gas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core) Compiling rustc-std-workspace-core v1.99.0 (/home/josh7gas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core) Compiling rust_os v0.1.0 (/home/josh7gas/github.com/Josh7GAS/Oficina/Rust/Rust_OS/rust_os) Finished dev [unoptimized + debuginfo] target(s) in 11.54s Now my doubt is why it had worked with the last command? and not with the first one, is because is to run on a bare-metal env? -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #925
> -- Signed, Ethin D. Probst

The command is running on the same directory of the target

**Comment by Josh7GAS** [comment]
> @Josh7GAS You're likely missing the `"executables": true` key in your custom `x86_64-rust-os` target.
here is the "x86_64-rust-os"

{
    "llvm-target": "x86_64-unknown-none",
    "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
    "arch": "x86_64",
    "target-endian": "little",
    "target-pointer-width": "64",
    "target-c-int-width": "32",
    "os": "none",
    "executables": true,
    "linker-flavor": "ld.lld",
    "linker": "rust-lld",
    "panic-strategy": "abort",
    "disable-redzone": true,
    "features": "-mmx,-sse,+soft-float"
}

the "executables" key is set to "true" and still no deal, I´ll keep looking deep to my files and the documentation.

cargo build --target x86_64-rust_os.json                 error: cannot produce bin for `rust_os v0.1.0 (D:\github.com\Josh7GAS\Oficina\Rust\Rust_OS\rust_os)` as the target `x86_64-rust_os` does not support these crate types

**Comment by phil-opp** [comment]
@Josh7GAS I just looked through your `Oficina` GitHub project and it looks like you use `"executable": true` (singular) instead of `"executables": true` (plural): https://github.com/Josh7GAS/Oficina/blob/d73a7ed9b44c1a9794507ff7e932f06b4b368670/Rust/Rust_OS/rust_os/x86_64-rust_os.json#L8

Unfortunately, target JSON files are not checked for unknown keys by Rust, so no error or warning occurs, they are just ignored.

**Comment by phil-opp** [comment]
Also there seems to be another typo [in the `features` list](https://github.com/Josh7GAS/Oficina/blob/d73a7ed9b44c1a9794507ff7e932f06b4b368670/Rust/Rust_OS/rust_os/x86_64-rust_os.json#L13). It should be `-mmx` instead of `-mx`. This is not related to the error you're seeing, but I thought I mention it as well.

**Comment by Josh7GAS** [comment]
Phill, greetings.

I´ve changed the file on github as well, and still stuck

`D:\github.com\Josh7GAS\Oficina\Rust\Rust_OS\rust_os> Get-Content .\x86_64-rust_os.json                        {                                                                                                                                 "llvm-target": "x86_64-unknown-none",                                                                                           "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",                                                                         "arch": "x86_64",                                                                                                               "target-endian": "little",                                                                                                      "target-pointer-width": "64",                                                                                                   "target-c-int-width": "32",                                                                                                     "os": "none",                                                                                                                   "executables": true,                                                                                                            "linker-flavor": "ld.lld",                                                                                                      "linker": "rust-lld",                                                                                                           "panic-strategy": "abort",                                                                                                      "disable-redzone": true,                                                                                                        "features": "-mmx,-sse,+soft-float"                                                                                           }                                                                                                                               PS D:\github.com\Josh7GAS\Oficina\Rust\Rust_OS\rust_os> cargo build --target x86_64-rust_os.json                 error: cannot produce bin for `rust_os v0.1.0 (D:\Users\re92331z\github.com\Josh7GAS\Oficina\Rust\Rust_OS\rust_os)` as the target `x86_64-rust_os` does not support these crate types     `

**Comment by phil-opp** [comment]
I just downloaded your repo to try it myself, but the repo is _enormous_ (~2GB). Just so that you know, it is not recommended to commit Rust's `target` folder to git. It contains not only the compiled files, but also lots of temporary build files, and can grow to multiple gigabytes in size.

That being said, I was able to compile your project without any problems. I used the following build command:

```
cargo +nightly build --target x86_64-rust_os.json -Zbuild-std=core
```

This completed without any errors.

Are you sure that you compiled using the correct target JSON file? Please also try to remove the `target` subfolder and then trying again.

**Comment by Josh7GAS** [comment]
Phil, greetings.

Thanks for your time and effort on this, it work it!

Sorry to bother.
