### ISSUE TITLE
Translate "Paging Implementation" into Japanese

### ISSUE THREAD

**Issue by hikalium** [phil-opp/blog_os#931]
I'll translate [Paging Implementation](https://os.phil-opp.com/paging-implementation/) into Japanese and this is a tracking issue for it.
Please let me know if anyone has already started translating it so that we can avoid duplicate works.

#906

**Comment by phil-opp** [comment]
Is this still up-to-date?

**Comment by hikalium** [comment]
Ah sorry, I have been busy recently so closing the issue for now to make it available 🙏 
(Anyway, thanks for the great articles around Rust + OS! I'll contribute again when I have a time...)
