### ISSUE TITLE
This Month in Rust OSDev (January 2021) does not appear in the status updates section

### ISSUE THREAD

**Issue by toothbrush7777777** [phil-opp/blog_os#933]
![Example](https://user-images.githubusercontent.com/8356617/109156461-c7f5a200-7768-11eb-8d11-7b7ebcb8c387.png)

**Comment by phil-opp** [comment]
Thanks for reporting! Seems like our script accidentally starts a new year with month number 0 :smile::

https://github.com/phil-opp/blog_os/blob/9d381723ed7075d6e1405e7ae2a0ae17680f5cfa/blog/before_build.py#L72

I'll push a fix in a minute.

**Comment by phil-opp** [comment]
Fixed in https://github.com/phil-opp/blog_os/commit/15ae425a6b99ad7132a0da65baa267f6327c3d68.
