### ISSUE TITLE
Qemu: could not load PC BIOS 'bios-256k.bin

### ISSUE THREAD

**Issue by JakubGawron23** [phil-opp/blog_os#936]
Sorry to keep creating new problems, but on my friend's computer I wanted to build a kernel, but it spat out errors like this:
![Zrzut ekranu (1)](https://user-images.githubusercontent.com/76694285/109420641-e4494700-79d3-11eb-8366-81a0ca8f6b24.png)
![Zrzut ekranu (2)](https://user-images.githubusercontent.com/76694285/109420656-f2976300-79d3-11eb-92fe-bff4ea386ba8.png)
How to fix it :(

**Comment by 12101111** [comment]
This file is part of qemu.
![image](https://user-images.githubusercontent.com/8438475/109421681-44aba900-7a13-11eb-96d3-260d793009ff.png)
Just reinstall qemu.

**Comment by phil-opp** [comment]
This is a known issue with the latest qemu version: https://bugs.launchpad.net/qemu/+bug/1915794

I hope that it gets fixed soon. Until then, you can try starting QEMU directly from its installation dir, or temporarily use an older version.
