### ISSUE TITLE
post-02 code no longer working - github actions also failing

### ISSUE THREAD

**Issue by schafezp** [phil-opp/blog_os#942]
I'm seeing an error when I try to run post-02 on qemu at the very end of the post. I got the same error when cloning the post-02 solution. I saw the same error on the Github Actions nightly build. I suspect something changed on rust nightly?

The error on local,

```
 = note: rust-lld: error: bootloader.ew8rconr-cgu.1:(.boot-first-stage+0x81): relocation R_X86_64_16 out of range: 87040 is not in [-32768, 65535]; references _rest_of_bootloader_end_addr
rust-lld: error: bootloader.ew8rconr-cgu.1:(.boot+0x6A): relocation R_X86_64_16 out of range: 87040 is not in [-32768, 65535]; references _kernel_start_addr
>>> defined in /Users/HOMEUSER//blog_os/target/bootimage/bootloader/x86_64-bootloader/release/deps/libbootloader-8ac18532d8298d1d.rlib(kernel_bin-blog_os.o)
```

Here is the github action, seems like its been failing for a little while now. https://github.com/phil-opp/blog_os/runs/2072692829?check_suite_focus=true and the log,
```
 = note: rust-lld: error: bootloader.4qapia1c-cgu.0:(.boot+0x6A): relocation R_X86_64_16 out of range: 88576 is not in [-32768, 65535]; references _kernel_start_addr
>>> defined in /home/runner/work/blog_os/blog_os/target/bootimage/bootloader/x86_64-bootloader/release/deps/libbootloader-0765bc7ffa1f3620.rlib(kernel_bin-blog_os.o)
rust-lld: error: bootloader.4qapia1c-cgu.0:(.boot+0x85): relocation R_X86_64_16 out of range: 365520 is not in [-32768, 65535]; references _kernel_size
```

Here is the post-02 code: https://github.com/phil-opp/blog_os/tree/post-02

Does anyone know what the cause of this issue is, and how it can be fixed? I would love to get Hello World working :) 

Thank you!

**Comment by bjorn3** [comment]
This should be fixed with the latest bootloader version.

**Comment by phil-opp** [comment]
> This should be fixed with the latest bootloader version.

Yes, try running `cargo update -p bootloader`. I just did that for the `post-02` (and other `post-xx` branches), so the CI should work now again, at least on Linux. (On Windows there is [currently a bug in the latest QEMU version](https://bugs.launchpad.net/qemu/+bug/1915794).)

**Comment by phil-opp** [comment]
This issue should be fixed.
