### ISSUE TITLE
https://os.phil-opp.com/testing/#completing-the-integration-test

### ISSUE THREAD

**Issue by alexxroche** [phil-opp/blog_os#945]
[I really like this guide]  When I got to #completing-the-integration-test

When I added
```rust
#![test_runner(blog_os::test_runner)]
//...
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    blog_os::test_panic_handler(info)
}
```
to `tests/basic_boot.rs`  it felt like I had to remove:

```patch
-#![test_runner(crate::test_runner)]

-fn test_runner(tests: &[&dyn Fn()]) {
-    unimplemented!();
-}
```
Is that intended?  https://github.com/phil-opp/blog_os/blob/post-04-no-more-bootimage/tests/basic_boot.rs suggests that is the case, but I missed the instruction to remove these on https://os.phil-opp.com/testing/#completing-the-integration-test

(It might be that this has been deliberately omitted for the student to explore and discover, and that would be an understandable choice.)

**Comment by phil-opp** [comment]
Thanks for reporting! I agree that we could make this more clear.
