### ISSUE TITLE
QEMU booting in endless loop

### ISSUE THREAD

**Issue by CypElf** [phil-opp/blog_os#946]
I'm currently trying to make the Hello World example working on my Windows machine. But when I run `qemu-system-x86_64 -drive format=raw,file=target\x86_64-nos\debug\bootimage-nos.bin`, I get this on QEMU :

![image](https://user-images.githubusercontent.com/31732086/111875232-03b30e80-8999-11eb-9b50-45eb8707d244.png)

And it's blinking, re printing these lines infinitely.
I'm using rustc 1.52.0-nightly and QEMU 5.1.92 (a december 2020 version, not the latest because of another known pending issue about bios256k.bin, but it didn't work in the latest as well anyway).

**Comment by CypElf** [comment]
Sorry the the unnecessary issue, it was caused by 4 zeros instead of 3 in the vga_buffer adress.

**Comment by phil-opp** [comment]
No worries, thanks for letting us know what the problem was.
