### ISSUE TITLE
Some one is use github action to run miner !!!

### ISSUE THREAD

**Issue by longwusha** [phil-opp/blog_os#968]
@phil-opp 

Please have a look at #967 , I think we should close this bad PR and forbid the author of this PR to create PR in all projects you can control.

This PR has used GitHub action to run the mining program(https://github.com/xmrig/xmrig) for many times. You don't need to merge this PR, as long as he reopen and close the PR repeatedly, it can trigger the operation

I saw on the news today that this is a bug of GitHub that has not been fixed. With this bug people can run mining programs through GitHub action. This is a very bad thing, it will waste a lot of GitHub action computing resources, which is not conducive to the normal operation of CI / CD of other normal projects.

**Comment by bjorn3** [comment]
All actions have been canceled already. By @phil-opp I guess. I also reported the user to github myself.

**Comment by phil-opp** [comment]
Thanks a lot for reporting! I noticed it as well and immediately canceled the CI run and reported the user on GitHub. Then they opened and closed the PR repeatedly to trigger lots of new CI jobs. I locked the PR to prevent this in the future and canceled all the active jobs manually. Let's hope that Github acts quickly and suspends the user, given that our project is not the only target.
