### ISSUE TITLE
How to enter user space?

### ISSUE THREAD

**Issue by arrayJY** [phil-opp/blog_os#970]
I'm working on my own kernel based on `blog_os`. I have done the work in post 1 to 11 of [Writing an OS in Rust](https://os.phil-opp.com/). Now I try to enter user space with `iretq`, using following codes:
```rust
unsafe {
    load_ds(user_data_seg);
    load_es(user_data_seg);
    asm!("mov rdx, {}", in (reg) user_stack);
    asm!("mov rsi, {}", in (reg) user_entry_point);
    asm!("push 0x1b");  // User data segment
    asm!("push rdx");   // User space stack
    asm!("push 0x202"); // RFlags
    asm!("push 0x23");  // User code segment
    asm!("push rsi");   // User entry point
    asm!("iretq")
}
```
After calling `iretq`, it jumps to `user_entry_point`.  The registers(`ss=ds=es=0x1b`, `cs=0x23`) seems been setted correctly. But double fault occurs when calling the next instruction(the first instruction in `user_entry_point`).

How can I enter user space correctly? Is anything important I forgot?

**Comment by ethindp** [comment]
I doubt this is actually going to work the way you want. Your doing
this in a rust function, so Rust is going to add its own stuff before
those instructions and after it. The double fault probably occurs
because rust is setting up a stack and then failing to fix it
afterwards because of your iretq. You can either write that in
assembly or use #[naked]. I don't know if #[naked] would fix it,
though, but you can try.

On 4/9/21, arrayJY ***@***.***> wrote:
> I'm working on my own kernel based on `blog_os`. I have done the work in
> post 1 to 11 of [Writing an OS in Rust](https://os.phil-opp.com/). Now I try
> to enter user space with `iretq`, using following codes:
> ```rust
> unsafe {
>     load_ds(user_data_seg);
>     load_es(user_data_seg);
>     asm!("mov rdx, {}", in (reg) user_stack);
>     asm!("mov rsi, {}", in (reg) user_entry_point);
>     asm!("push 0x1b");  // User data segment
>     asm!("push rdx");   // User space stack
>     asm!("push 0x202"); // RFlags
>     asm!("push 0x23");  // User code segment
>     asm!("push rsi");   // User entry point
>     asm!("iretq")
> }
> ```
> After calling `iretq`, it jumps to `user_entry_point`.  The
> registers(`ss=ds=es=0x1b`, `cs=0x23`) seems been setted correctly. But
> double fault occurs when calling the next instruction(the first instruction
> in `user_entry_point`).
>
> How can I enter user space correctly? Is anything important I forgot?
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/phil-opp/blog_os/issues/970


-- 
Signed,
Ethin D. Probst

**Comment by ethindp** [comment]
Also, you may wish to fill out the rest of yoru IDT. That'll tell you
explicitly what's wrong. The #DF isn't very helpful, and so I can only
speculate.

On 4/9/21, Ethin Probst ***@***.***> wrote:
> I doubt this is actually going to work the way you want. Your doing
> this in a rust function, so Rust is going to add its own stuff before
> those instructions and after it. The double fault probably occurs
> because rust is setting up a stack and then failing to fix it
> afterwards because of your iretq. You can either write that in
> assembly or use #[naked]. I don't know if #[naked] would fix it,
> though, but you can try.
>
> On 4/9/21, arrayJY ***@***.***> wrote:
>> I'm working on my own kernel based on `blog_os`. I have done the work in
>> post 1 to 11 of [Writing an OS in Rust](https://os.phil-opp.com/). Now I
>> try
>> to enter user space with `iretq`, using following codes:
>> ```rust
>> unsafe {
>>     load_ds(user_data_seg);
>>     load_es(user_data_seg);
>>     asm!("mov rdx, {}", in (reg) user_stack);
>>     asm!("mov rsi, {}", in (reg) user_entry_point);
>>     asm!("push 0x1b");  // User data segment
>>     asm!("push rdx");   // User space stack
>>     asm!("push 0x202"); // RFlags
>>     asm!("push 0x23");  // User code segment
>>     asm!("push rsi");   // User entry point
>>     asm!("iretq")
>> }
>> ```
>> After calling `iretq`, it jumps to `user_entry_point`.  The
>> registers(`ss=ds=es=0x1b`, `cs=0x23`) seems been setted correctly. But
>> double fault occurs when calling the next instruction(the first
>> instruction
>> in `user_entry_point`).
>>
>> How can I enter user space correctly? Is anything important I forgot?
>>
>>
>> --
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/phil-opp/blog_os/issues/970
>
>
> --
> Signed,
> Ethin D. Probst
>


-- 
Signed,
Ethin D. Probst

**Comment by bjorn3** [comment]
You must put all instructions in a single asm block. This may not fix the problem, but right now rustc and LLVM are allowed to add arbitrary instructions in between the asm blocks and likely will to satisfy the `reg` inputs. In addition because you are modifying the stack pointer using `push` without restoring it back at the end of the asm block, you are causing UB.

**Comment by arrayJY** [comment]
I find the mistake: the pages of `user_stack` and `user_entry_point` have no `USER_ACCESSIBLE` flag. I should create a new mapping to physical frame with `USER_ACCESSIBLE`.

The issue should be closed.
