### ISSUE TITLE
Can't build the project

### ISSUE THREAD

**Issue by paulefoe** [phil-opp/blog_os#971]
I've followed through from chapter0 to chapter 1 of the new edition but was not able to compile the project
https://osblog.stephenmarz.com/ch1.html

Then I downloaded from GitHub chapter 1 from here
https://github.com/sgmarz/osblog/tree/master/risc_v/chapters/ch1

and when I do `make run` it gives me this error:

```
cargo build
   Compiling sos v0.1.0 (/home/paulefou/other_projects/rust-os)
error: language item required, but not found: `eh_personality`

error: aborting due to previous error

error: could not compile `sos`

To learn more, run the command again with --verbose.
make: *** [Makefile:28: all] Error 101
```

I also had to change `asm!` to `llvm_asm!` as compiler complained about legacy syntax.

**Comment by JakubGawron23** [comment]
This problem should be reported in the project repository (https://github.com/sgmarz/osblog), not here. And to fix compilation problems you have to update the syntax ``` asm! ```

**Comment by paulefoe** [comment]
Oh yeah, my bad,  sorry.
I will reopen in the appropriate repo
