### ISSUE TITLE
I don't know what's going on

### ISSUE THREAD

**Issue by JakubGawron23** [phil-opp/blog_os#975]
I am using WSL to build blog_os but now after updating WSL I cannot build the system and I get this error. What is wrong
![Zrzut ekranu (20)](https://user-images.githubusercontent.com/76694285/115827050-0e374c80-a40c-11eb-91b8-3897d9d49bd9.png)

**Comment by 12101111** [comment]
You don't have a c compiler installed.

Run `sudo apt install build-essential`

**Comment by JakubGawron23** [comment]
But I wouldn't expect that the c compiler was removed after the WSL update
