### ISSUE TITLE
Combining the first and second editions

### ISSUE THREAD

**Issue by JakubGawron23** [phil-opp/blog_os#976]
I wanted to link the bootloader from the first release to the code from the second release, which even succeeded but only up to the post-02 level because when I want to add any dependency to Cargo.toml and want to compile I get this error. What is true that all code may not work from second edition. But then I use the code from the first edition. And going through the posts from the first edition I am still stuck on VGA BUFFER which does not deign to work. Maybe I need to change x86_64-blog_os.json

![Zrzut ekranu (22)](https://user-images.githubusercontent.com/76694285/116049975-3f678500-a677-11eb-9ab3-61e03ee916e7.png)
![Zrzut ekranu (23)](https://user-images.githubusercontent.com/76694285/116049977-40001b80-a677-11eb-9591-69ac5639c7d5.png)

**Comment by phil-opp** [comment]
Could you post the content of your Makefile? Without it, it's difficult to guess what's going wrong here.

**Comment by JakubGawron23** [comment]
To be honest, I fixed that problem. The system is now running on its own bootloader, and I would love to make this code available for the blog as such a combination of first and second edition. I intend to complete the code with posts from **04** to **12**. In addition I used the library [Vga](https://github.com/rust-osdev/vga). Below is a screen shot of what it looks like at this point t

**Comment by JakubGawron23** [comment]
And yes generally this problem I reported here was caused by **rlibc** crate and by **xargo** tool but I don't know why it works like this. But now I changed from **xargo** to **cargo** and now it works
