### ISSUE TITLE
I would love to read more of this wonderful blog 😢 

### ISSUE THREAD

**Issue by kahirokunn** [phil-opp/blog_os#979]
Are you writing more? 😳

**Comment by phil-opp** [comment]
Yes, more content is planned! I'm currently working on a new third edition, which will add support for UEFI-based booting and pixel based framebuffers. After porting the second editon over, I plan to continue looking into multitasking and create abstractions for threads and processes. It will take some time to get there though.

**Comment by kahirokunn** [comment]
I'm so excited about that!
Thx🤩
