### ISSUE TITLE
.../rustlib/src/rust/Cargo.lock does not exist

### ISSUE THREAD

**Issue by joseph-henry** [phil-opp/blog_os#992]
Hello all,

First off, fantastic work on this, I was able to get the kernel up and running some time ago and it was a great experience. However getting back into this I've encountered the following error when attempting to build the repo straight out of the box:

```
error: "/usr/local/Cellar/rust/1.52.1/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src
```

I've already:
 - [x] Searched the blog post and tried the solution mentioned by `RWOverdijk`
 - [x] Uninstalled and re-installed rust
 - [x] Set default to stable and back to nightly.
 - [x] Updated to `rustc 1.54.0-nightly (cc77ba46f 2021-06-03)`
 
 But still no resolution. Any hints?

**Comment by phil-opp** [comment]
Great to hear that you were able to solve your problem and thanks a lot for sharing your solution! Not sure what the problem was, but if a reinstall fixed it it probably was some corrupted installation.
